CREATE OR REPLACE TRIGGER ACT_HIST_GRUPO_MCIA_TRANSP
AFTER
--	INSERT OR
	UPDATE OR
	DELETE
	ON C1150761
FOR EACH ROW
DECLARE
	mi_contador		NUMBER;
BEGIN		--cod_cob, txt_cob, basica, cod_cob_inf
	IF UPDATING THEN

		--Llamado a la Insercion del Historico del Grupo de la Mercancia
		PCK115_GRUPO_MERCANCIA_HIS.PRC_CARG_GRUPO_MCIA_HIS
		(
			P_GRUPO_MERCANCIA =>
				:OLD.GRUPO_MERCANCIA,
			P_DESC_GRUPO_MERCANCIA =>
				:OLD.DESC_GRUPO_MERCANCIA,
			P_TASA =>
				:OLD.TASA,
			P_FECHA_VIG =>
				:OLD.FECHA_VIG,
			P_FECHA_BAJA =>
				:OLD.FECHA_BAJA,
			P_TIPO_OPERACION =>
				PCK115_CONSTANTES_TRANSPORTES.ACTUALIZACION
		);

	ELSIF DELETING THEN

		--Llamado a la Insercion del Historico del Grupo de la Mercancia
		PCK115_GRUPO_MERCANCIA_HIS.PRC_CARG_GRUPO_MCIA_HIS
		(
			P_GRUPO_MERCANCIA =>
				:OLD.GRUPO_MERCANCIA,
			P_DESC_GRUPO_MERCANCIA =>
				:OLD.DESC_GRUPO_MERCANCIA,
			P_TASA =>
				:OLD.TASA,
			P_FECHA_VIG =>
				:OLD.FECHA_VIG,
			P_FECHA_BAJA =>
				:OLD.FECHA_BAJA,
			P_TIPO_OPERACION =>
				PCK115_CONSTANTES_TRANSPORTES.ELIMINACION
		);

	END IF;
END act_hist_grupo_mcia_transp;
/
