CREATE OR REPLACE TRIGGER ACT_HIST_PAR_DAT_VAR
AFTER
--	INSERT OR
	UPDATE OR
	DELETE
	ON C1990002
FOR EACH ROW
DECLARE
	mi_contador						NUMBER;
	mi_cod_error					C2990999.COD_ERROR%TYPE := 0;
	mi_error_mensaje			C2990999.ERROR_MENSAJE%TYPE := 'N/A';
	mi_error_real					C2990999.ERROR_REAL%TYPE := 'N/A';
BEGIN
	IF UPDATING THEN

		--Llamado a la Insercion del Historico de Parametrizacion de Datos Fijos
		PCK299_VALIDA_BANCA_VAR_721.PRC_CARG_DATO_VARIABLE_H	-- C1990002_H
		(
			P_COD_CIA =>
				:OLD.COD_CIA,
			P_COD_SECC =>
				:OLD.COD_SECC,
			P_COD_RAMO =>
				:OLD.COD_RAMO,
			P_SUB_PRODUCTO =>
				:OLD.SUB_PRODUCTO,
			P_ENTIDAD_COLOCADORA =>
				:OLD.ENTIDAD_COLOCADORA,
			P_COD_CAMPO =>
				:OLD.COD_CAMPO,
			P_POL_PPAL =>
				:OLD.POL_PPAL,
			P_COD_NIVEL =>
				:OLD.COD_NIVEL,
			P_NUM_SECU =>
				:OLD.NUM_SECU,
			P_CONSECUTIVO =>
				:OLD.CONSECUTIVO,
			P_DESCRIPCION =>
				:OLD.DESCRIPCION,
			P_LONG_CAMPO =>
				:OLD.LONG_CAMPO,
			P_TIPO_CAMPO =>
				:OLD.TIPO_CAMPO,
			P_MCA_ENVIADO =>
				:OLD.MCA_ENVIADO,
			P_MCA_SALIDA =>
				:OLD.MCA_SALIDA,
			P_HEREDA =>
				:OLD.HEREDA,
			P_USUARIO_CREACION =>
				:OLD.USUARIO_CREACION,
			P_FECHA_CREACION =>
				:OLD.FECHA_CREACION,
			P_UNICO =>
				:OLD.UNICO,
			P_VALOR_DEFECTO =>
				:OLD.VALOR_DEFECTO,
			P_PRC_VALIDACION =>
				:OLD.PRC_VALIDACION,
			P_PRC_PRE_CAMPO =>
				:OLD.PRC_PRE_CAMPO,
			P_PRC_POST_CAMPO =>
				:OLD.PRC_POST_CAMPO,
			P_IDENTIFICA_NOMINA =>
				:OLD.IDENTIFICA_NOMINA,
			P_USUARIO_MODIFICACION =>
				:OLD.USUARIO_MODIFICACION,
			P_FECHA_MODIFICACION =>
				:OLD.FECHA_MODIFICACION,
			P_NUM_POL_FLOT =>
				:OLD.NUM_POL_FLOT,
			P_NUM_END_FLOT =>
				:OLD.NUM_END_FLOT,
			P_VAR_COD_CAMPO =>
				:OLD.VAR_COD_CAMPO,
			P_TIPO_OPERACION =>
				'U',
			P_USUARIO_ACTUALIZACION =>
				SUBSTR(REPLACE(USER,'$',''),4,8),
			P_FECHA_ACTUALIZACION =>
				SYSDATE,
			P_COD_ERROR =>
				mi_cod_error,
			P_ERROR_MENSAJE =>
				mi_error_mensaje,
			P_ERROR_REAL =>
				mi_error_real
		);

	ELSIF DELETING THEN

		--Llamado a la Insercion del Historico de Parametrizacion de Datos Fijos
		PCK299_VALIDA_BANCA_VAR_721.PRC_CARG_DATO_VARIABLE_H	-- C1990002_H
		(
			P_COD_CIA =>
				:OLD.COD_CIA,
			P_COD_SECC =>
				:OLD.COD_SECC,
			P_COD_RAMO =>
				:OLD.COD_RAMO,
			P_SUB_PRODUCTO =>
				:OLD.SUB_PRODUCTO,
			P_ENTIDAD_COLOCADORA =>
				:OLD.ENTIDAD_COLOCADORA,
			P_COD_CAMPO =>
				:OLD.COD_CAMPO,
			P_POL_PPAL =>
				:OLD.POL_PPAL,
			P_COD_NIVEL =>
				:OLD.COD_NIVEL,
			P_NUM_SECU =>
				:OLD.NUM_SECU,
			P_CONSECUTIVO =>
				:OLD.CONSECUTIVO,
			P_DESCRIPCION =>
				:OLD.DESCRIPCION,
			P_LONG_CAMPO =>
				:OLD.LONG_CAMPO,
			P_TIPO_CAMPO =>
				:OLD.TIPO_CAMPO,
			P_MCA_ENVIADO =>
				:OLD.MCA_ENVIADO,
			P_MCA_SALIDA =>
				:OLD.MCA_SALIDA,
			P_HEREDA =>
				:OLD.HEREDA,
			P_USUARIO_CREACION =>
				:OLD.USUARIO_CREACION,
			P_FECHA_CREACION =>
				:OLD.FECHA_CREACION,
			P_UNICO =>
				:OLD.UNICO,
			P_VALOR_DEFECTO =>
				:OLD.VALOR_DEFECTO,
			P_PRC_VALIDACION =>
				:OLD.PRC_VALIDACION,
			P_PRC_PRE_CAMPO =>
				:OLD.PRC_PRE_CAMPO,
			P_PRC_POST_CAMPO =>
				:OLD.PRC_POST_CAMPO,
			P_IDENTIFICA_NOMINA =>
				:OLD.IDENTIFICA_NOMINA,
			P_USUARIO_MODIFICACION =>
				:OLD.USUARIO_MODIFICACION,
			P_FECHA_MODIFICACION =>
				:OLD.FECHA_MODIFICACION,
			P_NUM_POL_FLOT =>
				:OLD.NUM_POL_FLOT,
			P_NUM_END_FLOT =>
				:OLD.NUM_END_FLOT,
			P_VAR_COD_CAMPO =>
				:OLD.VAR_COD_CAMPO,
			P_TIPO_OPERACION =>
				'D',
			P_USUARIO_ACTUALIZACION =>
				SUBSTR(REPLACE(USER,'$',''),4,8),
			P_FECHA_ACTUALIZACION =>
				SYSDATE,
			P_COD_ERROR =>
				mi_cod_error,
			P_ERROR_MENSAJE =>
				mi_error_mensaje,
			P_ERROR_REAL =>
				mi_error_real
		);

	END IF;
END act_hist_par_dat_var;
/
