CREATE OR REPLACE TRIGGER ACT_HIST_PARAM_MODO_COB
AFTER
--	INSERT OR
	UPDATE OR
	DELETE
	ON C1150766
FOR EACH ROW
DECLARE
	mi_contador		NUMBER;
BEGIN		--cod_cob, txt_cob, basica, cod_cob_inf
	IF UPDATING THEN

		--Llamado a la Insercion de la Informacion Historica del Modo por Cobertura
		PCK115_PARAM_MODO_COB_HIS.PRC_CARG_MODO_COB_HI
		(
			P_MODO =>
				:OLD.MODO,
			P_COBERTURA =>
				:OLD.COBERTURA,
			P_FECHA_VIG =>
				:OLD.FECHA_VIG,
			P_FECHA_BAJA =>
				:OLD.FECHA_BAJA,
			P_TIPO_OPERACION =>
				PCK115_CONSTANTES_TRANSPORTES.ACTUALIZACION
		);

	ELSIF DELETING THEN

		--Llamado a la Insercion de la Informacion Historica del Modo por Cobertura
		PCK115_PARAM_MODO_COB_HIS.PRC_CARG_MODO_COB_HI
		(
			P_MODO =>
				:OLD.MODO,
			P_COBERTURA =>
				:OLD.COBERTURA,
			P_FECHA_VIG =>
				:OLD.FECHA_VIG,
			P_FECHA_BAJA =>
				:OLD.FECHA_BAJA,
			P_TIPO_OPERACION =>
				PCK115_CONSTANTES_TRANSPORTES.ELIMINACION
		);

	END IF;
END act_hist_param_modo_cob;
/
