CREATE OR REPLACE TRIGGER ACT_HIST_GRUPO_FACTOR_TRANSP
AFTER
--	INSERT OR
	UPDATE OR
	DELETE
	ON C1150762
FOR EACH ROW
DECLARE
	mi_contador		NUMBER;
BEGIN		--cod_cob, txt_cob, basica, cod_cob_inf
	IF UPDATING THEN

		--Llamado a la Insercion del Historico del Grupo por Factor
		PCK115_GRUPO_FACTOR_HIS.PRC_CARG_GRUPO_FACTOR_HIS
		(
			P_GRUPO_FACTOR =>
				:OLD.GRUPO_FACTOR,
			P_DESC_GRUPO_FACTOR =>
				:OLD.DESC_GRUPO_FACTOR,
			P_FACTOR =>
				:OLD.FACTOR,
			P_FECHA_VIG =>
				:OLD.FECHA_VIG,
			P_FECHA_BAJA =>
				:OLD.FECHA_BAJA,
			P_TIPO_OPERACION =>
				PCK115_CONSTANTES_TRANSPORTES.ACTUALIZACION
		);

	ELSIF DELETING THEN

		--Llamado a la Insercion del Historico del Grupo por Factor
		PCK115_GRUPO_FACTOR_HIS.PRC_CARG_GRUPO_FACTOR_HIS
		(
			P_GRUPO_FACTOR =>
				:OLD.GRUPO_FACTOR,
			P_DESC_GRUPO_FACTOR =>
				:OLD.DESC_GRUPO_FACTOR,
			P_FACTOR =>
				:OLD.FACTOR,
			P_FECHA_VIG =>
				:OLD.FECHA_VIG,
			P_FECHA_BAJA =>
				:OLD.FECHA_BAJA,
			P_TIPO_OPERACION =>
				PCK115_CONSTANTES_TRANSPORTES.ELIMINACION
		);

	END IF;
END act_hist_grupo_factor_transp;
/
