CREATE OR REPLACE TRIGGER ACT_HIST_ACTIV_ECON_TRANSP
AFTER
--	INSERT OR
	UPDATE OR
	DELETE
	ON C1150757
FOR EACH ROW
DECLARE
	mi_contador		NUMBER;
BEGIN		--cod_cob, txt_cob, basica, cod_cob_inf
	IF UPDATING THEN

		--Llamado a la Insercion del Historico de la Actividad Economica
		PCK115_ACTIVIDAD_ECON_HIS.PRC_CARG_ACTIVIDAD_ECON_HIS
		(
			P_SECUENCIA_ACT_ECO =>
				:OLD.SECUENCIA_ACT_ECO,
			P_GRAN_DIVISION =>
				:OLD.GRAN_DIVISION,
			P_DIVISION =>
				:OLD.DIVISION,
			P_GRUPO =>
				:OLD.GRUPO,
			P_CODIGO =>
				:OLD.CODIGO,
			P_DESCRIPCION_LARGA =>
				:OLD.DESCRIPCION_LARGA,
			P_CODIGO_FUENTE =>
				:OLD.CODIGO_FUENTE,
			P_MCA_ACTIVO =>
				:OLD.MCA_ACTIVO,
			P_TASA =>
				:OLD.TASA,
			P_REN_AUTOMATICA =>
				:OLD.REN_AUTOMATICA,
			P_INSPECCION =>
				:OLD.INSPECCION,
			P_FECHA_VIG =>
				:OLD.FECHA_VIG,
			P_FECHA_BAJA =>
				:OLD.FECHA_BAJA,
			P_TIPO_OPERACION =>
				PCK115_CONSTANTES_TRANSPORTES.ACTUALIZACION
		);

	ELSIF DELETING THEN

		--Llamado a la Insercion del Historico de la Actividad Economica
		PCK115_ACTIVIDAD_ECON_HIS.PRC_CARG_ACTIVIDAD_ECON_HIS
		(
			P_SECUENCIA_ACT_ECO =>
				:OLD.SECUENCIA_ACT_ECO,
			P_GRAN_DIVISION =>
				:OLD.GRAN_DIVISION,
			P_DIVISION =>
				:OLD.DIVISION,
			P_GRUPO =>
				:OLD.GRUPO,
			P_CODIGO =>
				:OLD.CODIGO,
			P_DESCRIPCION_LARGA =>
				:OLD.DESCRIPCION_LARGA,
			P_CODIGO_FUENTE =>
				:OLD.CODIGO_FUENTE,
			P_MCA_ACTIVO =>
				:OLD.MCA_ACTIVO,
			P_TASA =>
				:OLD.TASA,
			P_REN_AUTOMATICA =>
				:OLD.REN_AUTOMATICA,
			P_INSPECCION =>
				:OLD.INSPECCION,
			P_FECHA_VIG =>
				:OLD.FECHA_VIG,
			P_FECHA_BAJA =>
				:OLD.FECHA_BAJA,
			P_TIPO_OPERACION =>
				PCK115_CONSTANTES_TRANSPORTES.ELIMINACION
		);

	END IF;
END act_hist_activ_econ_transp;
/
