CREATE OR REPLACE TRIGGER ACT_HIST_PARAM_TIPO_POL_COB
AFTER
--	INSERT OR
	UPDATE OR
	DELETE
	ON C1150765
FOR EACH ROW
DECLARE
	mi_contador		NUMBER;
BEGIN		--cod_cob, txt_cob, basica, cod_cob_inf
	IF UPDATING THEN

		--Llamado a la Insercion de la Informacion Historica del Tipo de Poliza por Cobertura
		PCK115_PARAM_TIPO_POL_COB_HIS.PRC_CARG_TIPO_POL_COB_HI
		(
			P_TIPO_POLIZA =>
				:OLD.TIPO_POLIZA,
			P_TRAMO =>
				:OLD.TRAMO,
			P_TRAYECTO =>
				:OLD.TRAYECTO,
			P_COBERTURA =>
				:OLD.COBERTURA,
			P_BASICA =>
				:OLD.BASICA,
			P_DEPENDIENTE =>
				:OLD.DEPENDIENTE,
			P_OBLIGATORIA =>
				:OLD.OBLIGATORIA,
			P_PORC_DIST =>
				:OLD.PORC_DIST,
			P_PORC_DIST_BASICA =>
				:OLD.PORC_DIST_BASICA,
			P_PORC_DIST_SUMA =>
				:OLD.PORC_DIST_SUMA,
			P_FECHA_VIG =>
				:OLD.FECHA_VIG,
			P_FECHA_BAJA =>
				:OLD.FECHA_BAJA,
			P_TIPO_OPERACION =>
				PCK115_CONSTANTES_TRANSPORTES.ACTUALIZACION
		);

	ELSIF DELETING THEN

		--Llamado a la Insercion de la Informacion Historica del Tipo de Poliza por Cobertura
		PCK115_PARAM_TIPO_POL_COB_HIS.PRC_CARG_TIPO_POL_COB_HI
		(
			P_TIPO_POLIZA =>
				:OLD.TIPO_POLIZA,
			P_TRAMO =>
				:OLD.TRAMO,
			P_TRAYECTO =>
				:OLD.TRAYECTO,
			P_COBERTURA =>
				:OLD.COBERTURA,
			P_BASICA =>
				:OLD.BASICA,
			P_DEPENDIENTE =>
				:OLD.DEPENDIENTE,
			P_OBLIGATORIA =>
				:OLD.OBLIGATORIA,
			P_PORC_DIST =>
				:OLD.PORC_DIST,
			P_PORC_DIST_BASICA =>
				:OLD.PORC_DIST_BASICA,
			P_PORC_DIST_SUMA =>
				:OLD.PORC_DIST_SUMA,
			P_FECHA_VIG =>
				:OLD.FECHA_VIG,
			P_FECHA_BAJA =>
				:OLD.FECHA_BAJA,
			P_TIPO_OPERACION =>
				PCK115_CONSTANTES_TRANSPORTES.ELIMINACION
		);

	END IF;
END act_hist_param_tipo_pol_cob;
/
