CREATE OR REPLACE TRIGGER ACT_HIST_RUTA_TRANSP
AFTER
--	INSERT OR
	UPDATE OR
	DELETE
	ON C1150729
FOR EACH ROW
DECLARE
	mi_contador		NUMBER;
BEGIN		--cod_cob, txt_cob, basica, cod_cob_inf
	IF UPDATING THEN

		--Llamado a la Insercion del Historico de la Ruta
		PCK115_RUTA_HIS.PRC_CARG_RUTA_HIS
		(
			P_RUTA =>
				:OLD.RUTA,
			P_DESC_RUTA =>
				:OLD.DESC_RUTA,
			P_FECHA_VIG =>
				:OLD.FECHA_VIG,
			P_FECHA_BAJA =>
				:OLD.FECHA_BAJA,
			P_TIPO_OPERACION =>
				PCK115_CONSTANTES_TRANSPORTES.ACTUALIZACION
		);

	ELSIF DELETING THEN

		--Llamado a la Insercion del Historico de la Ruta
		PCK115_RUTA_HIS.PRC_CARG_RUTA_HIS
		(
			P_RUTA =>
				:OLD.RUTA,
			P_DESC_RUTA =>
				:OLD.DESC_RUTA,
			P_FECHA_VIG =>
				:OLD.FECHA_VIG,
			P_FECHA_BAJA =>
				:OLD.FECHA_BAJA,
			P_TIPO_OPERACION =>
				PCK115_CONSTANTES_TRANSPORTES.ELIMINACION
		);

	END IF;
END act_hist_ruta_transp;
/
