CREATE OR REPLACE TRIGGER ACT_HIST_RANG_DEDUC_COB_TR
AFTER
--	INSERT OR
	UPDATE OR
	DELETE
	ON C1150768
FOR EACH ROW
DECLARE
	mi_contador		NUMBER;
BEGIN		--cod_cob, txt_cob, basica, cod_cob_inf
	IF UPDATING THEN

		--Llamado a la Insercion del Historico del Rangos del Deducible X Cobertura
		PCK115_RANG_DEDUC_COB_HIS.PRC_CARG_RANG_DEDUC_COB_HIS
		(
			P_TIPO_RANGO =>
				:OLD.TIPO_RANGO,
			P_TRAMO =>
				:OLD.TRAMO,
			P_TRAYECTO =>
				:OLD.TRAYECTO,
			P_COBERTURA =>
				:OLD.COBERTURA,
			P_DEDUCIBLE =>
				:OLD.DEDUCIBLE,
			P_MEDIDA_DEDUCIBLE =>
				:OLD.MEDIDA_DEDUCIBLE,
			P_MODALIDAD_DEDUCIBLE =>
					:OLD.MODALIDAD_DEDUCIBLE,
			P_VALOR_DEDUCIBLE =>
				:OLD.VALOR_DEDUCIBLE,
			P_VALOR_DEDUCIBLE_MIN =>
				:OLD.VALOR_DEDUCIBLE_MIN,
			P_FECHA_VIG =>
				:OLD.FECHA_VIG,
			P_FECHA_BAJA =>
				:OLD.FECHA_BAJA,
			P_TIPO_OPERACION =>
				PCK115_CONSTANTES_TRANSPORTES.ACTUALIZACION
		);

	ELSIF DELETING THEN

		--Llamado a la Insercion del Historico del Rangos del Deducible X Cobertura
		PCK115_RANG_DEDUC_COB_HIS.PRC_CARG_RANG_DEDUC_COB_HIS
		(
			P_TIPO_RANGO =>
				:OLD.TIPO_RANGO,
			P_TRAMO =>
				:OLD.TRAMO,
			P_TRAYECTO =>
				:OLD.TRAYECTO,
			P_COBERTURA =>
				:OLD.COBERTURA,
			P_DEDUCIBLE =>
				:OLD.DEDUCIBLE,
			P_MEDIDA_DEDUCIBLE =>
				:OLD.MEDIDA_DEDUCIBLE,
			P_MODALIDAD_DEDUCIBLE =>
				:OLD.MODALIDAD_DEDUCIBLE,
			P_VALOR_DEDUCIBLE =>
				:OLD.VALOR_DEDUCIBLE,
			P_VALOR_DEDUCIBLE_MIN =>
				:OLD.VALOR_DEDUCIBLE_MIN,
			P_FECHA_VIG =>
				:OLD.FECHA_VIG,
			P_FECHA_BAJA =>
				:OLD.FECHA_BAJA,
			P_TIPO_OPERACION =>
				PCK115_CONSTANTES_TRANSPORTES.ELIMINACION
		);

	END IF;
END act_hist_rang_deduc_cob_tr;
/
