CREATE OR REPLACE TRIGGER ACT_HIST_PAR_DAT_FIJOS
AFTER
--	INSERT OR
	UPDATE OR
	DELETE
	ON C1990001
FOR EACH ROW
DECLARE
	mi_contador						NUMBER;
	mi_cod_error					C2990999.COD_ERROR%TYPE := 0;
	mi_error_mensaje			C2990999.ERROR_MENSAJE%TYPE := 'N/A';
	mi_error_real					C2990999.ERROR_REAL%TYPE := 'N/A';
BEGIN		
	IF UPDATING THEN

		--Llamado a la Insercion del Historico de Parametrizacion de Datos Fijos
		PCK299_VALIDA_BANCA.PRC_CARG_DATOS_PAR_DAT_FIJ_H-- C1990001_H
		(
			P_COD_CIA =>
				:OLD.COD_CIA,
			P_COD_SECC =>
				:OLD.COD_SECC,
			P_COD_RAMO =>
				:OLD.COD_RAMO,
			P_SUB_PRODUCTO =>
				:OLD.SUB_PRODUCTO,
			P_ENTIDAD_COLOCADORA =>
				:OLD.ENTIDAD_COLOCADORA,
			P_POL_PPAL =>
				:OLD.POL_PPAL,
			P_NUM_POL_FLOT =>
				:OLD.NUM_POL_FLOT,
			P_NUM_END_FLOT =>
				:OLD.NUM_END_FLOT,
			P_MON_UNICA =>
				:OLD.MON_UNICA,
			P_MON_HEREDA =>
				:OLD.MON_HEREDA,
			P_MON_VALIDA =>
				:OLD.MON_VALIDA,
			P_COD_MON_DEF =>
				:OLD.COD_MON_DEF,
			P_PROD_UNICO =>
				:OLD.PROD_UNICO,
			P_PROD_HEREDA =>
				:OLD.PROD_HEREDA,
			P_PROD_VALIDA =>
				:OLD.PROD_VALIDA,
			P_COD_PROD_DEF =>
				:OLD.COD_PROD_DEF,
			P_CONVENIO_AGENTE =>
				:OLD.CONVENIO_AGENTE,
			P_PER_FACT_UNICO =>
				:OLD.PER_FACT_UNICO,
			P_PER_FACT_HEREDA =>
				:OLD.PER_FACT_HEREDA,
			P_PER_FACT_VALIDA =>
				:OLD.PER_FACT_VALIDA,
			P_PER_FAC_DEF =>
				:OLD.PER_FAC_DEF,
			P_FOR_COBRO_UNICA =>
				:OLD.FOR_COBRO_UNICA,
			P_FOR_COBRO_HEREDA =>
				:OLD.FOR_COBRO_HEREDA,
			P_FOR_COBRO_VALIDA =>
				:OLD.FOR_COBRO_VALIDA,
			P_FOR_COBRO_DEF =>
				:OLD.FOR_COBRO_DEF,
			P_VIGENCIA_ANUAL =>
				:OLD.VIGENCIA_ANUAL,
			P_VENC_UNIF_HEREDA =>
				:OLD.VENC_UNIF_HEREDA,
--			P_VENC_UNIF_DEF =>
--				:OLD.VENC_UNIF_DEF,
			P_COD_COA_UNICA =>
				:OLD.COD_COA_UNICA,
			P_COD_COA_HEREDA =>
				:OLD.COD_COA_HEREDA,
			P_COD_COA_VALIDA =>
				:OLD.COD_COA_VALIDA,
			P_COD_COA_DEF =>
				:OLD.COD_COA_DEF,
			P_COD_CIACOA_DEF =>
				:OLD.COD_CIACOA_DEF,
			P_NUM_POL_COA_DEF =>
				:OLD.NUM_POL_COA_DEF,
			P_NUM_ENDOSO_COA_DEF =>
				:OLD.NUM_ENDOSO_COA_DEF,
			P_PORC_PARTCOA_DEF =>
				:OLD.PORC_PARTCOA_DEF,
			P_MCA_FACTURA =>
				:OLD.MCA_FACTURA,
			P_COD_ENTIDAD_UNICA =>
				:OLD.COD_ENTIDAD_UNICA,
			P_COD_ENTIDAD_HEREDA =>
				:OLD.COD_ENTIDAD_HEREDA,
			P_COD_ENTIDAD_VALIDA =>
				:OLD.COD_ENTIDAD_VALIDA,
			P_COD_ENTIDAD_DEF =>
				:OLD.COD_ENTIDAD_DEF,
			P_CANAL_DESCTO_UNICA =>
				:OLD.CANAL_DESCTO_UNICA,
			P_CANAL_DESCTO_HEREDA =>
				:OLD.CANAL_DESCTO_HEREDA,
			P_CANAL_DESCTO_VALIDA =>
				:OLD.CANAL_DESCTO_VALIDA,
			P_CANAL_DESCTO_DEF =>
				:OLD.CANAL_DESCTO_DEF,
			P_TOMADOR_UNICO =>
				:OLD.TOMADOR_UNICO,
			P_TOMADOR_HEREDA =>
				:OLD.TOMADOR_HEREDA,
			P_TDOC_TERCERO_VALIDA =>
				:OLD.TDOC_TERCERO_VALIDA,
			P_NRO_DOCUMTO_VALIDA =>
				:OLD.NRO_DOCUMTO_VALIDA,
			P_SEC_TERCERO_VALIDA =>
				:OLD.SEC_TERCERO_VALIDA,
			P_TDOC_TERCERO =>
				:OLD.TDOC_TERCERO,
			P_NRO_DOCUMTO =>
				:OLD.NRO_DOCUMTO,
			P_SEC_TERCERO =>
				:OLD.SEC_TERCERO,
			P_NOMINA =>
				:OLD.NOMINA,
			P_COD_COB_NOMINA =>
				:OLD.COD_COB_NOMINA,
			P_USUARIO_CREACION =>
				:OLD.USUARIO_CREACION,
			P_FECHA_CREACION =>
				:OLD.FECHA_CREACION,
			P_USUARIO_MODIFICACION =>
				:OLD.USUARIO_MODIFICACION,
			P_FECHA_MODIFICACION =>
				:OLD.FECHA_MODIFICACION,
			P_TIPO_OPERACION =>
				'U',
			P_USUARIO_ACTUALIZACION =>
				SUBSTR(REPLACE(USER,'$',''),4,8),
			P_FECHA_ACTUALIZACION =>
				SYSDATE,
			P_COD_ERROR =>
				mi_cod_error,
			P_ERROR_MENSAJE =>
				mi_error_mensaje,
			P_ERROR_REAL =>
				mi_error_real
		);

	ELSIF DELETING THEN

		--Llamado a la Insercion del Historico de Parametrizacion de Datos Fijos
		PCK299_VALIDA_BANCA.PRC_CARG_DATOS_PAR_DAT_FIJ_H-- C1990001_H
		(
			P_COD_CIA =>
				:OLD.COD_CIA,
			P_COD_SECC =>
				:OLD.COD_SECC,
			P_COD_RAMO =>
				:OLD.COD_RAMO,
			P_SUB_PRODUCTO =>
				:OLD.SUB_PRODUCTO,
			P_ENTIDAD_COLOCADORA =>
				:OLD.ENTIDAD_COLOCADORA,
			P_POL_PPAL =>
				:OLD.POL_PPAL,
			P_NUM_POL_FLOT =>
				:OLD.NUM_POL_FLOT,
			P_NUM_END_FLOT =>
				:OLD.NUM_END_FLOT,
			P_MON_UNICA =>
				:OLD.MON_UNICA,
			P_MON_HEREDA =>
				:OLD.MON_HEREDA,
			P_MON_VALIDA =>
				:OLD.MON_VALIDA,
			P_COD_MON_DEF =>
				:OLD.COD_MON_DEF,
			P_PROD_UNICO =>
				:OLD.PROD_UNICO,
			P_PROD_HEREDA =>
				:OLD.PROD_HEREDA,
			P_PROD_VALIDA =>
				:OLD.PROD_VALIDA,
			P_COD_PROD_DEF =>
				:OLD.COD_PROD_DEF,
			P_CONVENIO_AGENTE =>
				:OLD.CONVENIO_AGENTE,
			P_PER_FACT_UNICO =>
				:OLD.PER_FACT_UNICO,
			P_PER_FACT_HEREDA =>
				:OLD.PER_FACT_HEREDA,
			P_PER_FACT_VALIDA =>
				:OLD.PER_FACT_VALIDA,
			P_PER_FAC_DEF =>
				:OLD.PER_FAC_DEF,
			P_FOR_COBRO_UNICA =>
				:OLD.FOR_COBRO_UNICA,
			P_FOR_COBRO_HEREDA =>
				:OLD.FOR_COBRO_HEREDA,
			P_FOR_COBRO_VALIDA =>
				:OLD.FOR_COBRO_VALIDA,
			P_FOR_COBRO_DEF =>
				:OLD.FOR_COBRO_DEF,
			P_VIGENCIA_ANUAL =>
				:OLD.VIGENCIA_ANUAL,
			P_VENC_UNIF_HEREDA =>
				:OLD.VENC_UNIF_HEREDA,
--			P_VENC_UNIF_DEF =>
--				:OLD.VENC_UNIF_DEF,
			P_COD_COA_UNICA =>
				:OLD.COD_COA_UNICA,
			P_COD_COA_HEREDA =>
				:OLD.COD_COA_HEREDA,
			P_COD_COA_VALIDA =>
				:OLD.COD_COA_VALIDA,
			P_COD_COA_DEF =>
				:OLD.COD_COA_DEF,
			P_COD_CIACOA_DEF =>
				:OLD.COD_CIACOA_DEF,
			P_NUM_POL_COA_DEF =>
				:OLD.NUM_POL_COA_DEF,
			P_NUM_ENDOSO_COA_DEF =>
				:OLD.NUM_ENDOSO_COA_DEF,
			P_PORC_PARTCOA_DEF =>
				:OLD.PORC_PARTCOA_DEF,
			P_MCA_FACTURA =>
				:OLD.MCA_FACTURA,
			P_COD_ENTIDAD_UNICA =>
				:OLD.COD_ENTIDAD_UNICA,
			P_COD_ENTIDAD_HEREDA =>
				:OLD.COD_ENTIDAD_HEREDA,
			P_COD_ENTIDAD_VALIDA =>
				:OLD.COD_ENTIDAD_VALIDA,
			P_COD_ENTIDAD_DEF =>
				:OLD.COD_ENTIDAD_DEF,
			P_CANAL_DESCTO_UNICA =>
				:OLD.CANAL_DESCTO_UNICA,
			P_CANAL_DESCTO_HEREDA =>
				:OLD.CANAL_DESCTO_HEREDA,
			P_CANAL_DESCTO_VALIDA =>
				:OLD.CANAL_DESCTO_VALIDA,
			P_CANAL_DESCTO_DEF =>
				:OLD.CANAL_DESCTO_DEF,
			P_TOMADOR_UNICO =>
				:OLD.TOMADOR_UNICO,
			P_TOMADOR_HEREDA =>
				:OLD.TOMADOR_HEREDA,
			P_TDOC_TERCERO_VALIDA =>
				:OLD.TDOC_TERCERO_VALIDA,
			P_NRO_DOCUMTO_VALIDA =>
				:OLD.NRO_DOCUMTO_VALIDA,
			P_SEC_TERCERO_VALIDA =>
				:OLD.SEC_TERCERO_VALIDA,
			P_TDOC_TERCERO =>
				:OLD.TDOC_TERCERO,
			P_NRO_DOCUMTO =>
				:OLD.NRO_DOCUMTO,
			P_SEC_TERCERO =>
				:OLD.SEC_TERCERO,
			P_NOMINA =>
				:OLD.NOMINA,
			P_COD_COB_NOMINA =>
				:OLD.COD_COB_NOMINA,
			P_USUARIO_CREACION =>
				:OLD.USUARIO_CREACION,
			P_FECHA_CREACION =>
				:OLD.FECHA_CREACION,
			P_USUARIO_MODIFICACION =>
				:OLD.USUARIO_MODIFICACION,
			P_FECHA_MODIFICACION =>
				:OLD.FECHA_MODIFICACION,
			P_TIPO_OPERACION =>
				'D',
			P_USUARIO_ACTUALIZACION =>
				SUBSTR(REPLACE(USER,'$',''),4,8),
			P_FECHA_ACTUALIZACION =>
				SYSDATE,
			P_COD_ERROR =>
				mi_cod_error,
			P_ERROR_MENSAJE =>
				mi_error_mensaje,
			P_ERROR_REAL =>
				mi_error_real
		);

	END IF;
END act_hist_par_dat_fijos;
/
