CREATE OR REPLACE TRIGGER ACT_HIST_DEDUC_COBERT_TRANSP
AFTER
--	INSERT OR
	UPDATE OR
	DELETE
	ON C1150759
FOR EACH ROW
DECLARE
	mi_contador		NUMBER;
BEGIN		--cod_cob, txt_cob, basica, cod_cob_inf
	IF UPDATING THEN

		--Llamado a la Insercion del Historico del Deducible X Cobertura
		PCK115_DEDUC_COBERT_HIS.PRC_CARG_DEDUC_COBERT_HIS
		(
			P_TRAMO =>
				:OLD.TRAMO,
			P_TRAYECTO =>
				:OLD.TRAYECTO,
			P_COBERTURA =>
				:OLD.COBERTURA,
			P_DEDUCIBLE =>
				:OLD.DEDUCIBLE,
			P_MEDIDA_DEDUCIBLE =>
				:OLD.MEDIDA_DEDUCIBLE,
			P_MODALIDAD_DEDUCIBLE =>
					:OLD.MODALIDAD_DEDUCIBLE,
			P_VALOR_DEDUCIBLE =>
				:OLD.VALOR_DEDUCIBLE,
			P_VALOR_DEDUCIBLE_MIN =>
				:OLD.VALOR_DEDUCIBLE_MIN,
			P_FECHA_VIG =>
				:OLD.FECHA_VIG,
			P_FECHA_BAJA =>
				:OLD.FECHA_BAJA,
			P_TIPO_OPERACION =>
				PCK115_CONSTANTES_TRANSPORTES.ACTUALIZACION
		);

	ELSIF DELETING THEN

		--Llamado a la Insercion del Historico del Deducible X Cobertura
		PCK115_DEDUC_COBERT_HIS.PRC_CARG_DEDUC_COBERT_HIS
		(
			P_TRAMO =>
				:OLD.TRAMO,
			P_TRAYECTO =>
				:OLD.TRAYECTO,
			P_COBERTURA =>
				:OLD.COBERTURA,
			P_DEDUCIBLE =>
				:OLD.DEDUCIBLE,
			P_MEDIDA_DEDUCIBLE =>
				:OLD.MEDIDA_DEDUCIBLE,
			P_MODALIDAD_DEDUCIBLE =>
				:OLD.MODALIDAD_DEDUCIBLE,
			P_VALOR_DEDUCIBLE =>
				:OLD.VALOR_DEDUCIBLE,
			P_VALOR_DEDUCIBLE_MIN =>
				:OLD.VALOR_DEDUCIBLE_MIN,
			P_FECHA_VIG =>
				:OLD.FECHA_VIG,
			P_FECHA_BAJA =>
				:OLD.FECHA_BAJA,
			P_TIPO_OPERACION =>
				PCK115_CONSTANTES_TRANSPORTES.ELIMINACION
		);

	END IF;
END act_hist_deduc_cobert_transp;
/
