CREATE OR REPLACE TRIGGER ACT_HIST_MCIA_TRANSP
AFTER
--	INSERT OR
	UPDATE OR
	DELETE
	ON C1150712
FOR EACH ROW
DECLARE
	mi_contador		NUMBER;
BEGIN		--cod_cob, txt_cob, basica, cod_cob_inf
	IF UPDATING THEN

		--Llamado a la Insercion del Historico de la Mercancia
		PCK115_MERCANCIA_HIS.PRC_CARG_MERCANCIA_HIS
		(
			P_MERCANCIA =>
				:OLD.MERCANCIA,
			P_MERCANCIA_PADRE =>
				:OLD.MERCANCIA_PADRE,
			P_TIPO_POLIZA =>
				:OLD.TIPO_POLIZA,
			P_NIVEL =>
				:OLD.NIVEL,
			P_GRUPO_MERCANCIA =>
				:OLD.GRUPO_MERCANCIA,
			P_DESC_MERCANCIA =>
				:OLD.DESC_MERCANCIA,
			P_FECHA_VIG =>
				:OLD.FECHA_VIG,
			P_FECHA_BAJA =>
				:OLD.FECHA_BAJA,
			P_TIPO_OPERACION =>
				PCK115_CONSTANTES_TRANSPORTES.ACTUALIZACION
		);

	ELSIF DELETING THEN

		--Llamado a la Insercion del Historico de la Mercancia
		PCK115_MERCANCIA_HIS.PRC_CARG_MERCANCIA_HIS
		(
			P_MERCANCIA =>
				:OLD.MERCANCIA,
			P_MERCANCIA_PADRE =>
				:OLD.MERCANCIA_PADRE,
			P_TIPO_POLIZA =>
				:OLD.TIPO_POLIZA,
			P_NIVEL =>
				:OLD.NIVEL,
			P_GRUPO_MERCANCIA =>
				:OLD.GRUPO_MERCANCIA,
			P_DESC_MERCANCIA =>
				:OLD.DESC_MERCANCIA,
			P_FECHA_VIG =>
				:OLD.FECHA_VIG,
			P_FECHA_BAJA =>
				:OLD.FECHA_BAJA,
			P_TIPO_OPERACION =>
				PCK115_CONSTANTES_TRANSPORTES.ELIMINACION
		);

	END IF;
END act_hist_mcia_transp;
/
