CREATE OR REPLACE TRIGGER ACT_HIST_DEDUC_MCIA_TRANSP
AFTER
--	INSERT OR
	UPDATE OR
	DELETE
	ON C2150750
FOR EACH ROW
DECLARE
	mi_contador		NUMBER;
BEGIN		--cod_cob, txt_cob, basica, cod_cob_inf
	IF UPDATING THEN

		--Llamado a la Insercion del Historico del Deducible X Mercancia
		PCK215_DEDUC_MCIA_HIS.PRC_CARG_DEDUC_MCIA_HIS
		(
			P_MERCANCIA =>
				:OLD.MERCANCIA,
			P_DEDUCIBLE =>
				:OLD.DEDUCIBLE,
			P_MEDIDA_DEDUCIBLE =>
				:OLD.MEDIDA_DEDUCIBLE,
			P_MODALIDAD_DEDUCIBLE =>
				:OLD.MODALIDAD_DEDUCIBLE,
			P_VALOR_DEDUCIBLE =>
				:OLD.VALOR_DEDUCIBLE,
			P_VALOR_DEDUCIBLE_MIN =>
				:OLD.VALOR_DEDUCIBLE_MIN,
			P_FECHA_VIG =>
				:OLD.FECHA_VIG,
			P_FECHA_BAJA =>
				:OLD.FECHA_BAJA,
			P_TIPO_OPERACION =>
				PCK115_CONSTANTES_TRANSPORTES.ACTUALIZACION
		);

	ELSIF DELETING THEN

		--Llamado a la Insercion del Historico del Deducible X Mercancia
		PCK215_DEDUC_MCIA_HIS.PRC_CARG_DEDUC_MCIA_HIS
		(
			P_MERCANCIA =>
				:OLD.MERCANCIA,
			P_DEDUCIBLE =>
				:OLD.DEDUCIBLE,
			P_MEDIDA_DEDUCIBLE =>
				:OLD.MEDIDA_DEDUCIBLE,
			P_MODALIDAD_DEDUCIBLE =>
				:OLD.MODALIDAD_DEDUCIBLE,
			P_VALOR_DEDUCIBLE =>
				:OLD.VALOR_DEDUCIBLE,
			P_VALOR_DEDUCIBLE_MIN =>
				:OLD.VALOR_DEDUCIBLE_MIN,
			P_FECHA_VIG =>
				:OLD.FECHA_VIG,
			P_FECHA_BAJA =>
				:OLD.FECHA_BAJA,
			P_TIPO_OPERACION =>
				PCK115_CONSTANTES_TRANSPORTES.ELIMINACION
		);

	END IF;
END act_hist_deduc_mcia_transp;
/
