CREATE OR REPLACE TRIGGER ACT_HIST_TRANSP_TRANSP
AFTER
--	INSERT OR
	UPDATE OR
	DELETE
	ON C1150727
FOR EACH ROW
DECLARE
	mi_contador		NUMBER;
BEGIN		--cod_cob, txt_cob, basica, cod_cob_inf
	IF UPDATING THEN

		--Llamado a la Insercion del Historico del Transportador
		PCK115_TRANSPORTADOR_HIS.PRC_CARG_TRANSPORTADOR_HIS
		(
			P_TRANSPORTADOR =>
				:OLD.TRANSPORTADOR,
			P_IDENT_TRANSPORTADOR =>
				:OLD.IDENT_TRANSPORTADOR,
			P_DESC_TRANSPORTADOR =>
				:OLD.DESC_TRANSPORTADOR,
			P_CALIFICA_GNP =>
				:OLD.CALIFICA_GNP,
			P_TIPO_TRANS =>
				:OLD.TIPO_TRANS,
			P_FECHA_VIG =>
				:OLD.FECHA_VIG,
			P_FECHA_BAJA =>
				:OLD.FECHA_BAJA,
			P_TIPO_OPERACION =>
				PCK115_CONSTANTES_TRANSPORTES.ACTUALIZACION
		);

	ELSIF DELETING THEN

		--Llamado a la Insercion del Historico del Transportador
		PCK115_TRANSPORTADOR_HIS.PRC_CARG_TRANSPORTADOR_HIS
		(
			P_TRANSPORTADOR =>
				:OLD.TRANSPORTADOR,
			P_IDENT_TRANSPORTADOR =>
				:OLD.IDENT_TRANSPORTADOR,
			P_DESC_TRANSPORTADOR =>
				:OLD.DESC_TRANSPORTADOR,
			P_CALIFICA_GNP =>
				:OLD.CALIFICA_GNP,
			P_TIPO_TRANS =>
				:OLD.TIPO_TRANS,
			P_FECHA_VIG =>
				:OLD.FECHA_VIG,
			P_FECHA_BAJA =>
				:OLD.FECHA_BAJA,
			P_TIPO_OPERACION =>
				PCK115_CONSTANTES_TRANSPORTES.ELIMINACION
		);

	END IF;
END act_hist_transp_transp;
/
