CREATE OR REPLACE TRIGGER APLI_RES_EPS_HIST 
BEFORE INSERT ON APLICACION_RESPUESTA_EPS_HIST 
FOR EACH ROW
WHEN (new.ID_APLI_RES_EPS_HIST IS NULL)
BEGIN
  SELECT SEQ_APLI_RES_EPS_HIST.NEXTVAL
  INTO   :new.ID_APLI_RES_EPS_HIST
  FROM   dual;
END;
/
