CREATE OR REPLACE TRIGGER audit_a1001301
BEFORE  DELETE ON ops$puma.a1001301
FOR EACH ROW
BEGIN
    IF TRUNC(:OLD.FECHA_EQUIPO) < TRUNC(SYSDATE)  AND
       USER != 'OPS$INTASI14' THEN
        RAISE_APPLICATION_ERROR (-20500,'NO PUEDE BORRAR AGENTES');
   END IF;
END;
/
