CREATE OR REPLACE TRIGGER cg$BIR_SIM_FER_PERSONA
BEFORE INSERT ON SIM_FER_PERSONA FOR EACH ROW
DECLARE
    cg$rec SIM_PCK_FER_PERSONA.cg$row_type;
    cg$ind SIM_PCK_FER_PERSONA.cg$ind_type;
BEGIN
--  Application_logic Pre-Before-Insert-row <<Start>>
--  Application_logic Pre-Before-Insert-row << End >>

--  Load cg$rec/cg$ind values from new

    cg$rec.NUMERO_DOCUMENTO := :new.NUMERO_DOCUMENTO;
    cg$ind.NUMERO_DOCUMENTO := TRUE;
    cg$rec.TIPO_IDENTIFICACION := :new.TIPO_IDENTIFICACION;
    cg$ind.TIPO_IDENTIFICACION := TRUE;
    cg$rec.CONSECUTIVO := :new.CONSECUTIVO;
    cg$ind.CONSECUTIVO := TRUE;
    cg$rec.PRIMER_NOMBRE := :new.PRIMER_NOMBRE;
    cg$ind.PRIMER_NOMBRE := TRUE;
    cg$rec.SEGUNDO_NOMBRE := :new.SEGUNDO_NOMBRE;
    cg$ind.SEGUNDO_NOMBRE := TRUE;
    cg$rec.PRIMER_APELLIDO := :new.PRIMER_APELLIDO;
    cg$ind.PRIMER_APELLIDO := TRUE;
    cg$rec.SEGUNDO_APELLIDO := :new.SEGUNDO_APELLIDO;
    cg$ind.SEGUNDO_APELLIDO := TRUE;
    cg$rec.SEXO := :new.SEXO;
    cg$ind.SEXO := TRUE;
    cg$rec.FECHA_NACIMIENTO := :new.FECHA_NACIMIENTO;
    cg$ind.FECHA_NACIMIENTO := TRUE;

    if not (SIM_PCK_FER_PERSONA.called_from_package) then
        SIM_PCK_FER_PERSONA.validate_arc(cg$rec);
        SIM_PCK_FER_PERSONA.validate_domain(cg$rec);

        SIM_PCK_FER_PERSONA.ins(cg$rec, cg$ind, FALSE);
        SIM_PCK_FER_PERSONA.called_from_package := FALSE;
    end if;

    SIM_PCK_FER_PERSONA.cg$table(SIM_PCK_FER_PERSONA.idx).NUMERO_DOCUMENTO := cg$rec.NUMERO_DOCUMENTO;
    SIM_PCK_FER_PERSONA.cg$tableind(SIM_PCK_FER_PERSONA.idx).NUMERO_DOCUMENTO := cg$ind.NUMERO_DOCUMENTO;

    SIM_PCK_FER_PERSONA.cg$table(SIM_PCK_FER_PERSONA.idx).TIPO_IDENTIFICACION := cg$rec.TIPO_IDENTIFICACION;
    SIM_PCK_FER_PERSONA.cg$tableind(SIM_PCK_FER_PERSONA.idx).TIPO_IDENTIFICACION := cg$ind.TIPO_IDENTIFICACION;

    SIM_PCK_FER_PERSONA.cg$table(SIM_PCK_FER_PERSONA.idx).CONSECUTIVO := cg$rec.CONSECUTIVO;
    SIM_PCK_FER_PERSONA.cg$tableind(SIM_PCK_FER_PERSONA.idx).CONSECUTIVO := cg$ind.CONSECUTIVO;

    SIM_PCK_FER_PERSONA.cg$table(SIM_PCK_FER_PERSONA.idx).PRIMER_NOMBRE := cg$rec.PRIMER_NOMBRE;
    SIM_PCK_FER_PERSONA.cg$tableind(SIM_PCK_FER_PERSONA.idx).PRIMER_NOMBRE := cg$ind.PRIMER_NOMBRE;

    SIM_PCK_FER_PERSONA.cg$table(SIM_PCK_FER_PERSONA.idx).SEGUNDO_NOMBRE := cg$rec.SEGUNDO_NOMBRE;
    SIM_PCK_FER_PERSONA.cg$tableind(SIM_PCK_FER_PERSONA.idx).SEGUNDO_NOMBRE := cg$ind.SEGUNDO_NOMBRE;

    SIM_PCK_FER_PERSONA.cg$table(SIM_PCK_FER_PERSONA.idx).PRIMER_APELLIDO := cg$rec.PRIMER_APELLIDO;
    SIM_PCK_FER_PERSONA.cg$tableind(SIM_PCK_FER_PERSONA.idx).PRIMER_APELLIDO := cg$ind.PRIMER_APELLIDO;

    SIM_PCK_FER_PERSONA.cg$table(SIM_PCK_FER_PERSONA.idx).SEGUNDO_APELLIDO := cg$rec.SEGUNDO_APELLIDO;
    SIM_PCK_FER_PERSONA.cg$tableind(SIM_PCK_FER_PERSONA.idx).SEGUNDO_APELLIDO := cg$ind.SEGUNDO_APELLIDO;

    SIM_PCK_FER_PERSONA.cg$table(SIM_PCK_FER_PERSONA.idx).SEXO := cg$rec.SEXO;
    SIM_PCK_FER_PERSONA.cg$tableind(SIM_PCK_FER_PERSONA.idx).SEXO := cg$ind.SEXO;

    SIM_PCK_FER_PERSONA.cg$table(SIM_PCK_FER_PERSONA.idx).FECHA_NACIMIENTO := cg$rec.FECHA_NACIMIENTO;
    SIM_PCK_FER_PERSONA.cg$tableind(SIM_PCK_FER_PERSONA.idx).FECHA_NACIMIENTO := cg$ind.FECHA_NACIMIENTO;

    SIM_PCK_FER_PERSONA.idx := SIM_PCK_FER_PERSONA.idx + 1;

    :new.NUMERO_DOCUMENTO := cg$rec.NUMERO_DOCUMENTO;
    :new.TIPO_IDENTIFICACION := cg$rec.TIPO_IDENTIFICACION;
    :new.CONSECUTIVO := cg$rec.CONSECUTIVO;
    :new.PRIMER_NOMBRE := cg$rec.PRIMER_NOMBRE;
    :new.SEGUNDO_NOMBRE := cg$rec.SEGUNDO_NOMBRE;
    :new.PRIMER_APELLIDO := cg$rec.PRIMER_APELLIDO;
    :new.SEGUNDO_APELLIDO := cg$rec.SEGUNDO_APELLIDO;
    :new.SEXO := cg$rec.SEXO;
    :new.FECHA_NACIMIENTO := cg$rec.FECHA_NACIMIENTO;

--  Application_logic Post-Before-Insert-row <<Start>>
--  Application_logic Post-Before-Insert-row << End >>
END;
/
