CREATE OR REPLACE TRIGGER cg$BIR_SIM_FER_ASEGURADO
BEFORE INSERT ON SIM_FER_ASEGURADO FOR EACH ROW
DECLARE
    cg$rec SIM_PCK_FER_ASEGURADO.cg$row_type;
    cg$ind SIM_PCK_FER_ASEGURADO.cg$ind_type;
BEGIN
--  Application_logic Pre-Before-Insert-row <<Start>>
--  Application_logic Pre-Before-Insert-row << End >>

--  Load cg$rec/cg$ind values from new

    cg$rec.NUMERO_DOCUMENTO := :new.NUMERO_DOCUMENTO;
    cg$ind.NUMERO_DOCUMENTO := TRUE;
    cg$rec.TIPO_IDENTIFICACION := :new.TIPO_IDENTIFICACION;
    cg$ind.TIPO_IDENTIFICACION := TRUE;
    cg$rec.NUMERO_CERTIFICADO := :new.NUMERO_CERTIFICADO;
    cg$ind.NUMERO_CERTIFICADO := TRUE;
    cg$rec.CONSECUTIVO := :new.CONSECUTIVO;
    cg$ind.CONSECUTIVO := TRUE;
    cg$rec.NUMERO_GR := :new.NUMERO_GR;
    cg$ind.NUMERO_GR := TRUE;
    cg$rec.FECHA_INICIO_VIGENCIA := :new.FECHA_INICIO_VIGENCIA;
    cg$ind.FECHA_INICIO_VIGENCIA := TRUE;
    cg$rec.VALOR_ASEGURADO := :new.VALOR_ASEGURADO;
    cg$ind.VALOR_ASEGURADO := TRUE;
    cg$rec.OPCION_COBERTURA := :new.OPCION_COBERTURA;
    cg$ind.OPCION_COBERTURA := TRUE;
    cg$rec.PRIMA := :new.PRIMA;
    cg$ind.PRIMA := TRUE;
    cg$rec.EXTRAPRIMA := :new.EXTRAPRIMA;
    cg$ind.EXTRAPRIMA := TRUE;
    cg$rec.PORCENTAJE_EXTRAPRIMA := :new.PORCENTAJE_EXTRAPRIMA;
    cg$ind.PORCENTAJE_EXTRAPRIMA := TRUE;
    cg$rec.TIPO_AFILIACION := :new.TIPO_AFILIACION;
    cg$ind.TIPO_AFILIACION := TRUE;
    cg$rec.FECHA_CANCELACION := :new.FECHA_CANCELACION;
    cg$ind.FECHA_CANCELACION := TRUE;
    cg$rec.FECHA_CREACION := :new.FECHA_CREACION;
    cg$ind.FECHA_CREACION := TRUE;
    cg$rec.SUCURSAL := :new.SUCURSAL;
    cg$ind.SUCURSAL := TRUE;

    if not (SIM_PCK_FER_ASEGURADO.called_from_package) then
        SIM_PCK_FER_ASEGURADO.validate_arc(cg$rec);
        SIM_PCK_FER_ASEGURADO.validate_domain(cg$rec);

        SIM_PCK_FER_ASEGURADO.ins(cg$rec, cg$ind, FALSE);
        SIM_PCK_FER_ASEGURADO.called_from_package := FALSE;
    end if;

    SIM_PCK_FER_ASEGURADO.cg$table(SIM_PCK_FER_ASEGURADO.idx).NUMERO_DOCUMENTO := cg$rec.NUMERO_DOCUMENTO;
    SIM_PCK_FER_ASEGURADO.cg$tableind(SIM_PCK_FER_ASEGURADO.idx).NUMERO_DOCUMENTO := cg$ind.NUMERO_DOCUMENTO;

    SIM_PCK_FER_ASEGURADO.cg$table(SIM_PCK_FER_ASEGURADO.idx).TIPO_IDENTIFICACION := cg$rec.TIPO_IDENTIFICACION;
    SIM_PCK_FER_ASEGURADO.cg$tableind(SIM_PCK_FER_ASEGURADO.idx).TIPO_IDENTIFICACION := cg$ind.TIPO_IDENTIFICACION;

    SIM_PCK_FER_ASEGURADO.cg$table(SIM_PCK_FER_ASEGURADO.idx).NUMERO_CERTIFICADO := cg$rec.NUMERO_CERTIFICADO;
    SIM_PCK_FER_ASEGURADO.cg$tableind(SIM_PCK_FER_ASEGURADO.idx).NUMERO_CERTIFICADO := cg$ind.NUMERO_CERTIFICADO;

    SIM_PCK_FER_ASEGURADO.cg$table(SIM_PCK_FER_ASEGURADO.idx).CONSECUTIVO := cg$rec.CONSECUTIVO;
    SIM_PCK_FER_ASEGURADO.cg$tableind(SIM_PCK_FER_ASEGURADO.idx).CONSECUTIVO := cg$ind.CONSECUTIVO;

    SIM_PCK_FER_ASEGURADO.cg$table(SIM_PCK_FER_ASEGURADO.idx).NUMERO_GR := cg$rec.NUMERO_GR;
    SIM_PCK_FER_ASEGURADO.cg$tableind(SIM_PCK_FER_ASEGURADO.idx).NUMERO_GR := cg$ind.NUMERO_GR;

    SIM_PCK_FER_ASEGURADO.cg$table(SIM_PCK_FER_ASEGURADO.idx).FECHA_INICIO_VIGENCIA := cg$rec.FECHA_INICIO_VIGENCIA;
    SIM_PCK_FER_ASEGURADO.cg$tableind(SIM_PCK_FER_ASEGURADO.idx).FECHA_INICIO_VIGENCIA := cg$ind.FECHA_INICIO_VIGENCIA;

    SIM_PCK_FER_ASEGURADO.cg$table(SIM_PCK_FER_ASEGURADO.idx).VALOR_ASEGURADO := cg$rec.VALOR_ASEGURADO;
    SIM_PCK_FER_ASEGURADO.cg$tableind(SIM_PCK_FER_ASEGURADO.idx).VALOR_ASEGURADO := cg$ind.VALOR_ASEGURADO;

    SIM_PCK_FER_ASEGURADO.cg$table(SIM_PCK_FER_ASEGURADO.idx).OPCION_COBERTURA := cg$rec.OPCION_COBERTURA;
    SIM_PCK_FER_ASEGURADO.cg$tableind(SIM_PCK_FER_ASEGURADO.idx).OPCION_COBERTURA := cg$ind.OPCION_COBERTURA;

    SIM_PCK_FER_ASEGURADO.cg$table(SIM_PCK_FER_ASEGURADO.idx).PRIMA := cg$rec.PRIMA;
    SIM_PCK_FER_ASEGURADO.cg$tableind(SIM_PCK_FER_ASEGURADO.idx).PRIMA := cg$ind.PRIMA;

    SIM_PCK_FER_ASEGURADO.cg$table(SIM_PCK_FER_ASEGURADO.idx).EXTRAPRIMA := cg$rec.EXTRAPRIMA;
    SIM_PCK_FER_ASEGURADO.cg$tableind(SIM_PCK_FER_ASEGURADO.idx).EXTRAPRIMA := cg$ind.EXTRAPRIMA;

    SIM_PCK_FER_ASEGURADO.cg$table(SIM_PCK_FER_ASEGURADO.idx).PORCENTAJE_EXTRAPRIMA := cg$rec.PORCENTAJE_EXTRAPRIMA;
    SIM_PCK_FER_ASEGURADO.cg$tableind(SIM_PCK_FER_ASEGURADO.idx).PORCENTAJE_EXTRAPRIMA := cg$ind.PORCENTAJE_EXTRAPRIMA;

    SIM_PCK_FER_ASEGURADO.cg$table(SIM_PCK_FER_ASEGURADO.idx).TIPO_AFILIACION := cg$rec.TIPO_AFILIACION;
    SIM_PCK_FER_ASEGURADO.cg$tableind(SIM_PCK_FER_ASEGURADO.idx).TIPO_AFILIACION := cg$ind.TIPO_AFILIACION;

    SIM_PCK_FER_ASEGURADO.cg$table(SIM_PCK_FER_ASEGURADO.idx).FECHA_CANCELACION := cg$rec.FECHA_CANCELACION;
    SIM_PCK_FER_ASEGURADO.cg$tableind(SIM_PCK_FER_ASEGURADO.idx).FECHA_CANCELACION := cg$ind.FECHA_CANCELACION;

    SIM_PCK_FER_ASEGURADO.cg$table(SIM_PCK_FER_ASEGURADO.idx).FECHA_CREACION := cg$rec.FECHA_CREACION;
    SIM_PCK_FER_ASEGURADO.cg$tableind(SIM_PCK_FER_ASEGURADO.idx).FECHA_CREACION := cg$ind.FECHA_CREACION;

    SIM_PCK_FER_ASEGURADO.cg$table(SIM_PCK_FER_ASEGURADO.idx).SUCURSAL := cg$rec.SUCURSAL;
    SIM_PCK_FER_ASEGURADO.cg$tableind(SIM_PCK_FER_ASEGURADO.idx).SUCURSAL := cg$ind.SUCURSAL;

    SIM_PCK_FER_ASEGURADO.idx := SIM_PCK_FER_ASEGURADO.idx + 1;

    :new.NUMERO_DOCUMENTO := cg$rec.NUMERO_DOCUMENTO;
    :new.TIPO_IDENTIFICACION := cg$rec.TIPO_IDENTIFICACION;
    :new.NUMERO_CERTIFICADO := cg$rec.NUMERO_CERTIFICADO;
    :new.CONSECUTIVO := cg$rec.CONSECUTIVO;
    :new.NUMERO_GR := cg$rec.NUMERO_GR;
    :new.FECHA_INICIO_VIGENCIA := cg$rec.FECHA_INICIO_VIGENCIA;
    :new.VALOR_ASEGURADO := cg$rec.VALOR_ASEGURADO;
    :new.OPCION_COBERTURA := cg$rec.OPCION_COBERTURA;
    :new.PRIMA := cg$rec.PRIMA;
    :new.EXTRAPRIMA := cg$rec.EXTRAPRIMA;
    :new.PORCENTAJE_EXTRAPRIMA := cg$rec.PORCENTAJE_EXTRAPRIMA;
    :new.TIPO_AFILIACION := cg$rec.TIPO_AFILIACION;
    :new.FECHA_CANCELACION := cg$rec.FECHA_CANCELACION;
    :new.FECHA_CREACION := cg$rec.FECHA_CREACION;
    :new.SUCURSAL := cg$rec.SUCURSAL;

--  Application_logic Post-Before-Insert-row <<Start>>
--  Application_logic Post-Before-Insert-row << End >>
END;
/
