CREATE OR REPLACE TRIGGER cg$BUR_SIM_FER_ASEGURADO
BEFORE UPDATE ON SIM_FER_ASEGURADO FOR EACH ROW
DECLARE
    cg$rec     SIM_PCK_FER_ASEGURADO.cg$row_type;
    cg$ind     SIM_PCK_FER_ASEGURADO.cg$ind_type;
    cg$old_rec SIM_PCK_FER_ASEGURADO.cg$row_type;
BEGIN
--  Application_logic Pre-Before-Update-row <<Start>>
--  Application_logic Pre-Before-Update-row << End >>

--  Load cg$rec/cg$ind values from new

    cg$rec.NUMERO_DOCUMENTO := :new.NUMERO_DOCUMENTO;
    cg$ind.NUMERO_DOCUMENTO :=    (:new.NUMERO_DOCUMENTO IS NULL AND :old.NUMERO_DOCUMENTO IS NOT NULL )
                        OR (:new.NUMERO_DOCUMENTO IS NOT NULL AND :old.NUMERO_DOCUMENTO IS NULL)
                        OR NOT(:new.NUMERO_DOCUMENTO = :old.NUMERO_DOCUMENTO) ;
    SIM_PCK_FER_ASEGURADO.cg$table(SIM_PCK_FER_ASEGURADO.idx).NUMERO_DOCUMENTO := :old.NUMERO_DOCUMENTO;
    cg$rec.TIPO_IDENTIFICACION := :new.TIPO_IDENTIFICACION;
    cg$ind.TIPO_IDENTIFICACION :=    (:new.TIPO_IDENTIFICACION IS NULL AND :old.TIPO_IDENTIFICACION IS NOT NULL )
                        OR (:new.TIPO_IDENTIFICACION IS NOT NULL AND :old.TIPO_IDENTIFICACION IS NULL)
                        OR NOT(:new.TIPO_IDENTIFICACION = :old.TIPO_IDENTIFICACION) ;
    SIM_PCK_FER_ASEGURADO.cg$table(SIM_PCK_FER_ASEGURADO.idx).TIPO_IDENTIFICACION := :old.TIPO_IDENTIFICACION;
    cg$rec.NUMERO_CERTIFICADO := :new.NUMERO_CERTIFICADO;
    cg$ind.NUMERO_CERTIFICADO :=    (:new.NUMERO_CERTIFICADO IS NULL AND :old.NUMERO_CERTIFICADO IS NOT NULL )
                        OR (:new.NUMERO_CERTIFICADO IS NOT NULL AND :old.NUMERO_CERTIFICADO IS NULL)
                        OR NOT(:new.NUMERO_CERTIFICADO = :old.NUMERO_CERTIFICADO) ;
    SIM_PCK_FER_ASEGURADO.cg$table(SIM_PCK_FER_ASEGURADO.idx).NUMERO_CERTIFICADO := :old.NUMERO_CERTIFICADO;
    cg$rec.CONSECUTIVO := :new.CONSECUTIVO;
    cg$ind.CONSECUTIVO :=    (:new.CONSECUTIVO IS NULL AND :old.CONSECUTIVO IS NOT NULL )
                        OR (:new.CONSECUTIVO IS NOT NULL AND :old.CONSECUTIVO IS NULL)
                        OR NOT(:new.CONSECUTIVO = :old.CONSECUTIVO) ;
    SIM_PCK_FER_ASEGURADO.cg$table(SIM_PCK_FER_ASEGURADO.idx).CONSECUTIVO := :old.CONSECUTIVO;
    cg$rec.NUMERO_GR := :new.NUMERO_GR;
    cg$ind.NUMERO_GR :=    (:new.NUMERO_GR IS NULL AND :old.NUMERO_GR IS NOT NULL )
                        OR (:new.NUMERO_GR IS NOT NULL AND :old.NUMERO_GR IS NULL)
                        OR NOT(:new.NUMERO_GR = :old.NUMERO_GR) ;
    SIM_PCK_FER_ASEGURADO.cg$table(SIM_PCK_FER_ASEGURADO.idx).NUMERO_GR := :old.NUMERO_GR;
    cg$rec.FECHA_INICIO_VIGENCIA := :new.FECHA_INICIO_VIGENCIA;
    cg$ind.FECHA_INICIO_VIGENCIA :=    (:new.FECHA_INICIO_VIGENCIA IS NULL AND :old.FECHA_INICIO_VIGENCIA IS NOT NULL )
                        OR (:new.FECHA_INICIO_VIGENCIA IS NOT NULL AND :old.FECHA_INICIO_VIGENCIA IS NULL)
                        OR NOT(:new.FECHA_INICIO_VIGENCIA = :old.FECHA_INICIO_VIGENCIA) ;
    SIM_PCK_FER_ASEGURADO.cg$table(SIM_PCK_FER_ASEGURADO.idx).FECHA_INICIO_VIGENCIA := :old.FECHA_INICIO_VIGENCIA;
    cg$rec.VALOR_ASEGURADO := :new.VALOR_ASEGURADO;
    cg$ind.VALOR_ASEGURADO :=    (:new.VALOR_ASEGURADO IS NULL AND :old.VALOR_ASEGURADO IS NOT NULL )
                        OR (:new.VALOR_ASEGURADO IS NOT NULL AND :old.VALOR_ASEGURADO IS NULL)
                        OR NOT(:new.VALOR_ASEGURADO = :old.VALOR_ASEGURADO) ;
    SIM_PCK_FER_ASEGURADO.cg$table(SIM_PCK_FER_ASEGURADO.idx).VALOR_ASEGURADO := :old.VALOR_ASEGURADO;
    cg$rec.OPCION_COBERTURA := :new.OPCION_COBERTURA;
    cg$ind.OPCION_COBERTURA :=    (:new.OPCION_COBERTURA IS NULL AND :old.OPCION_COBERTURA IS NOT NULL )
                        OR (:new.OPCION_COBERTURA IS NOT NULL AND :old.OPCION_COBERTURA IS NULL)
                        OR NOT(:new.OPCION_COBERTURA = :old.OPCION_COBERTURA) ;
    SIM_PCK_FER_ASEGURADO.cg$table(SIM_PCK_FER_ASEGURADO.idx).OPCION_COBERTURA := :old.OPCION_COBERTURA;
    cg$rec.PRIMA := :new.PRIMA;
    cg$ind.PRIMA :=    (:new.PRIMA IS NULL AND :old.PRIMA IS NOT NULL )
                        OR (:new.PRIMA IS NOT NULL AND :old.PRIMA IS NULL)
                        OR NOT(:new.PRIMA = :old.PRIMA) ;
    SIM_PCK_FER_ASEGURADO.cg$table(SIM_PCK_FER_ASEGURADO.idx).PRIMA := :old.PRIMA;
    cg$rec.EXTRAPRIMA := :new.EXTRAPRIMA;
    cg$ind.EXTRAPRIMA :=    (:new.EXTRAPRIMA IS NULL AND :old.EXTRAPRIMA IS NOT NULL )
                        OR (:new.EXTRAPRIMA IS NOT NULL AND :old.EXTRAPRIMA IS NULL)
                        OR NOT(:new.EXTRAPRIMA = :old.EXTRAPRIMA) ;
    SIM_PCK_FER_ASEGURADO.cg$table(SIM_PCK_FER_ASEGURADO.idx).EXTRAPRIMA := :old.EXTRAPRIMA;
    cg$rec.PORCENTAJE_EXTRAPRIMA := :new.PORCENTAJE_EXTRAPRIMA;
    cg$ind.PORCENTAJE_EXTRAPRIMA :=    (:new.PORCENTAJE_EXTRAPRIMA IS NULL AND :old.PORCENTAJE_EXTRAPRIMA IS NOT NULL )
                        OR (:new.PORCENTAJE_EXTRAPRIMA IS NOT NULL AND :old.PORCENTAJE_EXTRAPRIMA IS NULL)
                        OR NOT(:new.PORCENTAJE_EXTRAPRIMA = :old.PORCENTAJE_EXTRAPRIMA) ;
    SIM_PCK_FER_ASEGURADO.cg$table(SIM_PCK_FER_ASEGURADO.idx).PORCENTAJE_EXTRAPRIMA := :old.PORCENTAJE_EXTRAPRIMA;
    cg$rec.TIPO_AFILIACION := :new.TIPO_AFILIACION;
    cg$ind.TIPO_AFILIACION :=    (:new.TIPO_AFILIACION IS NULL AND :old.TIPO_AFILIACION IS NOT NULL )
                        OR (:new.TIPO_AFILIACION IS NOT NULL AND :old.TIPO_AFILIACION IS NULL)
                        OR NOT(:new.TIPO_AFILIACION = :old.TIPO_AFILIACION) ;
    SIM_PCK_FER_ASEGURADO.cg$table(SIM_PCK_FER_ASEGURADO.idx).TIPO_AFILIACION := :old.TIPO_AFILIACION;
    cg$rec.FECHA_CANCELACION := :new.FECHA_CANCELACION;
    cg$ind.FECHA_CANCELACION :=    (:new.FECHA_CANCELACION IS NULL AND :old.FECHA_CANCELACION IS NOT NULL )
                        OR (:new.FECHA_CANCELACION IS NOT NULL AND :old.FECHA_CANCELACION IS NULL)
                        OR NOT(:new.FECHA_CANCELACION = :old.FECHA_CANCELACION) ;
    SIM_PCK_FER_ASEGURADO.cg$table(SIM_PCK_FER_ASEGURADO.idx).FECHA_CANCELACION := :old.FECHA_CANCELACION;
    cg$rec.FECHA_CREACION := :new.FECHA_CREACION;
    cg$ind.FECHA_CREACION :=    (:new.FECHA_CREACION IS NULL AND :old.FECHA_CREACION IS NOT NULL )
                        OR (:new.FECHA_CREACION IS NOT NULL AND :old.FECHA_CREACION IS NULL)
                        OR NOT(:new.FECHA_CREACION = :old.FECHA_CREACION) ;
    SIM_PCK_FER_ASEGURADO.cg$table(SIM_PCK_FER_ASEGURADO.idx).FECHA_CREACION := :old.FECHA_CREACION;
    cg$rec.SUCURSAL := :new.SUCURSAL;
    cg$ind.SUCURSAL :=    (:new.SUCURSAL IS NULL AND :old.SUCURSAL IS NOT NULL )
                        OR (:new.SUCURSAL IS NOT NULL AND :old.SUCURSAL IS NULL)
                        OR NOT(:new.SUCURSAL = :old.SUCURSAL) ;
    SIM_PCK_FER_ASEGURADO.cg$table(SIM_PCK_FER_ASEGURADO.idx).SUCURSAL := :old.SUCURSAL;


    SIM_PCK_FER_ASEGURADO.idx := SIM_PCK_FER_ASEGURADO.idx + 1;

    if not (SIM_PCK_FER_ASEGURADO.called_from_package) then
        SIM_PCK_FER_ASEGURADO.validate_arc(cg$rec);
        SIM_PCK_FER_ASEGURADO.validate_domain(cg$rec, cg$ind);
        SIM_PCK_FER_ASEGURADO.validate_domain_cascade_update(cg$old_rec);

        SIM_PCK_FER_ASEGURADO.upd(cg$rec, cg$ind, FALSE);
        SIM_PCK_FER_ASEGURADO.called_from_package := FALSE;
    end if;

    :new.CONSECUTIVO := cg$rec.CONSECUTIVO;
    :new.NUMERO_GR := cg$rec.NUMERO_GR;
    :new.FECHA_INICIO_VIGENCIA := cg$rec.FECHA_INICIO_VIGENCIA;
    :new.VALOR_ASEGURADO := cg$rec.VALOR_ASEGURADO;
    :new.OPCION_COBERTURA := cg$rec.OPCION_COBERTURA;
    :new.PRIMA := cg$rec.PRIMA;
    :new.EXTRAPRIMA := cg$rec.EXTRAPRIMA;
    :new.PORCENTAJE_EXTRAPRIMA := cg$rec.PORCENTAJE_EXTRAPRIMA;
    :new.TIPO_AFILIACION := cg$rec.TIPO_AFILIACION;
    :new.FECHA_CANCELACION := cg$rec.FECHA_CANCELACION;
    :new.FECHA_CREACION := cg$rec.FECHA_CREACION;
    :new.SUCURSAL := cg$rec.SUCURSAL;
--  Application_logic Post-Before-Update-row <<Start>>
--  Application_logic Post-Before-Update-row << End >>
END;
/
