CREATE OR REPLACE TRIGGER PRODUCTOR
BEFORE INSERT ON C1010804
FOR EACH ROW
DECLARE
V_ACCES		      BOOLEAN;
V_VALOR		      BOOLEAN;
P_COD_PROD	    C1010804.COD_PROD%TYPE;
V_SUMA_ASEG	    NUMBER		:=	:NEW.SUMA_ASEG;
V_SUMA_ACCES	  NUMBER	  :=	:NEW.SUMA_ACCES;
V_COD_MARCA	    NUMBER		:=	:NEW.COD_MARCA;
V_COD_MOD       NUMBER		:=	:NEW.COD_MOD;
V_COD_CIA	      NUMBER		:=	:NEW.COD_CIA;

V_MAX_ASEG      NUMBER(19,2);

BEGIN
/*
  IF (:NEW.SUB_RAMO!=270)  THEN
      	BEGIN
      	SELECT 1
      	 INTO P_COD_PROD
      	 FROM dual
      	 WHERE exists(select 'x'
                        from a1001300
                        where COD_PROD = :NEW.COD_PROD);
      	EXCEPTION
      	WHEN NO_DATA_FOUND
      	THEN P_COD_PROD :=0;
      	END;


         IF P_COD_PROD = 0 THEN
      	RAISE_APPLICATION_ERROR(-20080, 'EL CODIGO DE AGENTE NO EXISTE ');
         END IF;
   END IF;
*/
  --YLCG  MODIFICADO EL DIA 20 DE DICIEMBRE DEL 2005 POR SOLICITUD DEL JEFE TECNICO

  /* IF :NEW.SUB_RAMO = 270 THEN
       IF  V_SUMA_ASEG > 150000000 THEN
           RAISE_APPLICATION_ERROR(-20081, 'NO PUEDE COTIZAR UN AUTOMOVIL POR ESTE VALOR , ES NECESARIO DILIGENCIAR UNA AUTORIZACION ');
       END IF;
   ELSE*/
       V_MAX_ASEG := RETORNA_VAL_ASEG_TIP_VEH(:new.Cod_Marca, :NEW.COD_TIPO, :new.sub_ramo);
       IF  V_SUMA_ASEG > V_MAX_ASEG THEN
           RAISE_APPLICATION_ERROR(-20081, 'NO PUEDE COTIZAR UN AUTOMOVIL POR ESTE VALOR , ES NECESARIO DILIGENCIAR UNA AUTORIZACION ');
       END IF;
--   END IF;

--   IF    V_SUMA_ASEG > 35000000 THEN
--	  RAISE_APPLICATION_ERROR(-20081, 'NO PUEDE COTIZAR UN AUTOMOVIL POR ESTE VALOR , ES NECESARIO DILIGENCIAR UNA AUTORIZACION ');
--   END IF;

/* DEJA EL NOMBRE DEL HABITUAL IGUAL AL TOMADOR*/

	IF :NEW.NOM_COND IS NULL THEN
		:NEW.NOM_COND := :NEW.NOM_ASEG;
	END IF;


/* FUNCION VALOR DEL AUTO (FUN_VALOR)*/

   V_VALOR  :=  VALOR(V_SUMA_ASEG,V_COD_MARCA,V_COD_MOD,V_COD_CIA);
   IF V_VALOR = FALSE THEN
	RAISE_APPLICATION_ERROR
	(-20060,'LA SUMA ASEGURADA DEL VEHICULO DEBE CORRESPONDER AL 20% POR DEBAJO O POR ENCIMA DEL VALOR DADO POR LA COMPA?IA');
   END IF;

/* FUNCION VALOR ACCESORIOS (FUN_VALOR_A)*/

   V_ACCES := ACCESORIOS(V_SUMA_ACCES,V_SUMA_ASEG);
   IF V_ACCES = FALSE THEN
	RAISE_APPLICATION_ERROR(-20050,'LA SUMA DE ACCESORIOS DEBE CORRESPONDER HASTA EL 15% DEL VALOR DEL AUTO');
   END IF;

   begin -- PARA GUARDAR EL NOMBRE DEL TOMADOR EN LA P2000020, (el programa CB201011)
    IF :NEW.NOMBRE IS NULL THEN
		   :NEW.NOMBRE := :NEW.NOM_ASEG;
	  END IF;
    EXCEPTION WHEN OTHERS THEN NULL;
   end;
END;
/
