CREATE OR REPLACE TRIGGER SIM_ESTADO_SOAT
/* Autor: Henry Laguna, Diana Reyes
  Fecha: Julio 28 de 2022
  Objetivo: Asegurar que todas las pòlizas emitidas de soat con num_pol1, queden en estado IMP  (impreso)
  */
  AFTER INSERT OR UPDATE ON SIM_DATOSSOAT
  FOR EACH ROW
DECLARE
  L_NUMPOL1      SIM_PCK_TIPOS_GENERALES.T_NUM_VALOR;
  L_USUARIO      VARCHAR2(10);
  L_FECHAVENCPOL DATE;
  L_PLACA        VARCHAR2(10);
BEGIN
  BEGIN
    SELECT A.NUM_POL1, A.FECHA_VENC_POL, B.PAT_VEH, A.COD_USR
      INTO L_NUMPOL1, L_FECHAVENCPOL, L_PLACA, L_USUARIO
      FROM A2000030 A, SIM_DATOSSOAT B
     WHERE A.NUM_SECU_POL = :NEW.NUM_SECU_POL
       AND A.NUM_END = 0
       AND NVL(A.NUM_POL1, 0) > 0
       AND B.NUM_SECU_POL = A.NUM_SECU_POL
       AND B.NUM_END = A.NUM_END
       AND B.ESTADO_IMPRESION = 'PND';
  EXCEPTION
    WHEN OTHERS THEN
      L_NUMPOL1 := 0;
  END;
  IF L_NUMPOL1 > 0 THEN
    BEGIN
      UPDATE SIM_DATOSSOAT
         SET NRO_SOAT          = L_NUMPOL1,
             ESTADO_IMPRESION  = 'IMP',
             MARCA_IMPRESO     = 'S',
             FECHA_IMPRESION   = SYSDATE,
             USUARIO_IMPRESION = L_USUARIO
       WHERE NUM_SECU_POL = :NEW.NUM_SECU_POL
         AND NUM_END = 0;
    END;
    BEGIN
      UPDATE A2000030
         SET MCA_IMP_POL = 'A', FEC_IMP_POL = SYSDATE
       WHERE NUM_SECU_POL = :NEW.NUM_SECU_POL
         AND NUM_END = 0;
    END;
    BEGIN
      UPDATE SIM_INFORMACION_RUNT
         SET SOAT_FECHA_VENCIMIENTO = L_FECHAVENCPOL,
             SOAT_NUMERO_POLIZA     = L_NUMPOL1 * 100,
             FECHA_MODIFICACION     = SYSDATE,
             SOAT_ENTIDAD_EXPIDE    = 'SEGUROS COMERCIALES BOLIVAR',
             SOAT_FECHA_EXPEDICION  = SYSDATE
       WHERE IG_PAT_VEH = L_PLACA;
    END;
  END IF;
END SIM_ESTADO_SOAT;
/
