CREATE OR REPLACE TRIGGER SIM_TRGSIM_MARCALINEAMODNOASEG
  before insert on SIM_MARCALINEAMODNOASEG
  for each row
declare
  v_secuencia number(17) := 0;
begin

    SELECT NVL(MAX(SECUENCIA), 0) + 1
    INTO v_secuencia
    FROM SIM_MARCALINEAMODNOASEG;
    :new.secuencia := v_secuencia;

    IF :NEW.FECHA_CREACION IS NULL THEN
      :NEW.FECHA_CREACION := SYSDATE;
    END IF;

end SIM_TRGSIM_MARCALINEAMODNOASEG;
/
