CREATE OR REPLACE TRIGGER SIM_TRG_SIM_OCUPACION_GEN
  before update on SIM_OCUPACION_GEN
  for each row
begin

    UPDATE SIM_OCUPACION
    SET DESCRIPCION = :new.DESCRIPCION
    WHERE COD_OCUPACION = :new.COD_OCUPACION;   

end SIM_TRG_SIM_OCUPACION_GEN;
/
