CREATE OR REPLACE TRIGGER SIM_TRG_AIUDR_DEDUCPROD
   /* <Creacion>
      <Autor>Carlos Eduardo Becerra/Autor>
      <Fecha>10/02/2021</Fecha>
      <Objetivo>Enviar la informacion a la tabla de auditoria</Objetivo>
     </Creacion>
    */
   AFTER INSERT OR UPDATE OR DELETE
   ON SIM_DEDUCIBLES_PRODUCTO
   FOR EACH ROW
DECLARE
   l_operacion   VARCHAR2 (3);
BEGIN
   IF INSERTING
   THEN
      INSERT INTO SIM_DEDUCIBLES_PRODUCTO_JN (
                   JN_SECUENCIA         ,   
                   JN_OPERACION         ,
                   JN_ORACLE_USER       ,
                   JN_DATETIME          ,
                   SECUENCIA            ,
                   COD_CIA              ,
                   COD_SECC             ,
                   COD_PRODUCTO         ,
                   COD_CAUSA            ,
                   COD_CONS             ,
                   COD_COB              ,
                   PORCENTAJE           ,
                   PESOS                ,
                   CANT_SMMLV           ,
                   PORC_CONT_ELECTR     ,
                   PORC_CONT_NOELEC     ,
                   PORC_LIMITE          ,
                   COD_COB_BASE         ,
                   MAXIMO_SMMLV         ,				   
                   FECHA_CREACION       ,
                   USUARIO_CREACION     ,
                   FECHA_ALTA           ,
                   USUARIO_MODIFICACION ,
                   FECHA_MODIFICACION   ,  
                   FECHA_BAJA           )
           VALUES (SEQ_DEDUC_PRDCTO_JN.NEXTVAL,
                   'INS',
                   :NEW.USUARIO_CREACION     ,
                   SYSDATE,
                   :NEW.SECUENCIA            ,
                   :NEW.COD_CIA              ,
                   :NEW.COD_SECC             ,
                   :NEW.COD_PRODUCTO         ,
                   :NEW.COD_CAUSA            ,
                   :NEW.COD_CONS             ,
                   :NEW.COD_COB              ,
                   :NEW.PORCENTAJE           ,
                   :NEW.PESOS                ,
                   :NEW.CANT_SMMLV           ,
                   :NEW.PORC_CONT_ELECTR     ,
                   :NEW.PORC_CONT_NOELEC     ,
                   :NEW.PORC_LIMITE          ,
                   :NEW.COD_COB_BASE         ,
                   :NEW.MAXIMO_SMMLV         ,				   				   
                   :NEW.FECHA_CREACION       ,
                   :NEW.USUARIO_CREACION     ,
                   :NEW.FECHA_ALTA           ,
                   :NEW.USUARIO_MODIFICACION ,
                   :NEW.FECHA_MODIFICACION   ,
                   :NEW.FECHA_BAJA         );
   ELSIF UPDATING
      THEN
         l_operacion := 'UPD';
      INSERT INTO SIM_DEDUCIBLES_PRODUCTO_JN (
                   JN_SECUENCIA         ,   
                   JN_OPERACION         ,
                   JN_ORACLE_USER       ,
                   JN_DATETIME          ,
                   SECUENCIA            ,
                   COD_CIA              ,
                   COD_SECC             ,
                   COD_PRODUCTO         ,
                   COD_CAUSA            ,
                   COD_CONS             ,
                   COD_COB              ,
                   PORCENTAJE           ,
                   PESOS                ,
                   CANT_SMMLV           ,
                   PORC_CONT_ELECTR     ,
                   PORC_CONT_NOELEC     ,
                   PORC_LIMITE          ,
                   COD_COB_BASE         ,
                   MAXIMO_SMMLV         ,
                   FECHA_CREACION       ,
                   USUARIO_CREACION     ,
                   FECHA_ALTA           ,
                   USUARIO_MODIFICACION ,
                   FECHA_MODIFICACION   ,  
                   FECHA_BAJA           )
           VALUES (SEQ_DEDUC_PRDCTO_JN.NEXTVAL,
                   l_operacion,
                   :NEW.USUARIO_CREACION     ,
                   SYSDATE,
                   :NEW.SECUENCIA            ,
                   :NEW.COD_CIA              ,
                   :NEW.COD_SECC             ,
                   :NEW.COD_PRODUCTO         ,
                   :NEW.COD_CAUSA            ,
                   :NEW.COD_CONS             ,
                   :NEW.COD_COB              ,
                   :NEW.PORCENTAJE           ,
                   :NEW.PESOS                ,
                   :NEW.CANT_SMMLV           ,
                   :NEW.PORC_CONT_ELECTR     ,
                   :NEW.PORC_CONT_NOELEC     ,
                   :NEW.PORC_LIMITE          ,
                   :NEW.COD_COB_BASE         ,
                   :NEW.MAXIMO_SMMLV         ,				   
                   :NEW.FECHA_CREACION       ,
                   :NEW.USUARIO_CREACION     ,
                   :NEW.FECHA_ALTA           ,
                   :NEW.USUARIO_MODIFICACION ,
                   :NEW.FECHA_MODIFICACION   ,
                   :NEW.FECHA_BAJA         ); 		 
   ELSIF DELETING
      THEN
         l_operacion := 'DEL';
      INSERT INTO SIM_DEDUCIBLES_PRODUCTO_JN (
                   JN_SECUENCIA         ,   
                   JN_OPERACION         ,
                   JN_ORACLE_USER       ,
                   JN_DATETIME          ,
                   SECUENCIA            ,
                   COD_CIA              ,
                   COD_SECC             ,
                   COD_PRODUCTO         ,
                   COD_CAUSA            ,
                   COD_CONS             ,
                   COD_COB              ,
                   PORCENTAJE           ,
                   PESOS                ,
                   CANT_SMMLV           ,
                   PORC_CONT_ELECTR     ,
                   PORC_CONT_NOELEC     ,
                   PORC_LIMITE          ,
                   COD_COB_BASE         ,
                   MAXIMO_SMMLV         ,				   
                   FECHA_CREACION       ,
                   USUARIO_CREACION     ,
                   FECHA_ALTA           ,
                   USUARIO_MODIFICACION ,
                   FECHA_MODIFICACION   ,  
                   FECHA_BAJA           )
           VALUES (SEQ_DEDUC_PRDCTO_JN.NEXTVAL,
                   l_operacion,
                   :OLD.USUARIO_CREACION     ,
                   SYSDATE,
                   :OLD.SECUENCIA            ,
                   :OLD.COD_CIA              ,
                   :OLD.COD_SECC             ,
                   :OLD.COD_PRODUCTO         ,
                   :OLD.COD_CAUSA            ,
                   :OLD.COD_CONS             ,
                   :OLD.COD_COB              ,
                   :OLD.PORCENTAJE           ,
                   :OLD.PESOS                ,
                   :OLD.CANT_SMMLV           ,
                   :OLD.PORC_CONT_ELECTR     ,
                   :OLD.PORC_CONT_NOELEC     ,
                   :OLD.PORC_LIMITE          ,
                   :OLD.COD_COB_BASE         ,
                   :OLD.MAXIMO_SMMLV         ,				   
                   :OLD.FECHA_CREACION       ,
                   :OLD.USUARIO_CREACION     ,
                   :OLD.FECHA_ALTA           ,
                   :OLD.USUARIO_MODIFICACION ,
                   :OLD.FECHA_MODIFICACION   ,
                   :OLD.FECHA_BAJA         );
   END IF;
END TR_AIUDR_DEDUCPROD;
/
