CREATE OR REPLACE TRIGGER SIM_TRG_BIU_SARLAFT_CONTROL
BEFORE INSERT OR UPDATE OF FORMULARIO_SARLAFT ON SIM_PRODUCTOS
FOR EACH ROW
DECLARE
    VAR_EXIST NUMBER := 0;
BEGIN
  SELECT c9.codigo
  INTO VAR_EXIST
  FROM c9999909 c9
  where c9.cod_tab = 'FOR_SARLAFT' and c9.codigo = :NEW.FORMULARIO_SARLAFT AND ROWNUM = 1;

--  IF(VAR_EXIST = 0) THEN
--    raise_application_error(-20502, 'NO EXISTE EL CODIGO SARLAFT INGRESADO EN LA TABLA DE DOMINIOS');
--  END IF;
  
EXCEPTION
  WHEN NO_DATA_FOUND THEN
    raise_application_error(-20502, 'NO EXISTE EL CODIGO SARLAFT INGRESADO EN LA TABLA DE DOMINIOS');
  WHEN TOO_MANY_ROWS THEN
    raise_application_error(-20502, 'SE ENCONTRARON MAS REGISTROS DE LOS ESPERADOS');
END;
/
