CREATE OR REPLACE TRIGGER SIM_TRG_SIM_ENFERMEDAD_GEN
  before update on SIM_ENFERMEDAD_GEN
  for each row
begin

    UPDATE SIM_ENFERMEDAD
    SET DESCRIPCION = :new.DESCRIPCION
    WHERE COD_ENFERMEDAD = :new.COD_ENFERMEDAD;   

end SIM_TRG_SIM_ENFERMEDAD_GEN;
/
