CREATE OR REPLACE TRIGGER SIM_TRG_SIM_PARENTESCO_GEN
  before update on SIM_PARENTESCO_GEN
  for each row
begin

    UPDATE SIM_PARENTESCO
    SET DESCRIPCION = :new.DESCRIPCION
    WHERE COD_PARENTESCO = :new.COD_PARENTESCO;   

end SIM_TRG_SIM_PARENTESCO_GEN;
/
