CREATE OR REPLACE TRIGGER TR_AIUDR_SIMAPIDVSINBIENEST_JN
  AFTER 
  INSERT OR 
  UPDATE OR 
  DELETE ON SIMAPI_DATVARSINI_BIEN_EST for each row
Declare 
  rec SIMAPI_DATVARSINI_BIEN_EST_JN%ROWTYPE; 
  blank SIMAPI_DATVARSINI_BIEN_EST_JN%ROWTYPE; 
  BEGIN 
    rec := blank; 
    IF INSERTING OR UPDATING THEN 
      rec.COD_CIA := :NEW.COD_CIA; 
      rec.COD_CAMPO := :NEW.COD_CAMPO; 
      rec.COD_RAMO := :NEW.COD_RAMO; 
      rec.ID_BIEN := :NEW.ID_BIEN; 
      rec.ID_PLANTILLA_ESTRATEGIA := :NEW.ID_PLANTILLA_ESTRATEGIA; 
      rec.ESTADO := :NEW.ESTADO; 
      rec.REQUERIDO := :NEW.REQUERIDO; 
      rec.VISIBLE := :NEW.VISIBLE; 
      rec.FECHA_CREACION := :NEW.FECHA_CREACION; 
      rec.USUARIO_CREACION := :NEW.USUARIO_CREACION; 
      rec.VR_DEFAULT := :NEW.VR_DEFAULT; 
      rec.FECHA_MODIFICACION := :NEW.FECHA_MODIFICACION; 
      rec.USUARIO_MODIFICACION := :NEW.USUARIO_MODIFICACION; 
      rec.JN_DATETIME := SYSDATE; 
      rec.JN_ORACLE_USER := SYS_CONTEXT ('USERENV', 'SESSION_USER'); 
      rec.JN_APPLN := SYS_CONTEXT ('USERENV', 'MODULE'); 
      rec.JN_SESSION := SYS_CONTEXT ('USERENV', 'SESSIONID'); 
      IF INSERTING THEN 
        rec.JN_OPERATION := 'INS'; 
      ELSIF UPDATING THEN 
        rec.JN_OPERATION := 'UPD'; 
      END IF; 
    ELSIF DELETING THEN 
      rec.COD_CIA := :OLD.COD_CIA; 
      rec.COD_CAMPO := :OLD.COD_CAMPO; 
      rec.COD_RAMO := :OLD.COD_RAMO; 
      rec.ID_BIEN := :OLD.ID_BIEN; 
      rec.ID_PLANTILLA_ESTRATEGIA := :OLD.ID_PLANTILLA_ESTRATEGIA; 
      rec.ESTADO := :OLD.ESTADO; 
      rec.REQUERIDO := :OLD.REQUERIDO; 
      rec.VISIBLE := :OLD.VISIBLE; 
      rec.FECHA_CREACION := :OLD.FECHA_CREACION; 
      rec.USUARIO_CREACION := :OLD.USUARIO_CREACION; 
      rec.VR_DEFAULT := :OLD.VR_DEFAULT; 
      rec.FECHA_MODIFICACION := :OLD.FECHA_MODIFICACION; 
      rec.USUARIO_MODIFICACION := :OLD.USUARIO_MODIFICACION; 
      rec.JN_DATETIME := SYSDATE; 
      rec.JN_ORACLE_USER := SYS_CONTEXT ('USERENV', 'SESSION_USER'); 
      rec.JN_APPLN := SYS_CONTEXT ('USERENV', 'MODULE'); 
      rec.JN_SESSION := SYS_CONTEXT ('USERENV', 'SESSIONID'); 
      rec.JN_OPERATION := 'DEL'; 
    END IF; 
    INSERT into SIMAPI_DATVARSINI_BIEN_EST_JN VALUES rec; 
  END;
/
