CREATE OR REPLACE TRIGGER TR_AIR_SIM_CAST_CART_CODCOMT
/*
    Modifico : Rolphy Quintero - Asesoftware - Germán Muñoz
    fecha :  Febrero 16 de 2016 - Mantis 38430 - Proyecto Castigo de Cartera
    Desc : Se adiciona la columna FECHA_LIMITE_CARGUE.
    
    Modifico : Rolphy Quintero - Asesoftware - Germán Muñoz
    fecha :  Agosto 25 de 2015 - Mantis 38430 - Proyecto Castigo de Cartera
    Desc : Creación del trigger. Auditar tabla SIM_CASTIGO_CARTERA_COMITE.
*/
  AFTER INSERT ON SIM_CASTIGO_CARTERA_COMITE FOR EACH ROW
Declare
  vl_Tipo_Operacion  SIM_HISTORIAL_CASTCART_COMITE.Tipo_Operacion%type;
Begin
  If Inserting Then
    vl_Tipo_Operacion := 'C'; -- Creación
    INSERT INTO SIM_HISTORIAL_CASTCART_COMITE (SECUENCIA, ROWID_CASTCART_COMITE, FECHA_CREACION_REGISTRO, TIPO_OPERACION,
    COD_COMITE, DESCRIPCION, ESTADO, FECHA_COMITE, FECHA_CREACION, USUARIO_CREACION, FECHA_MODIFICACION,
    USUARIO_MODIFICACION, FECHA_LIMITE_CARGUE)
    VALUES (SEQ_HISTORIAL_CASTCART_CODCOMT.NEXTVAL, :NEW.ROWID, SYSDATE, vl_Tipo_Operacion, :NEW.COD_COMITE,
    :NEW.DESCRIPCION, :NEW.ESTADO, :NEW.FECHA_COMITE, :NEW.FECHA_CREACION, :NEW.USUARIO_CREACION, :NEW.FECHA_MODIFICACION,
    :NEW.USUARIO_MODIFICACION, :NEW.FECHA_LIMITE_CARGUE);
  End If;
End TR_AIR_SIM_CAST_CART_CODCOMT;
/
