CREATE OR REPLACE TRIGGER TR_AIUDR_SIM_CARP_PROD_JN
  AFTER 
  INSERT OR 
  UPDATE OR 
  DELETE ON SIM_CARPETAS_PRODUCTOS for each row
Declare 
  rec OPS$PUMA.SIM_CARPETAS_PRODUCTOS_JN%ROWTYPE; 
  blank OPS$PUMA.SIM_CARPETAS_PRODUCTOS_JN%ROWTYPE; 
  BEGIN 
    rec := blank; 
    IF INSERTING OR UPDATING THEN 
      rec.SECUENCIA := :NEW.SECUENCIA; 
      rec.ID_PRODUCTO := :NEW.ID_PRODUCTO; 
      rec.ID_SUBPRODUCTO := :NEW.ID_SUBPRODUCTO; 
      rec.ID_CARPETA := :NEW.ID_CARPETA; 
      rec.ID_PROCESO := :NEW.ID_PROCESO; 
      rec.SIM_USUARIO_CREACION := :NEW.SIM_USUARIO_CREACION; 
      rec.SIM_USUARIO_MODIFICACION := :NEW.SIM_USUARIO_MODIFICACION; 
      rec.FECHA_CREACION := :NEW.FECHA_CREACION; 
      rec.FECHA_MODIFICACION := :NEW.FECHA_MODIFICACION; 
      rec.JN_DATETIME := SYSDATE; 
      rec.JN_ORACLE_USER := SYS_CONTEXT ('USERENV', 'SESSION_USER'); 
      rec.JN_APPLN := SYS_CONTEXT ('USERENV', 'MODULE'); 
      rec.JN_SESSION := SYS_CONTEXT ('USERENV', 'SESSIONID'); 
      IF INSERTING THEN 
        rec.JN_OPERATION := 'INS'; 
      ELSIF UPDATING THEN 
        rec.JN_OPERATION := 'UPD'; 
      END IF; 
    ELSIF DELETING THEN 
      rec.SECUENCIA := :OLD.SECUENCIA; 
      rec.ID_PRODUCTO := :OLD.ID_PRODUCTO; 
      rec.ID_SUBPRODUCTO := :OLD.ID_SUBPRODUCTO; 
      rec.ID_CARPETA := :OLD.ID_CARPETA; 
      rec.ID_PROCESO := :OLD.ID_PROCESO; 
      rec.SIM_USUARIO_CREACION := :OLD.SIM_USUARIO_CREACION; 
      rec.SIM_USUARIO_MODIFICACION := :OLD.SIM_USUARIO_MODIFICACION; 
      rec.FECHA_CREACION := :OLD.FECHA_CREACION; 
      rec.FECHA_MODIFICACION := :OLD.FECHA_MODIFICACION; 
      rec.JN_DATETIME := SYSDATE; 
      rec.JN_ORACLE_USER := SYS_CONTEXT ('USERENV', 'SESSION_USER'); 
      rec.JN_APPLN := SYS_CONTEXT ('USERENV', 'MODULE'); 
      rec.JN_SESSION := SYS_CONTEXT ('USERENV', 'SESSIONID'); 
      rec.JN_OPERATION := 'DEL'; 
    END IF; 
    INSERT into OPS$PUMA.SIM_CARPETAS_PRODUCTOS_JN VALUES rec; 
  END;
/
