CREATE OR REPLACE TRIGGER TR_AIUDR_SIM_CARPETAS_JN
  AFTER 
  INSERT OR 
  UPDATE OR 
  DELETE ON SIM_CARPETAS for each row
Declare 
  rec OPS$PUMA.SIM_CARPETAS_JN%ROWTYPE; 
  blank OPS$PUMA.SIM_CARPETAS_JN%ROWTYPE; 
  BEGIN 
    rec := blank; 
    IF INSERTING OR UPDATING THEN 
      rec.ID_CARPETA := :NEW.ID_CARPETA; 
      rec.COD_CARPETA := :NEW.COD_CARPETA; 
      rec.NOMBRE_CARPETA := :NEW.NOMBRE_CARPETA; 
      rec.ORIGEN_CARPETA := :NEW.ORIGEN_CARPETA; 
      rec.ESTADO := :NEW.ESTADO; 
      rec.USR_CREACION := :NEW.USR_CREACION; 
      rec.FEC_CREACION := :NEW.FEC_CREACION; 
      rec.ID_CARPETA_PADRE := :NEW.ID_CARPETA_PADRE; 
      rec.OBSERVACIONES := :NEW.OBSERVACIONES; 
      rec.USR_MODIFICACION := :NEW.USR_MODIFICACION; 
      rec.FEC_MODIFICACION := :NEW.FEC_MODIFICACION; 
      rec.CLASE_DOCUMENTAL := :NEW.CLASE_DOCUMENTAL; 
      rec.CLASE_FILENET := :NEW.CLASE_FILENET; 
      rec.LISTA_FILENET := :NEW.LISTA_FILENET; 
      rec.JN_DATETIME := SYSDATE; 
      rec.JN_ORACLE_USER := SYS_CONTEXT ('USERENV', 'SESSION_USER'); 
      rec.JN_APPLN := SYS_CONTEXT ('USERENV', 'MODULE'); 
      rec.JN_SESSION := SYS_CONTEXT ('USERENV', 'SESSIONID'); 
      IF INSERTING THEN 
        rec.JN_OPERATION := 'INS'; 
      ELSIF UPDATING THEN 
        rec.JN_OPERATION := 'UPD'; 
      END IF; 
    ELSIF DELETING THEN 
      rec.ID_CARPETA := :OLD.ID_CARPETA; 
      rec.COD_CARPETA := :OLD.COD_CARPETA; 
      rec.NOMBRE_CARPETA := :OLD.NOMBRE_CARPETA; 
      rec.ORIGEN_CARPETA := :OLD.ORIGEN_CARPETA; 
      rec.ESTADO := :OLD.ESTADO; 
      rec.USR_CREACION := :OLD.USR_CREACION; 
      rec.FEC_CREACION := :OLD.FEC_CREACION; 
      rec.ID_CARPETA_PADRE := :OLD.ID_CARPETA_PADRE; 
      rec.OBSERVACIONES := :OLD.OBSERVACIONES; 
      rec.USR_MODIFICACION := :OLD.USR_MODIFICACION; 
      rec.FEC_MODIFICACION := :OLD.FEC_MODIFICACION; 
      rec.CLASE_DOCUMENTAL := :OLD.CLASE_DOCUMENTAL; 
      rec.CLASE_FILENET := :OLD.CLASE_FILENET; 
      rec.LISTA_FILENET := :OLD.LISTA_FILENET; 
      rec.JN_DATETIME := SYSDATE; 
      rec.JN_ORACLE_USER := SYS_CONTEXT ('USERENV', 'SESSION_USER'); 
      rec.JN_APPLN := SYS_CONTEXT ('USERENV', 'MODULE'); 
      rec.JN_SESSION := SYS_CONTEXT ('USERENV', 'SESSIONID'); 
      rec.JN_OPERATION := 'DEL'; 
    END IF; 
    INSERT into OPS$PUMA.SIM_CARPETAS_JN VALUES rec; 
  END;
/
