CREATE OR REPLACE TRIGGER TR_AIUDR_SIMAPI_SERVICIOS_JN
  AFTER 
  INSERT OR 
  UPDATE OR 
  DELETE ON SIMAPI_SERVICIOS for each row
Declare 
  rec SIMAPI_SERVICIOS_JN%ROWTYPE; 
  blank SIMAPI_SERVICIOS_JN%ROWTYPE; 
  BEGIN 
    rec := blank; 
    IF INSERTING OR UPDATING THEN 
      rec.ID_SERVICIO := :NEW.ID_SERVICIO; 
      rec.DESCRIPCION := :NEW.DESCRIPCION; 
      rec.ESTADO := :NEW.ESTADO; 
      rec.FECHA_CREACION := :NEW.FECHA_CREACION; 
      rec.USUARIO_CREACION := :NEW.USUARIO_CREACION; 
      rec.DESCRIPCION_LARGA := :NEW.DESCRIPCION_LARGA; 
      rec.COD_HOMOLOGADO := :NEW.COD_HOMOLOGADO; 
      rec.TDOC_PROVEEDOR := :NEW.TDOC_PROVEEDOR; 
      rec.COD_PROVEEDOR := :NEW.COD_PROVEEDOR; 
      rec.FECHA_MODIFICACION := :NEW.FECHA_MODIFICACION; 
      rec.USUARIO_MODIFICACION := :NEW.USUARIO_MODIFICACION; 
      rec.JN_DATETIME := SYSDATE; 
      rec.JN_ORACLE_USER := SYS_CONTEXT ('USERENV', 'SESSION_USER'); 
      rec.JN_APPLN := SYS_CONTEXT ('USERENV', 'MODULE'); 
      rec.JN_SESSION := SYS_CONTEXT ('USERENV', 'SESSIONID'); 
      IF INSERTING THEN 
        rec.JN_OPERATION := 'INS'; 
      ELSIF UPDATING THEN 
        rec.JN_OPERATION := 'UPD'; 
      END IF; 
    ELSIF DELETING THEN 
      rec.ID_SERVICIO := :OLD.ID_SERVICIO; 
      rec.DESCRIPCION := :OLD.DESCRIPCION; 
      rec.ESTADO := :OLD.ESTADO; 
      rec.FECHA_CREACION := :OLD.FECHA_CREACION; 
      rec.USUARIO_CREACION := :OLD.USUARIO_CREACION; 
      rec.DESCRIPCION_LARGA := :OLD.DESCRIPCION_LARGA; 
      rec.COD_HOMOLOGADO := :OLD.COD_HOMOLOGADO; 
      rec.TDOC_PROVEEDOR := :OLD.TDOC_PROVEEDOR; 
      rec.COD_PROVEEDOR := :OLD.COD_PROVEEDOR; 
      rec.FECHA_MODIFICACION := :OLD.FECHA_MODIFICACION; 
      rec.USUARIO_MODIFICACION := :OLD.USUARIO_MODIFICACION; 
      rec.JN_DATETIME := SYSDATE; 
      rec.JN_ORACLE_USER := SYS_CONTEXT ('USERENV', 'SESSION_USER'); 
      rec.JN_APPLN := SYS_CONTEXT ('USERENV', 'MODULE'); 
      rec.JN_SESSION := SYS_CONTEXT ('USERENV', 'SESSIONID'); 
      rec.JN_OPERATION := 'DEL'; 
    END IF; 
    INSERT into SIMAPI_SERVICIOS_JN VALUES rec; 
  END;
/
