CREATE OR REPLACE TRIGGER TR_AIUDR_CARGA_DET_LIQ
      AFTER INSERT OR UPDATE OR DELETE ON SIM_CARGA_DET_LIQUIDACIONES
FOR EACH ROW
 /*
   <Creacion>
   <Autor>Carlos Eduardo Mayorga</Autor>
   <Fecha>15/09/2016</Fecha>
   <Objetivo>Enviar la informacion a la tabla de auditoria</Objetivo>
  </Creacion>
 */
DECLARE
 l_operacion VARCHAR2(3);
BEGIN
  IF inserting THEN
    INSERT INTO SIM_CARGA_DET_LIQUIDACIONES_JN(JN_SECUENCIA, JN_OPERACION, JN_ORACLE_USER,
      JN_DATETIME, SECUENCIA_CAR_LIQ, CONSECUTIVO, 
      PROCESO, COD_CIA, COD_SECC,
      COD_RAMO, COD_COB, COD_CONCEP_RVA,
      COD_CONCEP_LIQ, IMPORTE_LIQ, MCA_PROCESO,
      FECHA_PROCESO, MCA_PROCESO_TER, FECHA_PROCESO_TER,
      USUARIO_CREACION, FECHA_CREACION, USUARIO_MODIFICACION)
    VALUES(SEQ_SIM_CAR_DET_LIQ_JN.NEXTVAL, 'INS', USER,
      SYSDATE, :NEW.SECUENCIA_CAR_LIQ, :NEW.CONSECUTIVO, 
      :NEW.PROCESO, :NEW.COD_CIA, :NEW.COD_SECC,
      :NEW.COD_RAMO, :NEW.COD_COB, :NEW.COD_CONCEP_RVA,
      :NEW.COD_CONCEP_LIQ, :NEW.IMPORTE_LIQ, :NEW.MCA_PROCESO,
      :NEW.FECHA_PROCESO, :NEW.MCA_PROCESO_TER, :NEW.FECHA_PROCESO_TER,
      :NEW.USUARIO_CREACION, :NEW.FECHA_CREACION, :NEW.USUARIO_MODIFICACION);
  ELSE
    IF updating THEN
	  l_operacion := 'UPD';
    ELSIF deleting THEN 
	  l_operacion := 'DEL';
	END IF;
    INSERT INTO SIM_CARGA_DET_LIQUIDACIONES_JN(JN_SECUENCIA, JN_OPERACION, JN_ORACLE_USER,
      JN_DATETIME, SECUENCIA_CAR_LIQ, CONSECUTIVO, 
      PROCESO, COD_CIA, COD_SECC,
      COD_RAMO, COD_COB, COD_CONCEP_RVA,
      COD_CONCEP_LIQ, IMPORTE_LIQ, MCA_PROCESO,
      FECHA_PROCESO, MCA_PROCESO_TER, FECHA_PROCESO_TER,
      USUARIO_CREACION, FECHA_CREACION, USUARIO_MODIFICACION)
    VALUES(SEQ_SIM_CAR_DET_LIQ_JN.NEXTVAL, l_operacion, USER,
      SYSDATE, :OLD.SECUENCIA_CAR_LIQ, :OLD.CONSECUTIVO, 
      :OLD.PROCESO, :OLD.COD_CIA, :OLD.COD_SECC,
      :OLD.COD_RAMO, :OLD.COD_COB, :OLD.COD_CONCEP_RVA,
      :OLD.COD_CONCEP_LIQ, :OLD.IMPORTE_LIQ, :OLD.MCA_PROCESO,
      :OLD.FECHA_PROCESO, :OLD.MCA_PROCESO_TER, :OLD.FECHA_PROCESO_TER,
      :OLD.USUARIO_CREACION, :OLD.FECHA_CREACION, :OLD.USUARIO_MODIFICACION);
  END IF;
END TR_AIUDR_CARGA_DET_LIQ;
/
