CREATE OR REPLACE TRIGGER TR_AIUDR_SIMAPI_DCTOS_COMER_JN
  AFTER 
  INSERT OR 
  UPDATE OR 
  DELETE ON SIMAPI_DCTOS_COMERCIALES for each row
Declare 
  rec SIMAPI_DCTOS_COMERCIALES_JN%ROWTYPE; 
  blank SIMAPI_DCTOS_COMERCIALES_JN%ROWTYPE; 
  BEGIN 
    rec := blank; 
    IF INSERTING OR UPDATING THEN 
      rec.ID_DCTO_COMERCIAL := :NEW.ID_DCTO_COMERCIAL; 
      rec.DESCRIPCION := :NEW.DESCRIPCION; 
      rec.PORCENTAJE := :NEW.PORCENTAJE; 
      rec.MODIFICABLE := :NEW.MODIFICABLE; 
      rec.ESTADO := :NEW.ESTADO; 
      rec.USUARIO_CREACION := :NEW.USUARIO_CREACION; 
      rec.FECHA_CREACION := :NEW.FECHA_CREACION; 
      rec.USUARIO_MODIFICACION := :NEW.USUARIO_MODIFICACION; 
      rec.FECHA_MODIFICACION := :NEW.FECHA_MODIFICACION; 
      rec.JN_DATETIME := SYSDATE; 
      rec.JN_ORACLE_USER := SYS_CONTEXT ('USERENV', 'SESSION_USER'); 
      rec.JN_APPLN := SYS_CONTEXT ('USERENV', 'MODULE'); 
      rec.JN_SESSION := SYS_CONTEXT ('USERENV', 'SESSIONID'); 
      IF INSERTING THEN 
        rec.JN_OPERATION := 'INS'; 
      ELSIF UPDATING THEN 
        rec.JN_OPERATION := 'UPD'; 
      END IF; 
    ELSIF DELETING THEN 
      rec.ID_DCTO_COMERCIAL := :OLD.ID_DCTO_COMERCIAL; 
      rec.DESCRIPCION := :OLD.DESCRIPCION; 
      rec.PORCENTAJE := :OLD.PORCENTAJE; 
      rec.MODIFICABLE := :OLD.MODIFICABLE; 
      rec.ESTADO := :OLD.ESTADO; 
      rec.USUARIO_CREACION := :OLD.USUARIO_CREACION; 
      rec.FECHA_CREACION := :OLD.FECHA_CREACION; 
      rec.USUARIO_MODIFICACION := :OLD.USUARIO_MODIFICACION; 
      rec.FECHA_MODIFICACION := :OLD.FECHA_MODIFICACION; 
      rec.JN_DATETIME := SYSDATE; 
      rec.JN_ORACLE_USER := SYS_CONTEXT ('USERENV', 'SESSION_USER'); 
      rec.JN_APPLN := SYS_CONTEXT ('USERENV', 'MODULE'); 
      rec.JN_SESSION := SYS_CONTEXT ('USERENV', 'SESSIONID'); 
      rec.JN_OPERATION := 'DEL'; 
    END IF; 
    INSERT into SIMAPI_DCTOS_COMERCIALES_JN VALUES rec; 
  END;
/
