CREATE OR REPLACE TRIGGER TR_AIUDR_SIMAPI_COBOPCBIEST_JN
  AFTER 
  INSERT OR 
  UPDATE OR 
  DELETE ON SIMAPI_COB_OPC_BIEN_EST for each row
Declare 
  rec SIMAPI_COB_OPC_BIEN_EST_JN%ROWTYPE; 
  blank SIMAPI_COB_OPC_BIEN_EST_JN%ROWTYPE; 
  BEGIN 
    rec := blank; 
    IF INSERTING OR UPDATING THEN 
      rec.COD_CIA := :NEW.COD_CIA; 
      rec.ID_PLANTILLA_ESTRATEGIA := :NEW.ID_PLANTILLA_ESTRATEGIA; 
      rec.ID_BIEN := :NEW.ID_BIEN; 
      rec.COD_OPCION := :NEW.COD_OPCION; 
      rec.COD_COB := :NEW.COD_COB; 
      rec.DESC_OPCION := :NEW.DESC_OPCION; 
      rec.COB_OBLIGATORIA := :NEW.COB_OBLIGATORIA; 
      rec.NUM_SECU := :NEW.NUM_SECU; 
      rec.MCA_GRATUITA := :NEW.MCA_GRATUITA; 
      rec.ESTADO := :NEW.ESTADO; 
      rec.MCA_BENEF := :NEW.MCA_BENEF; 
      rec.USUARIO_CREACION := :NEW.USUARIO_CREACION; 
      rec.FECHA_CREACION := :NEW.FECHA_CREACION; 
      rec.VR_SUMA_ASEG := :NEW.VR_SUMA_ASEG;
      rec.COD_MON_SUMA_ASEG := :NEW.COD_MON_SUMA_ASEG; 
      rec.VR_PRIMA := :NEW.VR_PRIMA; 
      rec.COD_MON_PRIMA := :NEW.COD_MON_PRIMA; 
      rec.TASA := :NEW.TASA;
      rec.ID_DEDUCIBLE := :NEW.ID_DEDUCIBLE; 
      rec.COD_COB_DEPENDE := :NEW.COD_COB_DEPENDE; 
      rec.PORC_SUMA_ASEG := :NEW.PORC_SUMA_ASEG; 
      rec.URL_CONTENIDO := :NEW.URL_CONTENIDO; 
      rec.SUMA_ASEG_DESDE := :NEW.SUMA_ASEG_DESDE; 
      rec.SUMA_ASEG_HASTA := :NEW.SUMA_ASEG_HASTA; 
      rec.CLAUSULADO := :NEW.CLAUSULADO; 
      rec.USUARIO_MODIFICACION := :NEW.USUARIO_MODIFICACION; 
      rec.FECHA_MODIFICACION := :NEW.FECHA_MODIFICACION; 
      rec.JN_DATETIME := SYSDATE; 
      rec.JN_ORACLE_USER := SYS_CONTEXT ('USERENV', 'SESSION_USER'); 
      rec.JN_APPLN := SYS_CONTEXT ('USERENV', 'MODULE'); 
      rec.JN_SESSION := SYS_CONTEXT ('USERENV', 'SESSIONID'); 
      IF INSERTING THEN 
        rec.JN_OPERATION := 'INS'; 
      ELSIF UPDATING THEN 
        rec.JN_OPERATION := 'UPD'; 
      END IF; 
    ELSIF DELETING THEN 
      rec.COD_CIA := :OLD.COD_CIA; 
      rec.ID_PLANTILLA_ESTRATEGIA := :OLD.ID_PLANTILLA_ESTRATEGIA; 
      rec.ID_BIEN := :OLD.ID_BIEN; 
      rec.COD_OPCION := :OLD.COD_OPCION; 
      rec.COD_COB := :OLD.COD_COB; 
      rec.DESC_OPCION := :OLD.DESC_OPCION; 
      rec.COB_OBLIGATORIA := :OLD.COB_OBLIGATORIA; 
      rec.NUM_SECU := :OLD.NUM_SECU;
      rec.MCA_GRATUITA := :OLD.MCA_GRATUITA; 
      rec.ESTADO := :OLD.ESTADO; 
      rec.MCA_BENEF := :OLD.MCA_BENEF; 
      rec.USUARIO_CREACION := :OLD.USUARIO_CREACION; 
      rec.FECHA_CREACION := :OLD.FECHA_CREACION;
      rec.VR_SUMA_ASEG := :OLD.VR_SUMA_ASEG; 
      rec.COD_MON_SUMA_ASEG := :OLD.COD_MON_SUMA_ASEG; 
      rec.VR_PRIMA := :OLD.VR_PRIMA; 
      rec.COD_MON_PRIMA := :OLD.COD_MON_PRIMA; 
      rec.TASA := :OLD.TASA;
      rec.ID_DEDUCIBLE := :OLD.ID_DEDUCIBLE; 
      rec.COD_COB_DEPENDE := :OLD.COD_COB_DEPENDE; 
      rec.PORC_SUMA_ASEG := :OLD.PORC_SUMA_ASEG; 
      rec.URL_CONTENIDO := :OLD.URL_CONTENIDO; 
      rec.SUMA_ASEG_DESDE := :OLD.SUMA_ASEG_DESDE; 
      rec.SUMA_ASEG_HASTA := :OLD.SUMA_ASEG_HASTA; 
      rec.CLAUSULADO := :OLD.CLAUSULADO; 
      rec.USUARIO_MODIFICACION := :OLD.USUARIO_MODIFICACION; 
      rec.FECHA_MODIFICACION := :OLD.FECHA_MODIFICACION; 
      rec.JN_DATETIME := SYSDATE; 
      rec.JN_ORACLE_USER := SYS_CONTEXT ('USERENV', 'SESSION_USER'); 
      rec.JN_APPLN := SYS_CONTEXT ('USERENV', 'MODULE'); 
      rec.JN_SESSION := SYS_CONTEXT ('USERENV', 'SESSIONID'); 
      rec.JN_OPERATION := 'DEL'; 
    END IF; 
    INSERT into SIMAPI_COB_OPC_BIEN_EST_JN VALUES rec; 
  END;
/
