CREATE OR REPLACE TRIGGER TR_AIUDR_SIM_CAUSAS_PROD_JN
  AFTER 
  INSERT OR 
  UPDATE OR 
  DELETE ON SIM_CAUSAS_PROD for each row
Declare 
  rec OPS$PUMA.SIM_CAUSAS_PROD_JN%ROWTYPE; 
  blank OPS$PUMA.SIM_CAUSAS_PROD_JN%ROWTYPE; 
  BEGIN 
    rec := blank; 
    IF INSERTING OR UPDATING THEN 
      rec.ID_CAUSAPROD := :NEW.ID_CAUSAPROD; 
      rec.ID_PRODUCTO := :NEW.ID_PRODUCTO; 
      rec.ID_SUBPRODUCTO := :NEW.ID_SUBPRODUCTO; 
      rec.COD_CIA := :NEW.COD_CIA; 
      rec.COD_SECC := :NEW.COD_SECC; 
      rec.COD_PRODUCTO := :NEW.COD_PRODUCTO; 
      rec.COD_SUBPRODUCTO := :NEW.COD_SUBPRODUCTO; 
      rec.TIPO_CAUSA := :NEW.TIPO_CAUSA; 
      rec.COD_CAUSA := :NEW.COD_CAUSA; 
      rec.FECHA_CREACION := :NEW.FECHA_CREACION; 
      rec.USUARIO_CREACION := :NEW.USUARIO_CREACION; 
      rec.FECHA_MODIFICA := :NEW.FECHA_MODIFICA; 
      rec.USUARIO_MODIFICA := :NEW.USUARIO_MODIFICA; 
      rec.ESTADO := :NEW.ESTADO; 
      rec.JN_DATETIME := SYSDATE; 
      rec.JN_ORACLE_USER := SYS_CONTEXT ('USERENV', 'SESSION_USER'); 
      rec.JN_APPLN := SYS_CONTEXT ('USERENV', 'MODULE'); 
      rec.JN_SESSION := SYS_CONTEXT ('USERENV', 'SESSIONID'); 
      IF INSERTING THEN 
        rec.JN_OPERATION := 'INS'; 
      ELSIF UPDATING THEN 
        rec.JN_OPERATION := 'UPD'; 
      END IF; 
    ELSIF DELETING THEN 
      rec.ID_CAUSAPROD := :OLD.ID_CAUSAPROD; 
      rec.ID_PRODUCTO := :OLD.ID_PRODUCTO; 
      rec.ID_SUBPRODUCTO := :OLD.ID_SUBPRODUCTO; 
      rec.COD_CIA := :OLD.COD_CIA; 
      rec.COD_SECC := :OLD.COD_SECC; 
      rec.COD_PRODUCTO := :OLD.COD_PRODUCTO; 
      rec.COD_SUBPRODUCTO := :OLD.COD_SUBPRODUCTO; 
      rec.TIPO_CAUSA := :OLD.TIPO_CAUSA; 
      rec.COD_CAUSA := :OLD.COD_CAUSA; 
      rec.FECHA_CREACION := :OLD.FECHA_CREACION; 
      rec.USUARIO_CREACION := :OLD.USUARIO_CREACION; 
      rec.FECHA_MODIFICA := :OLD.FECHA_MODIFICA; 
      rec.USUARIO_MODIFICA := :OLD.USUARIO_MODIFICA; 
      rec.ESTADO := :OLD.ESTADO; 
      rec.JN_DATETIME := SYSDATE; 
      rec.JN_ORACLE_USER := SYS_CONTEXT ('USERENV', 'SESSION_USER'); 
      rec.JN_APPLN := SYS_CONTEXT ('USERENV', 'MODULE'); 
      rec.JN_SESSION := SYS_CONTEXT ('USERENV', 'SESSIONID'); 
      rec.JN_OPERATION := 'DEL'; 
    END IF; 
    INSERT into OPS$PUMA.SIM_CAUSAS_PROD_JN VALUES rec; 
  END;
/
