CREATE OR REPLACE TRIGGER TR_AIUDR_SIMAPI_CARPBIENEST_JN
  AFTER 
  INSERT OR 
  UPDATE OR 
  DELETE ON SIMAPI_CARPETAS_BIEN_EST for each row
Declare 
  rec SIMAPI_CARPETAS_BIEN_EST_JN%ROWTYPE; 
  blank SIMAPI_CARPETAS_BIEN_EST_JN%ROWTYPE; 
  BEGIN 
    rec := blank; 
    IF INSERTING OR UPDATING THEN 
      rec.ID_SEC_CARP_PROD := :NEW.ID_SEC_CARP_PROD; 
      rec.ID_BIEN := :NEW.ID_BIEN; 
      rec.ID_PLANTILLA_ESTRATEGIA := :NEW.ID_PLANTILLA_ESTRATEGIA; 
      rec.ESTADO := :NEW.ESTADO; 
      rec.USUARIO_CREACION := :NEW.USUARIO_CREACION; 
      rec.FECHA_CREACION := :NEW.FECHA_CREACION; 
      rec.USUARIO_MODIFICACION := :NEW.USUARIO_MODIFICACION; 
      rec.FECHA_MODIFICACION := :NEW.FECHA_MODIFICACION; 
      rec.JN_DATETIME := SYSDATE; 
      rec.JN_ORACLE_USER := SYS_CONTEXT ('USERENV', 'SESSION_USER'); 
      rec.JN_APPLN := SYS_CONTEXT ('USERENV', 'MODULE'); 
      rec.JN_SESSION := SYS_CONTEXT ('USERENV', 'SESSIONID'); 
      IF INSERTING THEN 
        rec.JN_OPERATION := 'INS'; 
      ELSIF UPDATING THEN 
        rec.JN_OPERATION := 'UPD'; 
      END IF; 
    ELSIF DELETING THEN 
      rec.ID_SEC_CARP_PROD := :OLD.ID_SEC_CARP_PROD; 
      rec.ID_BIEN := :OLD.ID_BIEN; 
      rec.ID_PLANTILLA_ESTRATEGIA := :OLD.ID_PLANTILLA_ESTRATEGIA; 
      rec.ESTADO := :OLD.ESTADO; 
      rec.USUARIO_CREACION := :OLD.USUARIO_CREACION; 
      rec.FECHA_CREACION := :OLD.FECHA_CREACION; 
      rec.USUARIO_MODIFICACION := :OLD.USUARIO_MODIFICACION; 
      rec.FECHA_MODIFICACION := :OLD.FECHA_MODIFICACION; 
      rec.JN_DATETIME := SYSDATE; 
      rec.JN_ORACLE_USER := SYS_CONTEXT ('USERENV', 'SESSION_USER'); 
      rec.JN_APPLN := SYS_CONTEXT ('USERENV', 'MODULE'); 
      rec.JN_SESSION := SYS_CONTEXT ('USERENV', 'SESSIONID'); 
      rec.JN_OPERATION := 'DEL'; 
    END IF; 
    INSERT into SIMAPI_CARPETAS_BIEN_EST_JN VALUES rec; 
  END;
/
