CREATE OR REPLACE TRIGGER TR_AIR_SIM_CAST_CART_CODCAST
/*
    Modifico : Rolphy Quintero - Asesoftware - Germán Muñoz
    fecha :  Agosto 24 de 2015 - Mantis 38430 - Proyecto Castigo de Cartera
    Desc : Creación del trigger. Auditar tabla SIM_CAST_CARTERA_COD_CASTIGO.
*/
  AFTER INSERT ON SIM_CAST_CARTERA_COD_CASTIGO FOR EACH ROW
Declare
  vl_Tipo_Operacion  SIM_HISTORIAL_CASTCART_CODCAST.Tipo_Operacion%type;
Begin
  If Inserting Then
    vl_Tipo_Operacion := 'C'; -- Creación
    INSERT INTO SIM_HISTORIAL_CASTCART_CODCAST (SECUENCIA, ROWID_CASTCART_COD_CASTIGO, FECHA_CREACION_REGISTRO, TIPO_OPERACION,
    COD_CASTIGO, DESCRIPCION, ESTADO, FECHA_CREACION, USUARIO_CREACION, FECHA_MODIFICACION, USUARIO_MODIFICACION)
    VALUES (SEQ_HISTORIAL_CASTCART_CODCAST.NEXTVAL, :NEW.ROWID, SYSDATE, vl_Tipo_Operacion,
    :NEW.COD_CASTIGO, :NEW.DESCRIPCION, :NEW.ESTADO, :NEW.FECHA_CREACION, :NEW.USUARIO_CREACION, :NEW.FECHA_MODIFICACION, :NEW.USUARIO_MODIFICACION);
  End If;
End TR_AIR_SIM_CAST_CART_CODCAST;
/
