CREATE OR REPLACE TRIGGER TR_AIR_SIM_CASTIGO_CARTERA
/*
    Modifico : Rolphy Quintero - Asesoftware - Germán Muñoz
    fecha :  Septiembre 3 de 2015 - Mantis 38430 - Proyecto Castigo de Cartera
    Desc : Se adiciona la columna tipo de cargue.
    
    Modifico : Rolphy Quintero - Asesoftware - Germán Muñoz
    fecha :  Agosto 13 de 2015 - Mantis 38430 - Proyecto Castigo de Cartera
    Desc : Creación del trigger.
*/
  AFTER INSERT ON SIM_CASTIGO_CARTERA FOR EACH ROW
Declare
  vl_Tipo_Operacion  SIM_HISTORIAL_CASTIGO_CARTERA.Tipo_Operacion%type;
Begin
  If Inserting Then
    vl_Tipo_Operacion := 'C'; -- Creación
    INSERT INTO SIM_HISTORIAL_CASTIGO_CARTERA (SECUENCIA, ROWID_CASTIGO_CARTERA, FECHA_CREACION_REGISTRO, TIPO_OPERACION,
    COD_CIA, COD_SECC, COD_RAMO, NUM_POL1, NUM_FACTURA, TDOC_TERCERO, NRO_DOCUMTO, COD_AGENCIA, IMP_PRIMA, IMP_IMPTOS,
    IMP_DER_EMI, COMISION, COD_MON, TC, COD_CASTIGO, OBSERVACION, FECHA_CARGUE, FECHA_VALIDACION, USUARIO_CARGUE,
    USUARIO_VALIDACION, OBSERVACION_RECHAZO, COD_RECHAZO, FECHA_CREACION, COD_COMITE, FECHA_MODIFICACION,
    USUARIO_MODIFICACION, TIPO_CARGUE) VALUES (SEQ_HISTORIAL_CASTIGO_CARTERA.NEXTVAL,
    :NEW.ROWID, SYSDATE, vl_Tipo_Operacion, :NEW.COD_CIA, :NEW.COD_SECC, :NEW.COD_RAMO, :NEW.NUM_POL1, :NEW.NUM_FACTURA, :NEW.TDOC_TERCERO,
    :NEW.NRO_DOCUMTO, :NEW.COD_AGENCIA, :NEW.IMP_PRIMA, :NEW.IMP_IMPTOS, :NEW.IMP_DER_EMI, :NEW.COMISION, :NEW.COD_MON, :NEW.TC,
    :NEW.COD_CASTIGO, :NEW.OBSERVACION, :NEW.FECHA_CARGUE, :NEW.FECHA_VALIDACION, :NEW.USUARIO_CARGUE, :NEW.USUARIO_VALIDACION,
    :NEW.OBSERVACION_RECHAZO, :NEW.COD_RECHAZO, :NEW.FECHA_CREACION, :NEW.COD_COMITE, NULL, NULL, :NEW.TIPO_CARGUE);
  End If;
End TR_AIR_SIM_CASTIGO_CARTERA;
/
