CREATE OR REPLACE TRIGGER TR_AIUDR_SIMAPI_COB_BIEN_JN
  AFTER 
  INSERT OR 
  UPDATE OR 
  DELETE ON SIMAPI_COBERTURAS_BIEN for each row
Declare 
  rec SIMAPI_COBERTURAS_BIEN_JN%ROWTYPE; 
  blank SIMAPI_COBERTURAS_BIEN_JN%ROWTYPE; 
  BEGIN 
    rec := blank; 
    IF INSERTING OR UPDATING THEN 
      rec.COD_CIA := :NEW.COD_CIA; 
      rec.COD_COB := :NEW.COD_COB; 
      rec.ID_BIEN := :NEW.ID_BIEN; 
      rec.ESTADO := :NEW.ESTADO; 
      rec.MCA_BENEF := :NEW.MCA_BENEF; 
      rec.USUARIO_CREACION := :NEW.USUARIO_CREACION; 
      rec.FECHA_CREACION := :NEW.FECHA_CREACION; 
      rec.MCA_UNICO := :NEW.MCA_UNICO; 
      rec.USUARIO_MODIFICACION := :NEW.USUARIO_MODIFICACION; 
      rec.FECHA_MODIFICACION := :NEW.FECHA_MODIFICACION; 
      rec.JN_DATETIME := SYSDATE; 
      rec.JN_ORACLE_USER := SYS_CONTEXT ('USERENV', 'SESSION_USER'); 
      rec.JN_APPLN := SYS_CONTEXT ('USERENV', 'MODULE'); 
      rec.JN_SESSION := SYS_CONTEXT ('USERENV', 'SESSIONID'); 
      IF INSERTING THEN 
        rec.JN_OPERATION := 'INS'; 
      ELSIF UPDATING THEN 
        rec.JN_OPERATION := 'UPD'; 
      END IF; 
    ELSIF DELETING THEN 
      rec.COD_CIA := :OLD.COD_CIA; 
      rec.COD_COB := :OLD.COD_COB; 
      rec.ID_BIEN := :OLD.ID_BIEN; 
      rec.ESTADO := :OLD.ESTADO; 
      rec.MCA_BENEF := :OLD.MCA_BENEF; 
      rec.USUARIO_CREACION := :OLD.USUARIO_CREACION; 
      rec.FECHA_CREACION := :OLD.FECHA_CREACION; 
      rec.MCA_UNICO := :OLD.MCA_UNICO; 
      rec.USUARIO_MODIFICACION := :OLD.USUARIO_MODIFICACION; 
      rec.FECHA_MODIFICACION := :OLD.FECHA_MODIFICACION; 
      rec.JN_DATETIME := SYSDATE; 
      rec.JN_ORACLE_USER := SYS_CONTEXT ('USERENV', 'SESSION_USER'); 
      rec.JN_APPLN := SYS_CONTEXT ('USERENV', 'MODULE'); 
      rec.JN_SESSION := SYS_CONTEXT ('USERENV', 'SESSIONID'); 
      rec.JN_OPERATION := 'DEL'; 
    END IF; 
    INSERT into SIMAPI_COBERTURAS_BIEN_JN VALUES rec; 
  END;
/
