CREATE OR REPLACE TRIGGER TR_AIUDR_CARGA_RES
      AFTER INSERT OR UPDATE OR DELETE ON SIM_CARGA_RESERVAS
FOR EACH ROW
 /*
   <Creacion>
   <Autor>Carlos Eduardo Mayorga</Autor>
   <Fecha>15/09/2016</Fecha>
   <Objetivo>Enviar la informacion a la tabla de auditoria</Objetivo>
  </Creacion>
 */
DECLARE
 l_operacion VARCHAR2(3);
BEGIN
  IF inserting THEN
    INSERT INTO SIM_CARGA_RESERVAS_JN(JN_SECUENCIA, JN_OPERACION, JN_ORACLE_USER,
      JN_DATETIME, SECUENCIA_CAR_EXPE, CONSECUTIVO,
      PROCESO, COD_CIA, COD_SECC,
      COD_RAMO, TIPO_EXPED, NRO_EXPED,
      COD_COB, COD_CONCEP_RVA, COD_MON,
      VALOR_MOVIM, APLICA_DEDUCIBLE, MCA_PROCESO,
      FECHA_PROCESO, MCA_PROCESO_TER, FECHA_PROCESO_TER)
    VALUES(SEQ_SIM_CAR_RES_JN.NEXTVAL, 'INS', USER,
      SYSDATE, :NEW.SECUENCIA_CAR_EXPE, :NEW.CONSECUTIVO,
      :NEW.PROCESO, :NEW.COD_CIA, :NEW.COD_SECC,
      :NEW.COD_RAMO, :NEW.TIPO_EXPED, :NEW.NRO_EXPED,
      :NEW.COD_COB, :NEW.COD_CONCEP_RVA, :NEW.COD_MON,
      :NEW.VALOR_MOVIM, :NEW.APLICA_DEDUCIBLE, :NEW.MCA_PROCESO,
      :NEW.FECHA_PROCESO, :NEW.MCA_PROCESO_TER, :NEW.FECHA_PROCESO_TER);
  ELSE
    IF updating THEN
	  l_operacion := 'UPD';
    ELSIF deleting THEN 
	  l_operacion := 'DEL';
	END IF;
    INSERT INTO SIM_CARGA_RESERVAS_JN(JN_SECUENCIA, JN_OPERACION, JN_ORACLE_USER,
      JN_DATETIME, SECUENCIA_CAR_EXPE, CONSECUTIVO,
      PROCESO, COD_CIA, COD_SECC,
      COD_RAMO, TIPO_EXPED, NRO_EXPED,
      COD_COB, COD_CONCEP_RVA, COD_MON,
      VALOR_MOVIM, APLICA_DEDUCIBLE, MCA_PROCESO,
      FECHA_PROCESO, MCA_PROCESO_TER, FECHA_PROCESO_TER)
    VALUES(SEQ_SIM_CAR_RES_JN.NEXTVAL, l_operacion, USER,
      SYSDATE, :OLD.SECUENCIA_CAR_EXPE, :OLD.CONSECUTIVO,
      :OLD.PROCESO, :OLD.COD_CIA, :OLD.COD_SECC,
      :OLD.COD_RAMO, :OLD.TIPO_EXPED, :OLD.NRO_EXPED,
      :OLD.COD_COB, :OLD.COD_CONCEP_RVA, :OLD.COD_MON,
      :OLD.VALOR_MOVIM, :OLD.APLICA_DEDUCIBLE, :OLD.MCA_PROCESO,
      :OLD.FECHA_PROCESO, :OLD.MCA_PROCESO_TER, :OLD.FECHA_PROCESO_TER);
  END IF;
END TR_AIUDR_CARGA_RES;
/
