CREATE OR REPLACE TRIGGER TR_AIUDR_CARGA_LIQ
      AFTER INSERT OR UPDATE OR DELETE ON SIM_CARGA_LIQUIDACIONES
FOR EACH ROW
 /*
   <Creacion>
   <Autor>Carlos Eduardo Mayorga</Autor>
   <Fecha>15/09/2016</Fecha>
   <Objetivo>Enviar la informacion a la tabla de auditoria</Objetivo>
  </Creacion>
 */
DECLARE
 l_operacion VARCHAR2(3);
BEGIN
  IF inserting THEN
    INSERT INTO SIM_CARGA_LIQUIDACIONES_JN(JN_SECUENCIA, JN_OPERACION, JN_ORACLE_USER,
      JN_DATETIME, SECUENCIA, PROCESO, 
      ENT_COLOCADORA, SISTEMA_ORIGEN, COD_CIA, 
      COD_SECC, COD_RAMO, NUM_POL1, 
      NUM_SINI, SECUENCIA_CAR_SINI, TIPO_EXPED,
      NRO_EXPED, SECUENCIA_CAR_EXPE, TIPO_LIQUIDACION, 
      COD_USER, NRO_FACTURA, FECHA_FACTURA, 
      FACTURA_EXENTA, LOCALIDAD_FACTURA, COD_MON, 
      TASA_CAMBIO, GENERA_ORDEN_PAGO, AGENCIA_GIRO, 
      REQUIERE_AUTORIZA, TDOC_BENEF, NDOC_BENEF, 
      COD_ACT_BENEF, ACTIV_ECONOMICA, SUBACTIV_ECONOMICA, 
      OBSERVACION, COD_TEXTO, SUB_COD_TEXTO, 
      AUTORIZANTE, TOTAL_FACTURA, TOTAL_LIQUIDACION, 
      FECHA_PAGO, MCA_COASEGURO, NUM_LIQUIDACION, 
      NUM_ORDEN_PAGO, COD_CAUSA_ANU, FECHA_ANULACION, 
      SIM_USUARIO, MCA_PROCESO, FECHA_PROCESO, 
      MCA_PROCESO_TER, FECHA_PROCESO_TER, USUARIO_CREACION, 
      FECHA_CREACION, USUARIO_MODIFICACION, FECHA_MODIFICACION)
    VALUES(SEQ_SIM_CAR_LIQ_JN.NEXTVAL, 'INS', USER,
      SYSDATE, :NEW.SECUENCIA, :NEW.PROCESO,
      :NEW.ENT_COLOCADORA, :NEW.SISTEMA_ORIGEN, :NEW.COD_CIA, 
      :NEW.COD_SECC, :NEW.COD_RAMO, :NEW.NUM_POL1, 
      :NEW.NUM_SINI, :NEW.SECUENCIA_CAR_SINI, :NEW.TIPO_EXPED, 
      :NEW.NRO_EXPED, :NEW.SECUENCIA_CAR_EXPE, :NEW.TIPO_LIQUIDACION, 
      :NEW.COD_USER, :NEW.NRO_FACTURA, :NEW.FECHA_FACTURA, 
      :NEW.FACTURA_EXENTA, :NEW.LOCALIDAD_FACTURA, :NEW.COD_MON, 
      :NEW.TASA_CAMBIO, :NEW.GENERA_ORDEN_PAGO, :NEW.AGENCIA_GIRO, 
      :NEW.REQUIERE_AUTORIZA, :NEW.TDOC_BENEF, :NEW.NDOC_BENEF, 
      :NEW.COD_ACT_BENEF, :NEW.ACTIV_ECONOMICA, :NEW.SUBACTIV_ECONOMICA, 
      :NEW.OBSERVACION, :NEW.COD_TEXTO, :NEW.SUB_COD_TEXTO, 
      :NEW.AUTORIZANTE, :NEW.TOTAL_FACTURA, :NEW.TOTAL_LIQUIDACION, 
      :NEW.FECHA_PAGO, :NEW.MCA_COASEGURO, :NEW.NUM_LIQUIDACION, 
      :NEW.NUM_ORDEN_PAGO, :NEW.COD_CAUSA_ANU, :NEW.FECHA_ANULACION, 
      :NEW.SIM_USUARIO, :NEW.MCA_PROCESO, :NEW.FECHA_PROCESO, 
      :NEW.MCA_PROCESO_TER, :NEW.FECHA_PROCESO_TER, :NEW.USUARIO_CREACION, 
      :NEW.FECHA_CREACION, :NEW.USUARIO_MODIFICACION, :NEW.FECHA_MODIFICACION);
  ELSE
    IF updating THEN
	  l_operacion := 'UPD';
    ELSIF deleting THEN 
	  l_operacion := 'DEL';
	END IF;
    INSERT INTO SIM_CARGA_LIQUIDACIONES_JN(JN_SECUENCIA, JN_OPERACION, JN_ORACLE_USER,
      JN_DATETIME, SECUENCIA, PROCESO, 
      ENT_COLOCADORA, SISTEMA_ORIGEN, COD_CIA, 
      COD_SECC, COD_RAMO, NUM_POL1, 
      NUM_SINI, SECUENCIA_CAR_SINI, TIPO_EXPED,
      NRO_EXPED, SECUENCIA_CAR_EXPE, TIPO_LIQUIDACION, 
      COD_USER, NRO_FACTURA, FECHA_FACTURA, 
      FACTURA_EXENTA, LOCALIDAD_FACTURA, COD_MON, 
      TASA_CAMBIO, GENERA_ORDEN_PAGO, AGENCIA_GIRO, 
      REQUIERE_AUTORIZA, TDOC_BENEF, NDOC_BENEF, 
      COD_ACT_BENEF, ACTIV_ECONOMICA, SUBACTIV_ECONOMICA, 
      OBSERVACION, COD_TEXTO, SUB_COD_TEXTO, 
      AUTORIZANTE, TOTAL_FACTURA, TOTAL_LIQUIDACION, 
      FECHA_PAGO, MCA_COASEGURO, NUM_LIQUIDACION, 
      NUM_ORDEN_PAGO, COD_CAUSA_ANU, FECHA_ANULACION, 
      SIM_USUARIO, MCA_PROCESO, FECHA_PROCESO, 
      MCA_PROCESO_TER, FECHA_PROCESO_TER, USUARIO_CREACION, 
      FECHA_CREACION, USUARIO_MODIFICACION, FECHA_MODIFICACION)
    VALUES(SEQ_SIM_CAR_LIQ_JN.NEXTVAL, l_operacion, USER,
      SYSDATE, :OLD.SECUENCIA, :OLD.PROCESO,
      :OLD.ENT_COLOCADORA, :OLD.SISTEMA_ORIGEN, :OLD.COD_CIA, 
      :OLD.COD_SECC, :OLD.COD_RAMO, :OLD.NUM_POL1, 
      :OLD.NUM_SINI, :OLD.SECUENCIA_CAR_SINI, :OLD.TIPO_EXPED, 
      :OLD.NRO_EXPED, :OLD.SECUENCIA_CAR_EXPE, :OLD.TIPO_LIQUIDACION, 
      :OLD.COD_USER, :OLD.NRO_FACTURA, :OLD.FECHA_FACTURA, 
      :OLD.FACTURA_EXENTA, :OLD.LOCALIDAD_FACTURA, :OLD.COD_MON, 
      :OLD.TASA_CAMBIO, :OLD.GENERA_ORDEN_PAGO, :OLD.AGENCIA_GIRO, 
      :OLD.REQUIERE_AUTORIZA, :OLD.TDOC_BENEF, :OLD.NDOC_BENEF, 
      :OLD.COD_ACT_BENEF, :OLD.ACTIV_ECONOMICA, :OLD.SUBACTIV_ECONOMICA, 
      :OLD.OBSERVACION, :OLD.COD_TEXTO, :OLD.SUB_COD_TEXTO, 
      :OLD.AUTORIZANTE, :OLD.TOTAL_FACTURA, :OLD.TOTAL_LIQUIDACION, 
      :OLD.FECHA_PAGO, :OLD.MCA_COASEGURO, :OLD.NUM_LIQUIDACION, 
      :OLD.NUM_ORDEN_PAGO, :OLD.COD_CAUSA_ANU, :OLD.FECHA_ANULACION, 
      :OLD.SIM_USUARIO, :OLD.MCA_PROCESO, :OLD.FECHA_PROCESO, 
      :OLD.MCA_PROCESO_TER, :OLD.FECHA_PROCESO_TER, :OLD.USUARIO_CREACION, 
      :OLD.FECHA_CREACION, :OLD.USUARIO_MODIFICACION, :OLD.FECHA_MODIFICACION);
  END IF;
END TR_AIUDR_CARGA_LIQ;
/
