CREATE OR REPLACE TRIGGER TR_AIUDR_SIMAPI_OPCBIENEST_JN
  AFTER 
  INSERT OR 
  UPDATE OR 
  DELETE ON SIMAPI_OPC_BIEN_EST for each row
Declare 
  rec SIMAPI_OPC_BIEN_EST_JN%ROWTYPE; 
  blank SIMAPI_OPC_BIEN_EST_JN%ROWTYPE; 
  BEGIN 
    rec := blank; 
    IF INSERTING OR UPDATING THEN 
      rec.ID_PLANTILLA_ESTRATEGIA := :NEW.ID_PLANTILLA_ESTRATEGIA; 
      rec.ID_BIEN := :NEW.ID_BIEN; 
      rec.COD_OPCION := :NEW.COD_OPCION; 
      rec.DESC_OPCION := :NEW.DESC_OPCION; 
      rec.ESTADO := :NEW.ESTADO; 
      rec.USUARIO_CREACION := :NEW.USUARIO_CREACION; 
      rec.FECHA_CREACION := :NEW.FECHA_CREACION; 
      rec.USUARIO_MODIFCACION := :NEW.USUARIO_MODIFCACION; 
      rec.FECHA_MODIFICACION := :NEW.FECHA_MODIFICACION; 
      rec.JN_DATETIME := SYSDATE; 
      rec.JN_ORACLE_USER := SYS_CONTEXT ('USERENV', 'SESSION_USER'); 
      rec.JN_APPLN := SYS_CONTEXT ('USERENV', 'MODULE'); 
      rec.JN_SESSION := SYS_CONTEXT ('USERENV', 'SESSIONID'); 
      IF INSERTING THEN 
        rec.JN_OPERATION := 'INS'; 
      ELSIF UPDATING THEN 
        rec.JN_OPERATION := 'UPD'; 
      END IF; 
    ELSIF DELETING THEN 
      rec.ID_PLANTILLA_ESTRATEGIA := :OLD.ID_PLANTILLA_ESTRATEGIA; 
      rec.ID_BIEN := :OLD.ID_BIEN; 
      rec.COD_OPCION := :OLD.COD_OPCION; 
      rec.DESC_OPCION := :OLD.DESC_OPCION; 
      rec.ESTADO := :OLD.ESTADO; 
      rec.USUARIO_CREACION := :OLD.USUARIO_CREACION; 
      rec.FECHA_CREACION := :OLD.FECHA_CREACION; 
      rec.USUARIO_MODIFCACION := :OLD.USUARIO_MODIFCACION; 
      rec.FECHA_MODIFICACION := :OLD.FECHA_MODIFICACION; 
      rec.JN_DATETIME := SYSDATE; 
      rec.JN_ORACLE_USER := SYS_CONTEXT ('USERENV', 'SESSION_USER'); 
      rec.JN_APPLN := SYS_CONTEXT ('USERENV', 'MODULE'); 
      rec.JN_SESSION := SYS_CONTEXT ('USERENV', 'SESSIONID'); 
      rec.JN_OPERATION := 'DEL'; 
    END IF; 
    INSERT into SIMAPI_OPC_BIEN_EST_JN VALUES rec; 
  END;
/
