CREATE OR REPLACE TRIGGER TR_AIUDR_SIMAPI_ESTRATEGIAS_JN
  AFTER 
  INSERT OR 
  UPDATE OR 
  DELETE ON SIMAPI_ESTRATEGIAS for each row
Declare 
  rec SIMAPI_ESTRATEGIAS_JN%ROWTYPE; 
  blank SIMAPI_ESTRATEGIAS_JN%ROWTYPE; 
  BEGIN 
    rec := blank; 
    IF INSERTING OR UPDATING THEN 
      rec.ID_ESTRATEGIA := :NEW.ID_ESTRATEGIA; 
      rec.DESCRIPCION := :NEW.DESCRIPCION; 
      rec.ID_PLANTILLA_ESTRATEGIA := :NEW.ID_PLANTILLA_ESTRATEGIA; 
      rec.ESTADO := :NEW.ESTADO; 
      rec.USUARIO_CREACION := :NEW.USUARIO_CREACION; 
      rec.FECHA_CREACION := :NEW.FECHA_CREACION; 
      rec.USUARIO_MODIFICACION := :NEW.USUARIO_MODIFICACION; 
      rec.FECHA_MODIFICACION := :NEW.FECHA_MODIFICACION; 
      rec.CLAUSULADO := :NEW.CLAUSULADO; 
      rec.JN_DATETIME := SYSDATE; 
      rec.JN_ORACLE_USER := SYS_CONTEXT ('USERENV', 'SESSION_USER'); 
      rec.JN_APPLN := SYS_CONTEXT ('USERENV', 'MODULE'); 
      rec.JN_SESSION := SYS_CONTEXT ('USERENV', 'SESSIONID'); 
      IF INSERTING THEN 
        rec.JN_OPERATION := 'INS'; 
      ELSIF UPDATING THEN 
        rec.JN_OPERATION := 'UPD'; 
      END IF; 
    ELSIF DELETING THEN 
      rec.ID_ESTRATEGIA := :OLD.ID_ESTRATEGIA; 
      rec.DESCRIPCION := :OLD.DESCRIPCION; 
      rec.ID_PLANTILLA_ESTRATEGIA := :OLD.ID_PLANTILLA_ESTRATEGIA; 
      rec.ESTADO := :OLD.ESTADO; 
      rec.USUARIO_CREACION := :OLD.USUARIO_CREACION; 
      rec.FECHA_CREACION := :OLD.FECHA_CREACION; 
      rec.USUARIO_MODIFICACION := :OLD.USUARIO_MODIFICACION; 
      rec.FECHA_MODIFICACION := :OLD.FECHA_MODIFICACION; 
      rec.CLAUSULADO := :OLD.CLAUSULADO; 
      rec.JN_DATETIME := SYSDATE; 
      rec.JN_ORACLE_USER := SYS_CONTEXT ('USERENV', 'SESSION_USER'); 
      rec.JN_APPLN := SYS_CONTEXT ('USERENV', 'MODULE'); 
      rec.JN_SESSION := SYS_CONTEXT ('USERENV', 'SESSIONID'); 
      rec.JN_OPERATION := 'DEL'; 
    END IF; 
    INSERT into SIMAPI_ESTRATEGIAS_JN VALUES rec; 
  END;
/
