CREATE OR REPLACE TRIGGER TR_AIUDR_CARGA_EXPE
      AFTER INSERT OR UPDATE OR DELETE ON SIM_CARGA_EXPEDIENTES
FOR EACH ROW
 /*
   <Creacion>
   <Autor>Carlos Eduardo Mayorga</Autor>
   <Fecha>15/09/2016</Fecha>
   <Objetivo>Enviar la informacion a la tabla de auditoria</Objetivo>
  </Creacion>
 */
DECLARE
 l_operacion VARCHAR2(3);
BEGIN
  IF inserting THEN
    INSERT INTO SIM_CARGA_EXPEDIENTES_JN(JN_SECUENCIA, JN_OPERACION, JN_ORACLE_USER,
      JN_DATETIME, SECUENCIA, SECUENCIA_CAR_SINI,
      PROCESO, SISTEMA_ORIGEN, COD_CIA,
      COD_SECC, COD_RAMO, NUM_SINI,
      TIPO_EXPED, NRO_EXPED, FEC_APER_EXP,
      COD_USER, COD_AGEN_TRAMI, COD_MON,
      TASA_CAMBIO, MCA_RECUP, NRO_EXPED_AFEC,
      COD_MODI_EXP, FEC_MODI_EXP, COD_BAJA_EXP,
      FEC_BAJA_EXP, COD_REAP_EXP, FEC_REAP_EXP, 
      SIM_USUARIO, MCA_PROCESO, FECHA_PROCESO,
      MCA_PROCESO_TER, FECHA_PROCESO_TER, USUARIO_CREACION,
      FECHA_CREACION, USUARIO_MODIFICACION, FECHA_MODIFICACION)
    VALUES(SEQ_SIM_CAR_EXPE_JN.NEXTVAL, 'INS', USER,
      SYSDATE, :NEW.SECUENCIA, :NEW.SECUENCIA_CAR_SINI,
      :NEW.PROCESO, :NEW.SISTEMA_ORIGEN, :NEW.COD_CIA,
      :NEW.COD_SECC, :NEW.COD_RAMO, :NEW.NUM_SINI,
      :NEW.TIPO_EXPED, :NEW.NRO_EXPED, :NEW.FEC_APER_EXP,
      :NEW.COD_USER, :NEW.COD_AGEN_TRAMI, :NEW.COD_MON,
      :NEW.TASA_CAMBIO, :NEW.MCA_RECUP, :NEW.NRO_EXPED_AFEC,
      :NEW.COD_MODI_EXP, :NEW.FEC_MODI_EXP, :NEW.COD_BAJA_EXP,
      :NEW.FEC_BAJA_EXP, :NEW.COD_REAP_EXP, :NEW.FEC_REAP_EXP, 
      :NEW.SIM_USUARIO, :NEW.MCA_PROCESO, :NEW.FECHA_PROCESO,
      :NEW.MCA_PROCESO_TER, :NEW.FECHA_PROCESO_TER, :NEW.USUARIO_CREACION,
      :NEW.FECHA_CREACION, :NEW.USUARIO_MODIFICACION, :NEW.FECHA_MODIFICACION);
  ELSE
    IF updating THEN
	  l_operacion := 'UPD';
    ELSIF deleting THEN 
	  l_operacion := 'DEL';
	END IF;
    INSERT INTO SIM_CARGA_EXPEDIENTES_JN(JN_SECUENCIA, JN_OPERACION, JN_ORACLE_USER,
      JN_DATETIME, SECUENCIA, SECUENCIA_CAR_SINI,
      PROCESO, SISTEMA_ORIGEN, COD_CIA,
      COD_SECC, COD_RAMO, NUM_SINI,
      TIPO_EXPED, NRO_EXPED, FEC_APER_EXP,
      COD_USER, COD_AGEN_TRAMI, COD_MON,
      TASA_CAMBIO, MCA_RECUP, NRO_EXPED_AFEC,
      COD_MODI_EXP, FEC_MODI_EXP, COD_BAJA_EXP,
      FEC_BAJA_EXP, COD_REAP_EXP, FEC_REAP_EXP, 
      SIM_USUARIO, MCA_PROCESO, FECHA_PROCESO,
      MCA_PROCESO_TER, FECHA_PROCESO_TER, USUARIO_CREACION,
      FECHA_CREACION, USUARIO_MODIFICACION, FECHA_MODIFICACION)
    VALUES(SEQ_SIM_CAR_EXPE_JN.NEXTVAL, l_operacion, USER,
      SYSDATE, :OLD.SECUENCIA, :OLD.SECUENCIA_CAR_SINI,
      :OLD.PROCESO, :OLD.SISTEMA_ORIGEN, :OLD.COD_CIA,
      :OLD.COD_SECC, :OLD.COD_RAMO, :OLD.NUM_SINI,
      :OLD.TIPO_EXPED, :OLD.NRO_EXPED, :OLD.FEC_APER_EXP,
      :OLD.COD_USER, :OLD.COD_AGEN_TRAMI, :OLD.COD_MON,
      :OLD.TASA_CAMBIO, :OLD.MCA_RECUP, :OLD.NRO_EXPED_AFEC,
      :OLD.COD_MODI_EXP, :OLD.FEC_MODI_EXP, :OLD.COD_BAJA_EXP,
      :OLD.FEC_BAJA_EXP, :OLD.COD_REAP_EXP, :OLD.FEC_REAP_EXP, 
      :OLD.SIM_USUARIO, :OLD.MCA_PROCESO, :OLD.FECHA_PROCESO,
      :OLD.MCA_PROCESO_TER, :OLD.FECHA_PROCESO_TER, :OLD.USUARIO_CREACION,
      :OLD.FECHA_CREACION, :OLD.USUARIO_MODIFICACION, :OLD.FECHA_MODIFICACION);
  END IF;
END TR_AIUDR_CARGA_EXPE;
/
