CREATE OR REPLACE TRIGGER TR_AIUDR_SIMAPI_CONSBIEPROD_JN
  AFTER 
  INSERT OR 
  UPDATE OR 
  DELETE ON SIMAPI_CONSEC_BIEN_PROD for each row
Declare 
  rec SIMAPI_CONSEC_BIEN_PROD_JN%ROWTYPE; 
  blank SIMAPI_CONSEC_BIEN_PROD_JN%ROWTYPE; 
  BEGIN 
    rec := blank; 
    IF INSERTING OR UPDATING THEN 
      rec.ID_BIEN := :NEW.ID_BIEN; 
      rec.COD_CONS := :NEW.COD_CONS; 
      rec.DESC_CONS := :NEW.DESC_CONS; 
      rec.ESTADO := :NEW.ESTADO; 
      rec.FECHA_CREACION := :NEW.FECHA_CREACION; 
      rec.USUARIO_CREACION := :NEW.USUARIO_CREACION; 
      rec.DESC_CONS_USUARIO := :NEW.DESC_CONS_USUARIO; 
      rec.FECHA_MODIFICACION := :NEW.FECHA_MODIFICACION; 
      rec.USUARIO_MODIFICACION := :NEW.USUARIO_MODIFICACION; 
      rec.JN_DATETIME := SYSDATE; 
      rec.JN_ORACLE_USER := SYS_CONTEXT ('USERENV', 'SESSION_USER'); 
      rec.JN_APPLN := SYS_CONTEXT ('USERENV', 'MODULE'); 
      rec.JN_SESSION := SYS_CONTEXT ('USERENV', 'SESSIONID'); 
      IF INSERTING THEN 
        rec.JN_OPERATION := 'INS'; 
      ELSIF UPDATING THEN 
        rec.JN_OPERATION := 'UPD'; 
      END IF; 
    ELSIF DELETING THEN 
      rec.ID_BIEN := :OLD.ID_BIEN; 
      rec.COD_CONS := :OLD.COD_CONS; 
      rec.DESC_CONS := :OLD.DESC_CONS; 
      rec.ESTADO := :OLD.ESTADO; 
      rec.FECHA_CREACION := :OLD.FECHA_CREACION; 
      rec.USUARIO_CREACION := :OLD.USUARIO_CREACION; 
      rec.DESC_CONS_USUARIO := :OLD.DESC_CONS_USUARIO; 
      rec.FECHA_MODIFICACION := :OLD.FECHA_MODIFICACION; 
      rec.USUARIO_MODIFICACION := :OLD.USUARIO_MODIFICACION; 
      rec.JN_DATETIME := SYSDATE; 
      rec.JN_ORACLE_USER := SYS_CONTEXT ('USERENV', 'SESSION_USER'); 
      rec.JN_APPLN := SYS_CONTEXT ('USERENV', 'MODULE'); 
      rec.JN_SESSION := SYS_CONTEXT ('USERENV', 'SESSIONID'); 
      rec.JN_OPERATION := 'DEL'; 
    END IF; 
    INSERT into SIMAPI_CONSEC_BIEN_PROD_JN VALUES rec; 
  END;
/
