CREATE OR REPLACE TRIGGER TR_BUDR_SIM_CAST_CART_RECHAZO
/*
    Modifico : Rolphy Quintero - Asesoftware - Germán Muñoz
    fecha :  Agosto 25 de 2015 - Mantis 38430 - Proyecto Castigo de Cartera
    Desc : Creación del trigger. Auditar tabla SIM_CASTIGO_CARTERA_RECHAZO.
*/
  BEFORE UPDATE OR DELETE ON SIM_CASTIGO_CARTERA_RECHAZO FOR EACH ROW
Declare
  vl_Tipo_Operacion  SIM_HISTORIAL_CASTCART_RECHAZO.Tipo_Operacion%type;
Begin
  If Updating Then
    vl_Tipo_Operacion := 'A'; -- Actualización
    INSERT INTO SIM_HISTORIAL_CASTCART_RECHAZO (SECUENCIA, ROWID_CASTCART_COD_RECHAZO, FECHA_CREACION_REGISTRO, TIPO_OPERACION, COD_RECHAZO,
    DESCRIPCION, EVENTO, FECHA_CREACION, USUARIO_CREACION, FECHA_MODIFICACION, USUARIO_MODIFICACION)
    VALUES (SEQ_HISTORIAL_CASTCART_RECHAZO.NEXTVAL, :NEW.ROWID, SYSDATE, vl_Tipo_Operacion, :NEW.COD_RECHAZO,
    :NEW.DESCRIPCION, :NEW.EVENTO, :NEW.FECHA_CREACION, :NEW.USUARIO_CREACION, :NEW.FECHA_MODIFICACION, :NEW.USUARIO_MODIFICACION);
  Elsif Deleting Then
    vl_Tipo_Operacion := 'B'; -- Borrado
    INSERT INTO SIM_HISTORIAL_CASTCART_RECHAZO (SECUENCIA, ROWID_CASTCART_COD_RECHAZO, FECHA_CREACION_REGISTRO, TIPO_OPERACION, COD_RECHAZO,
    DESCRIPCION, EVENTO, FECHA_CREACION, USUARIO_CREACION, FECHA_MODIFICACION, USUARIO_MODIFICACION)
    VALUES (SEQ_HISTORIAL_CASTCART_RECHAZO.NEXTVAL, :OLD.ROWID, SYSDATE, vl_Tipo_Operacion, :OLD.COD_RECHAZO,
    :OLD.DESCRIPCION, :OLD.EVENTO, :OLD.FECHA_CREACION, :OLD.USUARIO_CREACION, :OLD.FECHA_MODIFICACION, :OLD.USUARIO_MODIFICACION);
  End If;
End TR_BUDR_SIM_CAST_CART_RECHAZO;
/
