CREATE OR REPLACE TRIGGER "TR_BI_R_SIM_TEMP_PLANOS_BANCA" 
BEFORE INSERT ON SIM_TEMPORAL_PLANOS_BANCA 
FOR EACH ROW
DECLARE
  L_SECUENCIA NUMBER := 0;
BEGIN
  L_SECUENCIA := SEQ_SIM_TEMPORAL_PLANOS_BANCA.NEXTVAL;
  :NEW.SIM_SECUENCIA := L_SECUENCIA;
END TR_BI_R_SIM_TEMP_PLANOS_BANCA;
/
