CREATE OR REPLACE TRIGGER TR_BI_AUTOSCLTVAS_ERR_SERV
BEFORE INSERT ON SIM_X_AUTOS_CLTVAS_ERR_SERV
FOR EACH ROW
BEGIN
  SELECT SEQ_SIM_X_AUTOSCLTVAS_ERR_SERV.NEXTVAL
  INTO :NEW.ID_ERR_SERVICIO
  FROM DUAL;
END TR_BI_AUTOSCLTVAS_ERR_SERV;
/
