CREATE OR REPLACE TRIGGER "TR_BD_CAMBIOS_PREVENCION" 
       before delete 
  on CAMBIOS_PREVENCION FOR EACH ROW
declare

begin

  INSERT INTO LOG_CAMBIOS_PREVENCION

   ( NUM_POL1,
     NUM_SECU_POL,
     NUM_END,
     NRO_DOCUMTO,
     FECHA_VIG_POL,
     MCA_PROCESADO,
     MCA_PROVISORIO,
     COD_CIA,
     COD_RAMO,
     COD_SEC,
     FECHA_BORRADO)
   VALUES
   ( :OLD.NUM_POL1,
     :OLD.NUM_SECU_POL,
     :OLD.NUM_END,
     :OLD.NRO_DOCUMTO,
     :OLD.FECHA_VIG_POL,
     :OLD.MCA_PROCESADO,
     :OLD.MCA_PROVISORIO,
     :OLD.COD_CIA,
     :OLD.COD_RAMO,
     :OLD.COD_SECC,
     sysdate );

end TR_BD_CAMBIOS_PREVENCION;
/
