CREATE OR REPLACE TRIGGER TR_BUDR_C1010816
/*
    Modifico : Rolphy Quintero - Asesoftware - German Mu?oz
    fecha :  Febrero 11 de 2016 - Mantis 42926 - Proyecto Castigo de Cartera
    Desc : Creacion del trigger para auditar tabla C1010816.
*/
  BEFORE UPDATE OR DELETE ON C1010816 FOR EACH ROW
Declare
  vl_Tipo_Operacion  SIM_HISTORIAL_C1010816.Tipo_Operacion%type;
Begin
  If Updating Then
    vl_Tipo_Operacion := 'A'; -- Actualizacion
    INSERT INTO SIM_HISTORIAL_C1010816 (SECUENCIA, ROWID_C1010816, FECHA_CREACION_REGISTRO, TIPO_OPERACION,
    COD_SECC, COD_RAMO, COD_PROD, FECHA_CREACION, USUARIO_CREACION)
    VALUES (SEQ_HISTORIAL_C1010816.NEXTVAL, :NEW.ROWID, SYSDATE, vl_Tipo_Operacion,
    :NEW.COD_SECC, :NEW.COD_RAMO, :NEW.COD_PROD, :NEW.FECHA_CREACION, :NEW.USUARIO_CREACION);
  Elsif Deleting Then
    vl_Tipo_Operacion := 'B'; -- Borrado
    INSERT INTO SIM_HISTORIAL_C1010816 (SECUENCIA, ROWID_C1010816, FECHA_CREACION_REGISTRO, TIPO_OPERACION,
    COD_SECC, COD_RAMO, COD_PROD, FECHA_CREACION, USUARIO_CREACION)
    VALUES (SEQ_HISTORIAL_C1010816.NEXTVAL, :OLD.ROWID, SYSDATE, vl_Tipo_Operacion,
    :OLD.COD_SECC, :OLD.COD_RAMO, :OLD.COD_PROD, :OLD.FECHA_CREACION, :OLD.USUARIO_CREACION);
  End If;
End TR_BUDR_C1010816;
/
