CREATE OR REPLACE TRIGGER TR_BUDR_SIM_CAST_CART_TIPCUEN
/*
    Modifico : Rolphy Quintero - Asesoftware - Germán Muñoz
    fecha :  Septiembre 28 de 2015 - Mantis 38430 - Proyecto Castigo de Cartera
    Desc : Se adiciona la columna NATURALEZA a la auditoría.
    
    Modifico : Rolphy Quintero - Asesoftware - Germán Muñoz
    fecha :  Septiembre 25 de 2015 - Mantis 38430 - Proyecto Castigo de Cartera
    Desc : Creación del trigger. Auditar tabla SIM_CAST_CARTERA_TIPO_CUENTAS.
*/
  BEFORE UPDATE OR DELETE ON SIM_CAST_CARTERA_TIPO_CUENTAS FOR EACH ROW
Declare
  vl_Tipo_Operacion  SIM_HISTORIAL_CASTCART_TIPCUEN.Tipo_Operacion%type;
Begin
  If Updating Then
    vl_Tipo_Operacion := 'A'; -- Actualización
    INSERT INTO SIM_HISTORIAL_CASTCART_TIPCUEN (SECUENCIA, ROWID_CASTCART_COD_TIPO_CUENTA, FECHA_CREACION_REGISTRO,
    TIPO_OPERACION, COD_TIPO_CUENTA, DESCRIPCION, ESTADO, FECHA_CREACION, USUARIO_CREACION, FECHA_MODIFICACION,
    USUARIO_MODIFICACION, NATURALEZA)
    VALUES (SEQ_HISTORIAL_CASTCART_TIPCUEN.NEXTVAL, :NEW.ROWID, SYSDATE, vl_Tipo_Operacion, :NEW.COD_TIPO_CUENTA,
    :NEW.DESCRIPCION, :NEW.ESTADO, :NEW.FECHA_CREACION, :NEW.USUARIO_CREACION, :NEW.FECHA_MODIFICACION,
    :NEW.USUARIO_MODIFICACION, :NEW.NATURALEZA);
  Elsif Deleting Then
    vl_Tipo_Operacion := 'B'; -- Borrado
    INSERT INTO SIM_HISTORIAL_CASTCART_TIPCUEN (SECUENCIA, ROWID_CASTCART_COD_TIPO_CUENTA, FECHA_CREACION_REGISTRO,
    TIPO_OPERACION, COD_TIPO_CUENTA, DESCRIPCION, ESTADO, FECHA_CREACION, USUARIO_CREACION, FECHA_MODIFICACION,
    USUARIO_MODIFICACION, NATURALEZA)
    VALUES (SEQ_HISTORIAL_CASTCART_TIPCUEN.NEXTVAL, :OLD.ROWID, SYSDATE, vl_Tipo_Operacion, :OLD.COD_TIPO_CUENTA,
    :OLD.DESCRIPCION, :OLD.ESTADO, :OLD.FECHA_CREACION, :OLD.USUARIO_CREACION, :OLD.FECHA_MODIFICACION,
    :OLD.USUARIO_MODIFICACION, :OLD.NATURALEZA);
  End If;
End TR_BUDR_SIM_CAST_CART_TIPCUEN;
/
