CREATE OR REPLACE TRIGGER TR_BUDR_SIM_CAST_CART_PRODEXC
/*
    Modifico : Rolphy Quintero - Asesoftware - Germán Muñoz
    fecha :  Agosto 26 de 2015 - Mantis 38430 - Proyecto Castigo de Cartera
    Desc : Creación del trigger. Auditar tabla SIM_CAST_CART_PRODUCTO_EXC.
*/
  BEFORE UPDATE OR DELETE ON SIM_CAST_CART_PRODUCTO_EXC FOR EACH ROW
Declare
  vl_Tipo_Operacion  SIM_HISTORIAL_CASTCART_PRODEXC.Tipo_Operacion%type;
Begin
  If Updating Then
    vl_Tipo_Operacion := 'A'; -- Actualización
    INSERT INTO SIM_HISTORIAL_CASTCART_PRODEXC (SECUENCIA, ROWID_CASTCART_PRODUCTO_EXC, FECHA_CREACION_REGISTRO, TIPO_OPERACION,
    COD_CIA, COD_SECC, COD_RAMO, ESTADO, FECHA_CREACION, USUARIO_CREACION, FECHA_MODIFICACION, USUARIO_MODIFICACION)
    VALUES (SEQ_HISTORIAL_CASTCART_PRODEXC.NEXTVAL, :NEW.ROWID, SYSDATE, vl_Tipo_Operacion,
    :NEW.COD_CIA, :NEW.COD_SECC, :NEW.COD_RAMO, :NEW.ESTADO, :NEW.FECHA_CREACION, :NEW.USUARIO_CREACION, :NEW.FECHA_MODIFICACION, :NEW.USUARIO_MODIFICACION);
  Elsif Deleting Then
    vl_Tipo_Operacion := 'B'; -- Borrado
    INSERT INTO SIM_HISTORIAL_CASTCART_PRODEXC (SECUENCIA, ROWID_CASTCART_PRODUCTO_EXC, FECHA_CREACION_REGISTRO, TIPO_OPERACION,
    COD_CIA, COD_SECC, COD_RAMO, ESTADO, FECHA_CREACION, USUARIO_CREACION, FECHA_MODIFICACION, USUARIO_MODIFICACION)
    VALUES (SEQ_HISTORIAL_CASTCART_PRODEXC.NEXTVAL, :OLD.ROWID, SYSDATE, vl_Tipo_Operacion,
    :OLD.COD_CIA, :OLD.COD_SECC, :OLD.COD_RAMO, :OLD.ESTADO, :OLD.FECHA_CREACION, :OLD.USUARIO_CREACION, :OLD.FECHA_MODIFICACION, :OLD.USUARIO_MODIFICACION);
  End If;
End TR_BUDR_SIM_CAST_CART_PRODEXC;
/
