CREATE OR REPLACE TRIGGER TR_BUDR_SIM_CAST_CART_TERCEXC
/*
    Modifico : Rolphy Quintero - Asesoftware - Germán Muñoz
    fecha :  Agosto 25 de 2015 - Mantis 38430 - Proyecto Castigo de Cartera
    Desc : Creación del trigger. Auditar tabla SIM_CAST_CART_TERCERO_EXCLUIDO.
*/
  BEFORE UPDATE OR DELETE ON SIM_CAST_CART_TERCERO_EXCLUIDO FOR EACH ROW
Declare
  vl_Tipo_Operacion  SIM_HISTORIAL_CASTCART_TERCEXC.Tipo_Operacion%type;
Begin
  If Updating Then
    vl_Tipo_Operacion := 'A'; -- Actualización
    INSERT INTO SIM_HISTORIAL_CASTCART_TERCEXC (SECUENCIA, ROWID_CASTCART_TERC_EXCLUIDO, FECHA_CREACION_REGISTRO, TIPO_OPERACION,
    TDOC_TERCERO, NRO_DOCUMTO, ESTADO, FECHA_CREACION, USUARIO_CREACION, FECHA_MODIFICACION, USUARIO_MODIFICACION)
    VALUES (SEQ_HISTORIAL_CASTCART_TERCEXC.NEXTVAL, :NEW.ROWID, SYSDATE, vl_Tipo_Operacion, :NEW.TDOC_TERCERO,
    :NEW.NRO_DOCUMTO, :NEW.ESTADO, :NEW.FECHA_CREACION, :NEW.USUARIO_CREACION, :NEW.FECHA_MODIFICACION, :NEW.USUARIO_MODIFICACION);
  Elsif Deleting Then
    vl_Tipo_Operacion := 'B'; -- Borrado
    INSERT INTO SIM_HISTORIAL_CASTCART_TERCEXC (SECUENCIA, ROWID_CASTCART_TERC_EXCLUIDO, FECHA_CREACION_REGISTRO, TIPO_OPERACION,
    TDOC_TERCERO, NRO_DOCUMTO, ESTADO, FECHA_CREACION, USUARIO_CREACION, FECHA_MODIFICACION, USUARIO_MODIFICACION)
    VALUES (SEQ_HISTORIAL_CASTCART_TERCEXC.NEXTVAL, :OLD.ROWID, SYSDATE, vl_Tipo_Operacion, :OLD.TDOC_TERCERO,
    :OLD.NRO_DOCUMTO, :OLD.ESTADO, :OLD.FECHA_CREACION, :OLD.USUARIO_CREACION, :OLD.FECHA_MODIFICACION, :OLD.USUARIO_MODIFICACION);
  End If;
End TR_BUDR_SIM_CAST_CART_TERCEXC;
/
