CREATE OR REPLACE TRIGGER TR_BIR_SIM_CU_LOGEXPEDICION
BEFORE INSERT 
ON SIM_CU_LOGEXPEDICION
FOR EACH ROW
BEGIN 
    SELECT SEC_SIM_CU_LOGEXPEDICION.NEXTVAL INTO :NEW.SECUENCIA FROM DUAL;
END TR_BIR_SIM_CU_LOGEXPEDICION;
/
