CREATE OR REPLACE TRIGGER TRG_SEC_SIM_PARAM_AGENTECIUDAD
  BEFORE INSERT ON SIM_PARAM_AGENTE_CIUDAD
  FOR EACH ROW
DECLARE
  -- LOCAL VARIABLES HERE
  V_SECUENCIA NUMBER(17) := 0;
BEGIN
  BEGIN
    SELECT SEC_SIM_PARAM_AGENTE_CIUDAD.NEXTVAL INTO V_SECUENCIA FROM DUAL;
  END;
  :NEW.SECUENCIA := V_SECUENCIA;
END TRG_SEC_SIM_PARAM_AGENTECIUDAD;
/
