CREATE OR REPLACE TRIGGER TRG_SIM_INDEMNIZACION
  BEFORE INSERT ON  SIM_INDEMNIZACION
  FOR EACH ROW
DECLARE
  V_SECUENCIA NUMBER(17) := 0;
BEGIN
  BEGIN
    SELECT SEC_SIM_INDEMNIZACION.NEXTVAL INTO V_SECUENCIA FROM DUAL;
  END;
   :NEW.SECUENCIA := V_SECUENCIA;
END TRG_SIM_INDEMNIZACION;
/
