CREATE OR REPLACE TRIGGER TRG_SIM_PRODUCTOS_HIST_AIUD
  AFTER INSERT OR UPDATE OR DELETE ON sim_productos
  FOR EACH ROW
DECLARE
  vproceso VARCHAR2(25);
  vusuario VARCHAR2(25);
  vip VARCHAR2(25);

BEGIN
  BEGIN
    SELECT SYS_CONTEXT ('USERENV', 'IP_ADDRESS')
    INTO vip
    FROM DUAL;

    SELECT SYS_CONTEXT('USERENV', 'OS_USER')
    INTO vusuario
    FROM DUAL;
  END;

  IF inserting THEN
    vproceso := 'REGISTRO CREADO';
    INSERT INTO
  sim_productos_hist (ID_PRODUCTO,COD_PRODUCTO,ABREV_PRODUCTO,NOM_PRODUCTO,COD_CIA,COD_SECC,
                      ESTADO,USUARIO_CREACION,FECHA_CREACION,FECHA_ALTA,CLAU_ANEX,MCA_TXT_FIJO,
                      MCA_TXT_ASOC,MCA_END_TEMP,MCA_FACTURA,COD_TRATAMIENTO,MCA_MULTIRAMO,
                      MCA_PERIODO_FACT,MCA_FINAN,MCA_MANUAL,MCA_PENSION,MCA_GENERA_CARNET,
                      MCA_IMPRESION_WEB,MCA_BANCASEGUROS,USUARIO_MODIFICACION,FECHA_MODIFICACION,
                      MCA_POLIZA_PPAL,DESC_PRODUCTO,NOMBRE_LOGO,MCA_RENOVACION,MCA_RENOVACION_LINEA,
                      MCA_FACTURA_INFORMADA,MCA_FACTURA_DEBITO,MCA_FACTURA_LIBRANZA,MCA_ANULA_DIARIA,
                      MCA_ANULA_MENSUAL,MCA_VISUALIZA_TEXTOS,FEC_INICIO_IMPRESION_DOC1,
                      MCA_COORDENADA_SINI,POLIZA_ELECTRONICA,CONTABILIZA_EMISION,
                      CONTABILIZA_LIBRANZA,CONTABILIZA_DEBITO,DIAS_VIGENCIA_COTIZA_EO,
                      DIAS_VIGENCIA_COTIZA_RE,MANEJA_CUMULO,CUMULO_TEMPORAL,
                      VIGENCIA_COBERTURAS,GENERA_POL_HIJAS_AUT,MCA_MENSAJERIA,
                      MCA_POL_PPAL,USUARIO_PROCESO,IP_USUARIO,FECHA_PROCESO,PROCESO,
                      MCA_IMPRESION,MCA_CONSULTA_BANCASEGUROS)
  VALUES (:NEW.ID_PRODUCTO,:NEW.COD_PRODUCTO,:NEW.ABREV_PRODUCTO,:NEW.NOM_PRODUCTO,:NEW.COD_CIA,:NEW.COD_SECC,
          :NEW.ESTADO,:NEW.USUARIO_CREACION,:NEW.FECHA_CREACION,:NEW.FECHA_ALTA,:NEW.CLAU_ANEX,:NEW.MCA_TXT_FIJO,
          :NEW.MCA_TXT_ASOC,:NEW.MCA_END_TEMP,:NEW.MCA_FACTURA,:NEW.COD_TRATAMIENTO,:NEW.MCA_MULTIRAMO,
          :NEW.MCA_PERIODO_FACT,:NEW.MCA_FINAN,:NEW.MCA_MANUAL,:NEW.MCA_PENSION,:NEW.MCA_GENERA_CARNET,
          :NEW.MCA_IMPRESION_WEB,:NEW.MCA_BANCASEGUROS,:NEW.USUARIO_MODIFICACION,:NEW.FECHA_MODIFICACION,
          :NEW.MCA_POLIZA_PPAL,:NEW.DESC_PRODUCTO,:NEW.NOMBRE_LOGO,:NEW.MCA_RENOVACION,:NEW.MCA_RENOVACION_LINEA,
          :NEW.MCA_FACTURA_INFORMADA,:NEW.MCA_FACTURA_DEBITO,:NEW.MCA_FACTURA_LIBRANZA,:NEW.MCA_ANULA_DIARIA,
          :NEW.MCA_ANULA_MENSUAL,:NEW.MCA_VISUALIZA_TEXTOS,:NEW.FEC_INICIO_IMPRESION_DOC1,
          :NEW.MCA_COORDENADA_SINI,:NEW.POLIZA_ELECTRONICA,:NEW.CONTABILIZA_EMISION,
          :NEW.CONTABILIZA_LIBRANZA,:NEW.CONTABILIZA_DEBITO,:NEW.DIAS_VIGENCIA_COTIZA_EO,
          :NEW.DIAS_VIGENCIA_COTIZA_RE,:NEW.MANEJA_CUMULO,:NEW.CUMULO_TEMPORAL,
          :NEW.VIGENCIA_COBERTURAS,:NEW.GENERA_POL_HIJAS_AUT,:NEW.MCA_MENSAJERIA,
          :NEW.MCA_POL_PPAL,vusuario,vip,SYSDATE,vproceso,
          :NEW.MCA_IMPRESION,:NEW.MCA_CONSULTA_BANCASEGUROS);
  ELSIF deleting THEN
    vproceso := 'REGISTRO BORRADO';
    INSERT INTO
  sim_productos_hist (ID_PRODUCTO,COD_PRODUCTO,ABREV_PRODUCTO,NOM_PRODUCTO,COD_CIA,COD_SECC,
                      ESTADO,USUARIO_CREACION,FECHA_CREACION,FECHA_ALTA,CLAU_ANEX,MCA_TXT_FIJO,
                      MCA_TXT_ASOC,MCA_END_TEMP,MCA_FACTURA,COD_TRATAMIENTO,MCA_MULTIRAMO,
                      MCA_PERIODO_FACT,MCA_FINAN,MCA_MANUAL,MCA_PENSION,MCA_GENERA_CARNET,
                      MCA_IMPRESION_WEB,MCA_BANCASEGUROS,USUARIO_MODIFICACION,FECHA_MODIFICACION,
                      MCA_POLIZA_PPAL,DESC_PRODUCTO,NOMBRE_LOGO,MCA_RENOVACION,MCA_RENOVACION_LINEA,
                      MCA_FACTURA_INFORMADA,MCA_FACTURA_DEBITO,MCA_FACTURA_LIBRANZA,MCA_ANULA_DIARIA,
                      MCA_ANULA_MENSUAL,MCA_VISUALIZA_TEXTOS,FEC_INICIO_IMPRESION_DOC1,
                      MCA_COORDENADA_SINI,POLIZA_ELECTRONICA,CONTABILIZA_EMISION,
                      CONTABILIZA_LIBRANZA,CONTABILIZA_DEBITO,DIAS_VIGENCIA_COTIZA_EO,
                      DIAS_VIGENCIA_COTIZA_RE,MANEJA_CUMULO,CUMULO_TEMPORAL,
                      VIGENCIA_COBERTURAS,GENERA_POL_HIJAS_AUT,MCA_MENSAJERIA,
                      MCA_POL_PPAL,USUARIO_PROCESO,IP_USUARIO,FECHA_PROCESO,PROCESO,
                      MCA_IMPRESION,MCA_CONSULTA_BANCASEGUROS)
  VALUES (:OLD.ID_PRODUCTO,:OLD.COD_PRODUCTO,:OLD.ABREV_PRODUCTO,:OLD.NOM_PRODUCTO,:OLD.COD_CIA,:OLD.COD_SECC,
          :OLD.ESTADO,:OLD.USUARIO_CREACION,:OLD.FECHA_CREACION,:OLD.FECHA_ALTA,:OLD.CLAU_ANEX,:OLD.MCA_TXT_FIJO,
          :OLD.MCA_TXT_ASOC,:OLD.MCA_END_TEMP,:OLD.MCA_FACTURA,:OLD.COD_TRATAMIENTO,:OLD.MCA_MULTIRAMO,
          :OLD.MCA_PERIODO_FACT,:OLD.MCA_FINAN,:OLD.MCA_MANUAL,:OLD.MCA_PENSION,:OLD.MCA_GENERA_CARNET,
          :OLD.MCA_IMPRESION_WEB,:OLD.MCA_BANCASEGUROS,:OLD.USUARIO_MODIFICACION,:OLD.FECHA_MODIFICACION,
          :OLD.MCA_POLIZA_PPAL,:OLD.DESC_PRODUCTO,:OLD.NOMBRE_LOGO,:OLD.MCA_RENOVACION,:OLD.MCA_RENOVACION_LINEA,
          :OLD.MCA_FACTURA_INFORMADA,:OLD.MCA_FACTURA_DEBITO,:OLD.MCA_FACTURA_LIBRANZA,:OLD.MCA_ANULA_DIARIA,
          :OLD.MCA_ANULA_MENSUAL,:OLD.MCA_VISUALIZA_TEXTOS,:OLD.FEC_INICIO_IMPRESION_DOC1,
          :OLD.MCA_COORDENADA_SINI,:OLD.POLIZA_ELECTRONICA,:OLD.CONTABILIZA_EMISION,
          :OLD.CONTABILIZA_LIBRANZA,:OLD.CONTABILIZA_DEBITO,:OLD.DIAS_VIGENCIA_COTIZA_EO,
          :OLD.DIAS_VIGENCIA_COTIZA_RE,:OLD.MANEJA_CUMULO,:OLD.CUMULO_TEMPORAL,
          :OLD.VIGENCIA_COBERTURAS,:OLD.GENERA_POL_HIJAS_AUT,:OLD.MCA_MENSAJERIA,
          :OLD.MCA_POL_PPAL,vusuario,vip,SYSDATE,vproceso,
          :OLD.MCA_IMPRESION,:OLD.MCA_CONSULTA_BANCASEGUROS);
  ELSE
    vproceso := 'REGISTRO ACTUALIZADO';
  INSERT INTO
  sim_productos_hist (ID_PRODUCTO,COD_PRODUCTO,ABREV_PRODUCTO,NOM_PRODUCTO,COD_CIA,COD_SECC,
                      ESTADO,USUARIO_CREACION,FECHA_CREACION,FECHA_ALTA,CLAU_ANEX,MCA_TXT_FIJO,
                      MCA_TXT_ASOC,MCA_END_TEMP,MCA_FACTURA,COD_TRATAMIENTO,MCA_MULTIRAMO,
                      MCA_PERIODO_FACT,MCA_FINAN,MCA_MANUAL,MCA_PENSION,MCA_GENERA_CARNET,
                      MCA_IMPRESION_WEB,MCA_BANCASEGUROS,USUARIO_MODIFICACION,FECHA_MODIFICACION,
                      MCA_POLIZA_PPAL,DESC_PRODUCTO,NOMBRE_LOGO,MCA_RENOVACION,MCA_RENOVACION_LINEA,
                      MCA_FACTURA_INFORMADA,MCA_FACTURA_DEBITO,MCA_FACTURA_LIBRANZA,MCA_ANULA_DIARIA,
                      MCA_ANULA_MENSUAL,MCA_VISUALIZA_TEXTOS,FEC_INICIO_IMPRESION_DOC1,
                      MCA_COORDENADA_SINI,POLIZA_ELECTRONICA,CONTABILIZA_EMISION,
                      CONTABILIZA_LIBRANZA,CONTABILIZA_DEBITO,DIAS_VIGENCIA_COTIZA_EO,
                      DIAS_VIGENCIA_COTIZA_RE,MANEJA_CUMULO,CUMULO_TEMPORAL,
                      VIGENCIA_COBERTURAS,GENERA_POL_HIJAS_AUT,MCA_MENSAJERIA,
                      MCA_POL_PPAL,USUARIO_PROCESO,IP_USUARIO,FECHA_PROCESO,PROCESO,
                      MCA_IMPRESION,MCA_CONSULTA_BANCASEGUROS)
  VALUES (:OLD.ID_PRODUCTO,:OLD.COD_PRODUCTO,:OLD.ABREV_PRODUCTO,:OLD.NOM_PRODUCTO,:OLD.COD_CIA,:OLD.COD_SECC,
          :OLD.ESTADO,:OLD.USUARIO_CREACION,:OLD.FECHA_CREACION,:OLD.FECHA_ALTA,:OLD.CLAU_ANEX,:OLD.MCA_TXT_FIJO,
          :OLD.MCA_TXT_ASOC,:OLD.MCA_END_TEMP,:OLD.MCA_FACTURA,:OLD.COD_TRATAMIENTO,:OLD.MCA_MULTIRAMO,
          :OLD.MCA_PERIODO_FACT,:OLD.MCA_FINAN,:OLD.MCA_MANUAL,:OLD.MCA_PENSION,:OLD.MCA_GENERA_CARNET,
          :OLD.MCA_IMPRESION_WEB,:OLD.MCA_BANCASEGUROS,:OLD.USUARIO_MODIFICACION,:OLD.FECHA_MODIFICACION,
          :OLD.MCA_POLIZA_PPAL,:OLD.DESC_PRODUCTO,:OLD.NOMBRE_LOGO,:OLD.MCA_RENOVACION,:OLD.MCA_RENOVACION_LINEA,
          :OLD.MCA_FACTURA_INFORMADA,:OLD.MCA_FACTURA_DEBITO,:OLD.MCA_FACTURA_LIBRANZA,:OLD.MCA_ANULA_DIARIA,
          :OLD.MCA_ANULA_MENSUAL,:OLD.MCA_VISUALIZA_TEXTOS,:OLD.FEC_INICIO_IMPRESION_DOC1,
          :OLD.MCA_COORDENADA_SINI,:OLD.POLIZA_ELECTRONICA,:OLD.CONTABILIZA_EMISION,
          :OLD.CONTABILIZA_LIBRANZA,:OLD.CONTABILIZA_DEBITO,:OLD.DIAS_VIGENCIA_COTIZA_EO,
          :OLD.DIAS_VIGENCIA_COTIZA_RE,:OLD.MANEJA_CUMULO,:OLD.CUMULO_TEMPORAL,
          :OLD.VIGENCIA_COBERTURAS,:OLD.GENERA_POL_HIJAS_AUT,:OLD.MCA_MENSAJERIA,
          :OLD.MCA_POL_PPAL,vusuario,vip,SYSDATE,vproceso,
          :OLD.MCA_IMPRESION,:OLD.MCA_CONSULTA_BANCASEGUROS);
  END IF;

END TRG_SIM_PRODUCTOS_HIST_AIUD;
/
