CREATE OR REPLACE TRIGGER C8500210_UPD_ESTADO
  BEFORE UPDATE ON C8500210
  FOR EACH ROW
BEGIN
  IF UPPER(:NEW.ESTADO) = 'I' THEN
    :NEW.FECHA_BAJA := SYSDATE;
  ELSE IF UPPER(:NEW.ESTADO) = 'A' THEN
        :NEW.FECHA_BAJA := NULL;
    END IF;
  END IF;
END;
/
