CREATE OR REPLACE TRIGGER TRG_UID_C2990019 BEFORE insert or update or delete on C2990019
  for each row
Declare
  v_operacion char(1);
  vl_secuencia number := 0;
Begin
   IF INSERTING  THEN
     v_operacion := 'I';
     IF :new.ID_SECUENCIA IS NULL THEN
       vl_secuencia := SEQ_c2990019.NEXTVAL;
       :new.ID_SECUENCIA := vl_secuencia;     
     END IF;
   END IF;
   IF  UPDATING THEN
     v_operacion := 'A';
   END IF;
   IF  DELETING THEN
     v_operacion := 'B';
   END IF;
   IF INSERTING OR UPDATING THEN
     INSERT INTO C2990019_JN(OPERACION, USUARIO_JN, FECHA_JN, ID_SECUENCIA, COD_CIA, 
       COD_SECC, COD_RAMO, COD_SUBPRODUCTO, OPCION, ALTERNATIVA, 
       COD_COB, COD_ASISTENCIA, PERIODO_CARENCIA, NRO_EVENTOS, DESC_EVENTOS, 
       ALCANCE_EVENTO, AMBITO_TERRITORIAL, FECHA_VIGENCIA, FECHA_BAJA, USUARIO_CREACION, 
       FECHA_CREACION, USUARIO_MODIFICA, FECHA_MODIFICA, NIT_PROVEEDOR, INTERMEDIARIO)
     VALUES (v_operacion, USER, SYSDATE, :NEW.ID_SECUENCIA, :NEW.COD_CIA, 
       :NEW.COD_SECC, :NEW.COD_RAMO, :NEW.COD_SUBPRODUCTO, :NEW.OPCION, :NEW.ALTERNATIVA, 
       :NEW.COD_COB, :NEW.COD_ASISTENCIA, :NEW.PERIODO_CARENCIA, :NEW.NRO_EVENTOS, :NEW.DESC_EVENTOS, 
       :NEW.ALCANCE_EVENTO, :NEW.AMBITO_TERRITORIAL, :NEW.FECHA_VIGENCIA, :NEW.FECHA_BAJA, :NEW.USUARIO_CREACION, 
       :NEW.FECHA_CREACION, :NEW.USUARIO_MODIFICA, :NEW.FECHA_MODIFICA, :NEW.NIT_PROVEEDOR, :NEW.INTERMEDIARIO);
    END IF;
   IF DELETING THEN
     INSERT INTO C2990019_JN(OPERACION, USUARIO_JN, FECHA_JN, ID_SECUENCIA, COD_CIA, 
       COD_SECC, COD_RAMO, COD_SUBPRODUCTO, OPCION, ALTERNATIVA, 
       COD_COB, COD_ASISTENCIA, PERIODO_CARENCIA, NRO_EVENTOS, DESC_EVENTOS, 
       ALCANCE_EVENTO, AMBITO_TERRITORIAL, FECHA_VIGENCIA, FECHA_BAJA, USUARIO_CREACION, 
       FECHA_CREACION, USUARIO_MODIFICA, FECHA_MODIFICA, NIT_PROVEEDOR, INTERMEDIARIO)
     VALUES (v_operacion, USER, SYSDATE, :OLD.ID_SECUENCIA, :OLD.COD_CIA, 
       :OLD.COD_SECC, :OLD.COD_RAMO, :OLD.COD_SUBPRODUCTO, :NEW.OPCION, :OLD.ALTERNATIVA, 
       :OLD.COD_COB, :OLD.COD_ASISTENCIA, :OLD.PERIODO_CARENCIA, :OLD.NRO_EVENTOS, :OLD.DESC_EVENTOS, 
       :OLD.ALCANCE_EVENTO, :OLD.AMBITO_TERRITORIAL, :OLD.FECHA_VIGENCIA, :OLD.FECHA_BAJA, :OLD.USUARIO_CREACION, 
       :OLD.FECHA_CREACION, :OLD.USUARIO_MODIFICA, :OLD.FECHA_MODIFICA, :OLD.NIT_PROVEEDOR, :OLD.INTERMEDIARIO);
    END IF;
End TRG_UID_C2990019;
/
