CREATE OR REPLACE TRIGGER "TRG_HIST_DEFINICION" AFTER
  INSERT OR
  UPDATE ON IND_REGLAS_DEFINICION FOR EACH ROW
BEGIN
  INSERT
  INTO OPS$PUMA.SIM_DEFINICION_REGLAS_JN
    (
      ID,
      PRODUCTO,
      SCORE_RIESGO,
      CLV,
      COBERTURA ,
      CAUSA,
      CONSECUENCIA,
      MODELO_RIESGO_PRETENSION,
      RESULTADO_ENCUESTA,
      RESULTADO_EVIDENCIA,
      CLASIFICACION_CASO_CODE,
      MOTOR_DEFINICION_CASO,
      DEFINICION_CASO_CODE,
      COMPANY,
      SECCION,
      FECHA_BAJA,
      FECHA_MODIFICACION,
      USUARIO_MODIFICACION
    )
    VALUES
    (
      :NEW.ID,
      :NEW.PRODUCTO,
      :NEW.SCORE_RIESGO,
      :NEW.CLV,
      :NEW.COBERTURA ,
      :NEW.CAUSA,
      :NEW.CONSECUENCIA,
      :NEW.MODELO_RIESGO_PRETENSION,
      :NEW.RESULTADO_ENCUESTA,
      :NEW.RESULTADO_EVIDENCIA,
      :NEW.CLASIFICACION_CASO_CODE,
      :NEW.MOTOR_DEFINICION_CASO,
      :NEW.DEFINICION_CASO_CODE,
      :NEW.COMPANY,
      :NEW.SECCION,
      :NEW.FECHA_BAJA,
      :NEW.FECHA_CREACION,
      :NEW.USUARIO_CREACION
    );
END TRG_HIST_DEFINICION;
/
