CREATE OR REPLACE TRIGGER TRG_SIM_TMP_ASEG_NUI
BEFORE insert OR UPDATE ON sim_tmp_asegurados
  FOR EACH ROW
begin
  IF :NEW.COD_CAMPO = 'CODIGO_NUI' THEN
    :NEW.VALOR_CAMPO := TRIM(:NEW.VALOR_CAMPO);
  END IF;
end TRG_SIM_TMP_ASEG_NUI;
/
