CREATE OR REPLACE TRIGGER "TRG_SEC_SIM_PRODUCTO_MADRE"
  BEFORE INSERT ON SIM_PRODUCTO_MADRE
  FOR EACH ROW
BEGIN

  :NEW.PRM_CODIGO := SEC_SIM_PRODUCTO_MADRE.NEXTVAL;

END TRG_SEC_SIM_PRODUCTO_MADRE;
/
