CREATE OR REPLACE TRIGGER TRG_SEC_SIM_PARAMETROS_TARIFA
  BEFORE INSERT ON SIM_PARAMETROS_TARIFACION
  FOR EACH ROW
DECLARE
  V_SECUENCIA NUMBER(15) := 0;
BEGIN
  BEGIN
     SELECT SEC_SIM_PARAMETROS_TARIFACION.NEXTVAL
     INTO   V_SECUENCIA
     FROM   DUAL;
  END;
  :NEW.SECUENCIA := V_SECUENCIA;
END TRG_SEC_SIM_PARAMETROS_TARIFA;
/
