CREATE OR REPLACE TRIGGER TRG_BI_SIM_CU_PARAM_DPTO_REST
  BEFORE INSERT ON SIM_CU_PARAM_DPTO_REST
  FOR EACH ROW
DECLARE
  V_SECUENCIA NUMBER(17) := 0;
BEGIN
  BEGIN
    SELECT SEC_SIM_CU_PARAM_DPTO_REST.NEXTVAL INTO V_SECUENCIA FROM DUAL;
  END;

  :NEW.SECUENCIA := V_SECUENCIA;

END TRG_SIM_CU_PARAM_DPTO_REST;
/
