CREATE OR REPLACE TRIGGER TRG_SIM_REGLAS_TRANSICION 
  BEFORE INSERT ON  SIM_REGLAS_TRANSICION 
  FOR EACH ROW
DECLARE
  V_SECUENCIA NUMBER(17) := 0;
BEGIN
  BEGIN
    SELECT SEC_SIM_REGLAS_TRANSICION.NEXTVAL INTO V_SECUENCIA FROM DUAL;
  END;
   :NEW.SECUENCIA := V_SECUENCIA;
END  TRG_SIM_REGLAS_TRANSICION;
/
