CREATE OR REPLACE TRIGGER TRG_A502_AUDITORIA_AREA_FE
  AFTER INSERT OR UPDATE ON C9999909
  FOR EACH ROW
DECLARE
V_OPE 		VARCHAR2 (6)	:= NULL;
V_OLD		VARCHAR2 (40) 	:= NULL;
V_NEW		VARCHAR2 (40)	:= NULL;
V_COL		VARCHAR2 (60)	:= NULL;
VCA_SQL		VARCHAR2 (4000)	:= NULL;
BEGIN
	IF 		UPDATING  THEN V_OPE := 'UPDATE';
	ELSIF 	INSERTING THEN V_OPE := 'INSERT';
	ELSE  	V_OPE := 'ERROR';
	END IF;

	IF :NEW.COD_TAB = 'A502_FACTURA_E' AND :NEW.COD_CAMPO = 'AREA' AND :NEW.COD_RAMO = 999 AND :NEW.COD_CIA = 99 AND :NEW.COD_SECC = 1 THEN

		VCA_SQL := 'PROVEEDOR = ' || :NEW.CODIGO || ', AREA = ' ||
               :NEW.CODIGO1 || ', TIPO DOC PROVEEDOR = ' || :NEW.DAT_OBS ||
			   ', COMPANIA BOLIVAR = ' || :NEW.DAT_NUM || ', FECHA CREACION = ' ||
               :NEW.FECHA_ALTA || ', FECHA ACTIVACION = ' || :NEW.FECHA_ACT ||
			   ', USUARIO = ' || :NEW.USUARIO || ', SECUENCIA = ' ||
               :NEW.SECUENCIA;

		IF UPDATING OR INSERTING THEN
			IF UPDATING THEN
				IF :NEW.CODIGO1 <> :OLD.CODIGO1 THEN 
					V_COL := 'AREA';
					V_OLD := TO_CHAR(:OLD.CODIGO1);
					V_NEW := TO_CHAR(:NEW.CODIGO1);
				ELSIF :NEW.FECHA_ACT <> :OLD.FECHA_ACT THEN 
					V_COL := 'FECHA DE ACTIVACION' ;
					V_OLD := TO_CHAR(:OLD.FECHA_ACT, 'DD/MM/YY');
					V_NEW := TO_CHAR(:NEW.FECHA_ACT, 'DD/MM/YY');
				ELSIF :NEW.FECHA_BAJA <> :OLD.FECHA_BAJA THEN 
					V_COL := 'FECHA DE ELIMINACION' ;
					V_OLD := TO_CHAR(:OLD.FECHA_BAJA, 'DD/MM/YY');
					V_NEW := TO_CHAR(:NEW.FECHA_BAJA, 'DD/MM/YY');
				END IF;
			ELSE 
				V_COL := 'AREA';
				V_NEW := TO_CHAR(:NEW.CODIGO1);
			END IF;
			INSERT INTO A502_AUDITORIA_AREA_FACT (
				ID_AUDITORIA,
				COD_BENEF,
				TDOC_TERCERO,
				COMANDO,
				VALOR_OLD,
				VALOR_NEW,
				USUARIO,
				FECHA,
				COLUMNA,
				SECUENCIA,
				SQL)
		    VALUES(
				NULL,
				:NEW.CODIGO,
				:NEW.DAT_OBS,
				V_OPE,
				V_OLD,
				V_NEW,
				:NEW.USUARIO,
				SYSDATE,
				V_COL,
				:NEW.SECUENCIA,
				substr(vca_sql, 1, 4000)
			);
		END IF;
    END IF;
END TRG_A502_AUDITORIA_AREA_FE;
/
