CREATE OR REPLACE TRIGGER trg_cambia_estado_solicitud
AFTER INSERT OR UPDATE OF estado_solicitud ON EMI_SOLICITUD_POLIZA
FOR EACH ROW
DECLARE

BEGIN
 IF :NEW.ESTADO_SOLICITUD <> :OLD.ESTADO_SOLICITUD THEN
  IF :NEW.OBSERVACION_USUARIO IS NOT NULL THEN
   IF :OLD.OBSERVACION_USUARIO IS NULL OR (:OLD.OBSERVACION_USUARIO IS NOT NULL AND (:OLD.OBSERVACION_USUARIO <> :NEW.OBSERVACION_USUARIO)) THEN


   INSERT INTO EMI_HISTORICO_SOLICITUD_POLIZA
         (NUMERO_SOLICITUD,
		  TIPO_DOCUMENTO,
		  NUMERO_DOCUMENTO,
		  TOMADOR_ES_ASEGURADO,
		  FECHA_SOLICITUD,
		  CLAVE_INTERMEDIARIO,
		  LOCALIDAD_RADICACION,
		  TIPO_NEGOCIO,
		  CODIGO_COMPANIA,
		  CODIGO_RAMO,
		  CODIGO_PRODUCTO,
		  NEGOCIO_REFERIDO,
		  TIENE_DESCUENTO_COMERCIAL,
		  CODIGO_DESCUENTO_COMERCIAL,
		  PORC_DESCTO_COMERCIAL,
		  PORC_DESCTO_COMERCIAL_1,
		  PORC_DESCTO_COMERCIAL_2,
		  NEGOCIO_TIENE_FIDUCIA,
		  NUMERO_CONTRATO_FIDUCIA,
		  NIT_EMPRESA_FIDUCIA,
		  NUM_CONSECUTIVO_STELLENT,
		  ESTADO_SOLICITUD,
		  OBSERVACION_USUARIO,
		  OBSERVACION_ESTADO,
		  NUMERO_POLIZA,
		  FECHA_EMISION,
		  FECHA_VIGENCIA,
		  COMISION_PACTADA,
		  FECHA_ORIGEN,
		  ENT_IAPA,
		  CODRIE_CONJUNT,
		  USUARIO_CREACION,
		  USUARIO_TRANSACCION,
		  FECHA_TRANSACCION,
		  SUMA_ASEGURADA,
		  MUERTE_ACCIDENTAL,
		  SUMA_ASEG_MUERTE_ACC,
		  QUE_PLAN_DESEA_TOMAR,
		  ESTE_SEGURO_LO_TOMA_PARA,
		  TIPO_INDEMNIZACION
		 )
   VALUES(:NEW.NUMERO_SOLICITUD,
		  :NEW.TIPO_DOCUMENTO,
		  :NEW.NUMERO_DOCUMENTO,
		  :NEW.TOMADOR_ES_ASEGURADO,
		  :NEW.FECHA_SOLICITUD,
		  :NEW.CLAVE_INTERMEDIARIO,
		  :NEW.LOCALIDAD_RADICACION,
		  :NEW.TIPO_NEGOCIO,
		  :NEW.CODIGO_COMPANIA,
		  :NEW.CODIGO_RAMO,
		  :NEW.CODIGO_PRODUCTO,
		  :NEW.NEGOCIO_REFERIDO,
		  :NEW.TIENE_DESCUENTO_COMERCIAL,
		  :NEW.CODIGO_DESCUENTO_COMERCIAL,
		  :NEW.PORC_DESCTO_COMERCIAL,
		  :NEW.PORC_DESCTO_COMERCIAL_1,
		  :NEW.PORC_DESCTO_COMERCIAL_2,
		  :NEW.NEGOCIO_TIENE_FIDUCIA,
		  :NEW.NUMERO_CONTRATO_FIDUCIA,
		  :NEW.NIT_EMPRESA_FIDUCIA,
		  :NEW.NUM_CONSECUTIVO_STELLENT,
		  :NEW.ESTADO_SOLICITUD,
		  :NEW.OBSERVACION_USUARIO,
		  :NEW.OBSERVACION_ESTADO,
		  :NEW.NUMERO_POLIZA,
		  :NEW.FECHA_EMISION,
		  :NEW.FECHA_VIGENCIA,
		  :NEW.COMISION_PACTADA,
		  :NEW.FECHA_ORIGEN,
		  :NEW.ENT_IAPA,
		  :NEW.CODRIE_CONJUNT,
		  :NEW.USUARIO_CREACION,
		  :NEW.USUARIO_TRANSACCION,
		  :NEW.FECHA_TRANSACCION,
		  :NEW.SUMA_ASEGURADA,
		  :NEW.MUERTE_ACCIDENTAL,
		  :NEW.SUMA_ASEG_MUERTE_ACC,
		  :NEW.QUE_PLAN_DESEA_TOMAR,
		  :NEW.ESTE_SEGURO_LO_TOMA_PARA,
		  :NEW.TIPO_INDEMNIZACION
         );
   ELSE
    RAISE_APPLICATION_ERROR(-20105,'Es obligatorio escribir una observacion de cambio de estado');
   END IF;
  ELSE
    RAISE_APPLICATION_ERROR(-20106,'La observacion de cambio de estado no puede estar vacia');
  END IF;
 END IF;
END;
/
