CREATE OR REPLACE TRIGGER TRG_A2000040_CODAGRUP
BEFORE INSERT ON A2000040
FOR EACH ROW
BEGIN
	IF NVL(:NEW.COD_AGRUP_CONT, 0) = 0 THEN
		BEGIN
			SELECT B.COD_AGRUP_CONT
				INTO :NEW.COD_AGRUP_CONT
				FROM A1002100 B,
						 A2000030 Z
			 WHERE B.COD_CIA = Z.COD_CIA
				 AND B.COD_COB = :NEW.COD_COB
				 AND B.COD_RAMO = Z.COD_RAMO
				 AND Z.NUM_SECU_POL = :NEW.NUM_SECU_POL
				 AND Z.NUM_END = :NEW.NUM_END;
		EXCEPTION
			WHEN NO_DATA_FOUND THEN
				NULL;
		END;
	END IF;
END;
/
