CREATE OR REPLACE TRIGGER TRG_C2999300
  before update or delete on c2999300
  for each row
declare
  -- local variables here
begin
  insert into c2999300_h
 (CIA_LIDER,RAMO_LIDER,POLIZA_LIDER,NUM_PROV_LIDER,NUM_SECU_POL_LIDER,NUM_END_LIDER,
  COD_RIES_LIDER,CIA_ANEXO,RAMO_ANEXO,POLIZA_ANEXO,NUM_SECU_POL_ANEXO,NUM_END_ANEXO,
  COD_RIES_ANEXO,MCA_PROVISORIA,NUM_PROV_ANEXO,FECHA_CREACION,PROCESO,MCA_COTIZACION,
  NUM_POL_COTIZ_LIDER,NUM_POL_COTIZ_ANEXO,SECCION_LIDER,SECCION_ANEXO, COD_USER,
  FECHA_OPERACION, OPERACION)
  VALUES
 (:OLD.CIA_LIDER,:OLD.RAMO_LIDER,:OLD.POLIZA_LIDER,:OLD.NUM_PROV_LIDER,:OLD.NUM_SECU_POL_LIDER,
  :OLD.NUM_END_LIDER,:OLD.COD_RIES_LIDER,:OLD.CIA_ANEXO,:OLD.RAMO_ANEXO,:OLD.POLIZA_ANEXO,
  :OLD.NUM_SECU_POL_ANEXO,:OLD.NUM_END_ANEXO, :OLD.COD_RIES_ANEXO,:OLD.MCA_PROVISORIA,
  :OLD.NUM_PROV_ANEXO,:OLD.FECHA_CREACION,:OLD.PROCESO,:OLD.MCA_COTIZACION,
  :OLD.NUM_POL_COTIZ_LIDER,:OLD.NUM_POL_COTIZ_ANEXO,:OLD.SECCION_LIDER,:OLD.SECCION_ANEXO,
  substr(USER,1,16) ,SYSDATE, 'D');
end TRG_C2999300;
/
