CREATE OR REPLACE TRIGGER TRG_HIST_EMI_REFERENCIAS
AFTER INSERT OR UPDATE ON EMI_REFERENCIAS_PERSONALES
FOR EACH ROW
DECLARE

BEGIN
   INSERT INTO EMI_HISTORICO_REFERENCIAS
         (NUMERO_SOLICITUD,
          CONSECUTIVO,
		  NOMBRE_COMPLETO,
		  TELEFONO,
		  USUARIO_CREACION,
		  FECHA_CREACION,
		  USUARIO_TRANSACCION,
		  FECHA_TRANSACCION
		 )
   VALUES(:NEW.NUMERO_SOLICITUD,
          :NEW.CONSECUTIVO,
		  :NEW.NOMBRE_COMPLETO,
		  :NEW.TELEFONO,
		  :NEW.USUARIO_CREACION,
		  :NEW.FECHA_CREACION,
		  :NEW.USUARIO_TRANSACCION,
		  :NEW.FECHA_TRANSACCION
         );
END;
/
