CREATE OR REPLACE TRIGGER TRG_EMI_ALARMA_MEDICAMENTOS
AFTER INSERT OR UPDATE ON EMI_MEDICAMENTO_ASEGURADO FOR EACH ROW
DECLARE

 VAR_MEDICAMENTO VARCHAR2(60);

BEGIN
 IF NVL(:NEW.COD_MED,0) <> NVL(:OLD.COD_MED,0)THEN
     SELECT EF.MEDICAMENTO
       INTO VAR_MEDICAMENTO
       FROM EMI_MEDICAMENTOS EF
      WHERE EF.CODIGO_MED = :NEW.COD_MED;

     UPDATE EMI_SOLICITUD_POLIZA
        SET OBSERVACION_USUARIO = OBSERVACION_USUARIO || ' -> '||:NEW.USUARIO_TRANSACCION||' Fecha: '||sysdate||' '|| ' ALARMA: '||VAR_MEDICAMENTO
      WHERE NUMERO_SOLICITUD = :NEW.NUMERO_SOLICITUD;
 END IF;

EXCEPTION WHEN OTHERS THEN
  RAISE_APPLICATION_ERROR(-20005,'Error Alarmas Med. '||SQLERRM);
END;
/
