CREATE OR REPLACE TRIGGER TRG_SEQ_CARGUE_PRE 
  BEFORE INSERT ON SIMAPI_CARGUE_PREDIAL
  FOR EACH ROW
DECLARE
  -- local variables here
  V_secuencia number(17) := 0;
BEGIN
  BEGIN
     SELECT SEQ_PREDIAL_CARGUE.Nextval
     INTO   V_secuencia
     FROM   dual;
  END;

  :new.ID_CARGUE_PREDIAL := V_secuencia;

END TRG_SEQ_CARGUE_PRE;
/
