CREATE OR REPLACE TRIGGER TRG_AU_EMI_CAMBIA_PRODUCTO
  after update of tipo_negocio on emi_solicitud_poliza
declare
  var_num_solicitud number;
  var_cod_riesgo number;

  var_row     ROWID;
  var_mensaje VARCHAR2(255);
  var_solicitud number;
  var_cambia_producto varchar2(1) := 'N';

begin

  BEGIN
  SELECT num_rowid, mensaje, numero_solicitud,codigo_riesgo
    INTO var_row,
         var_mensaje,
         var_solicitud,
         var_cod_riesgo
    FROM EMI_MUTATING
   WHERE table_name = 'EMI_SOLICITUD';

    var_cambia_producto := 'S';
  EXCEPTION WHEN NO_DATA_FOUND THEN
     var_cambia_producto := 'N';
  END;

 if var_cambia_producto = 'S' then

  --Cambio 04/08/2010 de algoritmo para creacion de consecutivo sin saltos en el sistema
  select TO_CHAR(SYSDATE, 'yymm') ||
         lpad(max(to_number(substr(numero_solicitud, 5, 8))) + 1,
              4,
              0)
    INTO VAR_NUM_SOLICITUD
    from emi_solicitud_poliza;


  INSERT INTO EMI_SOLICITUD_POLIZA
          (NUMERO_SOLICITUD, TIEMPO_LLAMADA, TIPO_DOCUMENTO, NUMERO_DOCUMENTO, TOMADOR_ES_ASEGURADO,
           FECHA_SOLICITUD, CLAVE_INTERMEDIARIO, LOCALIDAD_RADICACION, TIPO_NEGOCIO, CODIGO_RAMO,
           CODIGO_PRODUCTO, NEGOCIO_REFERIDO, TIENE_DESCUENTO_COMERCIAL, CODIGO_DESCUENTO_COMERCIAL,
           PORC_DESCTO_COMERCIAL, PORC_DESCTO_COMERCIAL_1, PORC_DESCTO_COMERCIAL_2, NEGOCIO_TIENE_FIDUCIA,
           NUMERO_CONTRATO_FIDUCIA, NIT_EMPRESA_FIDUCIA, NUM_CONSECUTIVO_STELLENT, ESTADO_SOLICITUD,
           OBSERVACION_USUARIO, FECHA_VIGENCIA, FECHA_ORIGEN, CODRIE_CONJUNT, ESTE_SEGURO_LO_TOMA_PARA,
           QUE_PLAN_DESEA_TOMAR, TIPO_INDEMNIZACION, SUMA_ASEGURADA, USUARIO_CREACION, USUARIO_TRANSACCION,
           FECHA_TRANSACCION, COMISION_PACTADA, ENT_IAPA, ENT_AXA, ENT_BEST,ASIST_BOLIVAR,extension,
           PORC_PARTICIPACION, MCA_LIDER, CLAVE_INTERMEDIARIO_2, LOCALIDAD_RADICACION_2,PORC_PARTICIPACION_2,
           MCA_LIDER_2, TIENE_SEGUNDA_CLAVE, CAMBIA_TOMADOR,TIPO_ENVIO,INTENCION_AHORRO,NUMERO_SIMASOL,ES_ONEROSO
           )
   SELECT  var_num_solicitud, TIEMPO_LLAMADA, TIPO_DOCUMENTO, NUMERO_DOCUMENTO, TOMADOR_ES_ASEGURADO,
           FECHA_SOLICITUD, CLAVE_INTERMEDIARIO, LOCALIDAD_RADICACION, 'I', 47,
           942, NEGOCIO_REFERIDO, TIENE_DESCUENTO_COMERCIAL, CODIGO_DESCUENTO_COMERCIAL,
           PORC_DESCTO_COMERCIAL, PORC_DESCTO_COMERCIAL_1, PORC_DESCTO_COMERCIAL_2, NEGOCIO_TIENE_FIDUCIA,
           NUMERO_CONTRATO_FIDUCIA, NIT_EMPRESA_FIDUCIA, NUM_CONSECUTIVO_STELLENT, 'PEN',
           ' SOLICITUD ORIGINAL No. '||var_solicitud ||' '||OBSERVACION_USUARIO, FECHA_VIGENCIA,
           FECHA_ORIGEN, CODRIE_CONJUNT, ESTE_SEGURO_LO_TOMA_PARA,QUE_PLAN_DESEA_TOMAR, TIPO_INDEMNIZACION,
           SUMA_ASEGURADA, USUARIO_CREACION, USUARIO_TRANSACCION,
           SYSDATE, COMISION_PACTADA, ENT_IAPA, ENT_AXA, ENT_BEST,ASIST_BOLIVAR,extension,
           PORC_PARTICIPACION, MCA_LIDER, CLAVE_INTERMEDIARIO_2,LOCALIDAD_RADICACION_2,PORC_PARTICIPACION_2,
           MCA_LIDER_2, TIENE_SEGUNDA_CLAVE, CAMBIA_TOMADOR,TIPO_ENVIO,INTENCION_AHORRO,NUMERO_SIMASOL,ES_ONEROSO
     FROM  EMI_SOLICITUD_POLIZA EP
    WHERE  EP.NUMERO_SOLICITUD = var_solicitud;

  --Se elimina el registro de clientes pues al ingresar la solicitud de la póliza se crea el cliente

        INSERT INTO EMI_DATOS_ASEGURADO
              (NUMERO_SOLICITUD,CODIGO_RIESGO,ENTIDAD_SEGURIDAD_SOCIAL,ES_ZURDO,
               NIVEL_DE_EDUCACION,VIDA_PROTEGIDA,LICENCIA_PILOTO,MANEJA_MOTOCICLETA,
               DEPORTES_ALTO_RIESGO,OTRO_DEPORTE_ALTO_RIESGO,PRACTICA_OTROS_DEPORTES,
               CUALES_DEPORTES,ACTIVIDADES_LICITAS,CONDENADO_PENALMENTE,SECUESTRADO,
               RESIDE_EXTERIOR,USUARIO_CREACION,FECHA_CREACION,USUARIO_TRANSACCION,
               FECHA_TRANSACCION,INDEMNIZACION_PREVIA,LABORES_FISCALIZACION,CUALES_LABORES,
               VIDA_ASEGURADA,CIA_PROTEGIDA,MONTO_PROTEGIDO,CIA_ASEGURADA,MONTO_ASEGURADO,
               CUAL_ANEXO,MONTO_ANEXO)
        SELECT  var_num_solicitud,CODIGO_RIESGO,ENTIDAD_SEGURIDAD_SOCIAL,ES_ZURDO,NIVEL_DE_EDUCACION,
                VIDA_PROTEGIDA,LICENCIA_PILOTO,MANEJA_MOTOCICLETA,DEPORTES_ALTO_RIESGO,
                OTRO_DEPORTE_ALTO_RIESGO,PRACTICA_OTROS_DEPORTES,CUALES_DEPORTES,
                ACTIVIDADES_LICITAS,CONDENADO_PENALMENTE,SECUESTRADO,RESIDE_EXTERIOR,
                USUARIO_CREACION,FECHA_CREACION,USUARIO_TRANSACCION,FECHA_TRANSACCION,
                INDEMNIZACION_PREVIA,LABORES_FISCALIZACION,CUALES_LABORES,VIDA_ASEGURADA,
                CIA_PROTEGIDA,MONTO_PROTEGIDO,CIA_ASEGURADA,MONTO_ASEGURADO,CUAL_ANEXO,MONTO_ANEXO
          FROM EMI_DATOS_ASEGURADO EA
         WHERE EA.CODIGO_RIESGO = var_cod_riesgo
           AND EA.NUMERO_SOLICITUD = var_solicitud;

      INSERT INTO EMI_AMPAROS_ADICIONALES
             (NUMERO_SOLICITUD,CODIGO_RIESGO,VIDA_RIESGO,DESMEMBRACION,SUMA_DESMEMBRACION,
              RENTA_MENSUAL_INCAPACIDAD,SUMA_RENTA_MENSUAL_INCAPACIDAD,GASTOS_MEDICOS,SUMA_GASTOS_MEDICOS,
              ENF_GRAVES_ANTIC_40,SUMA_ENF_GRAVES_ANTIC_40,INCAPACIDAD_TOTAL_PERMANENTE,SUMA_ITP,
              ENF_GRAVES_ANTIC_40_EXCL,SUMA_ENF_GRAVES_ANTIC_40_EXCL,ENF_GRAVES_ADIC_100,SUMA_ENF_GRAVES_ADIC_100,
              ENF_GRAVES_ADIC_100_EXCL,SUMA_ENF_GRAVES_ADIC_100_EXCL,EXONERACION_DE_PRIMAS,TOTAL_PRIMA_DE_RIESGO,
              OPCION_ASEG,USUARIO_CREACION,FECHA_CREACION,USUARIO_TRANSACCION,FECHA_TRANSACCION,
              MUERTE_ACCIDENTAL,SUMA_ASEG_MUERTE_ACC,ITP_SUMA_ADICIONAL,SUMA_ITP_SUMA_ADICIONAL,MUERTE_ACC_TRANSITO,
              SUMA_MUERTE_ACC_TRANSITO,INGRESO_EN_PESOS,RENTA_DIARIA_INCAPACIDAD,SUMA_RENTA_DIARIA_INCAPACIDAD,ES_ONEROSO
             )
      SELECT var_num_solicitud,CODIGO_RIESGO,VIDA_RIESGO,DESMEMBRACION,SUMA_DESMEMBRACION,
             RENTA_MENSUAL_INCAPACIDAD,SUMA_RENTA_MENSUAL_INCAPACIDAD,GASTOS_MEDICOS,SUMA_GASTOS_MEDICOS,
             ENF_GRAVES_ANTIC_40,SUMA_ENF_GRAVES_ANTIC_40,INCAPACIDAD_TOTAL_PERMANENTE,SUMA_ITP,
             ENF_GRAVES_ANTIC_40_EXCL,SUMA_ENF_GRAVES_ANTIC_40_EXCL,ENF_GRAVES_ADIC_100,SUMA_ENF_GRAVES_ADIC_100,
             ENF_GRAVES_ADIC_100_EXCL,SUMA_ENF_GRAVES_ADIC_100_EXCL,EXONERACION_DE_PRIMAS,TOTAL_PRIMA_DE_RIESGO,
             OPCION_ASEG,USUARIO_CREACION,FECHA_CREACION,USUARIO_TRANSACCION,FECHA_TRANSACCION,
             MUERTE_ACCIDENTAL,SUMA_ASEG_MUERTE_ACC,ITP_SUMA_ADICIONAL,SUMA_ITP_SUMA_ADICIONAL,MUERTE_ACC_TRANSITO,
             SUMA_MUERTE_ACC_TRANSITO,INGRESO_EN_PESOS,RENTA_DIARIA_INCAPACIDAD,SUMA_RENTA_DIARIA_INCAPACIDAD,ES_ONEROSO
        FROM EMI_AMPAROS_ADICIONALES EM
       WHERE EM.CODIGO_RIESGO = var_cod_riesgo
         AND EM.NUMERO_SOLICITUD = var_solicitud;


      INSERT INTO EMI_BENEFICIARIOS
             (NUMERO_SOLICITUD,CODIGO_RIESGO,CONSECUTIVO,TIPDOC_CODIGO,NUMERO_DOCUMENTO,PRIMER_NOMBRE,
              SEGUNDO_NOMBRE,PRIMER_APELLIDO,SEGUNDO_APELLIDO,PARENTESCO,CALIDAD,PORCENTAJE_PARTICIPACION,
              COSTO_EDUCATIVO_MENSUAL,ANOS_PENDIENTE_SECUN,COSTO_SEMESTRE_ACTUAL,ANOS_PROY_UNIV,GASTOS_EDUCATIVOS,
              PAGO_TOTAL,RENTA_MENSUAL,ANOS_PAGO,USUARIO_CREACION,FECHA_CREACION,USUARIO_TRANSACCION,
              FECHA_TRANSACCION
             )
      SELECT var_num_solicitud,CODIGO_RIESGO,CONSECUTIVO,TIPDOC_CODIGO,NUMERO_DOCUMENTO,PRIMER_NOMBRE,
             SEGUNDO_NOMBRE,PRIMER_APELLIDO,SEGUNDO_APELLIDO,PARENTESCO,CALIDAD,PORCENTAJE_PARTICIPACION,
             COSTO_EDUCATIVO_MENSUAL,ANOS_PENDIENTE_SECUN,COSTO_SEMESTRE_ACTUAL,ANOS_PROY_UNIV,GASTOS_EDUCATIVOS,
             PAGO_TOTAL,RENTA_MENSUAL,ANOS_PAGO,USUARIO_CREACION,FECHA_CREACION,USUARIO_TRANSACCION,
             FECHA_TRANSACCION
        FROM EMI_BENEFICIARIOS EF
       WHERE EF.CODIGO_RIESGO = var_cod_riesgo
         AND EF.NUMERO_SOLICITUD = var_solicitud;

      INSERT INTO EMI_BLOQUE_MEDICO
             ( NUMERO_SOLICITUD,CODIGO_RIESGO,PESO_ACTUAL,ESTATURA,INDICE_MASA_CORPORAL,HIPERTENSION_ARTERIAL,
               COLESTEROL_TRIGLICERIDOS,OBESIDAD,ESTA_EMBARAZADA,OTRA_ENFERMEDAD_SINTOMA,CUAL_ENFERMEDAD,
               DEBE_TRAER_HISTORIA_CLINICA,PARALISIS_O_AMPUTACIONES,CIRUGIAS,SUSTANCIAS_ADICTIVAS,SUSTANCIA_TOXICA,
               FUMA,FUMABA,HACE_CUANTO,CUANTOS_CIGARRILLOS,TOMA_ALGUN_MEDICAMENTO,POR_ENFERMEDAD_MENCIONADA,
               OTRO_MEDICAMENTO,CUAL_MEDICAMENTO,CIRUGIA_PROGRAMADA,CUAL_CIRUGIA,ESTUDIO_HTA,
               ESTUDIO_OBESIDAD,ESTUDIO_LIPIDOS,ESTUDIO_DIABETES,SE_ENVIA_A_EVALUACION,USUARIO_CREACION,
               FECHA_CREACION,USUARIO_TRANSACCION,FECHA_TRANSACCION,ANTECEDENTE_FAMILIAR,CUAL_ANTECEDENTE,
               ANTECEDENTE_POLIZA,AUMENTO_PESO,CAMBIO_MOTIVO_SALUD,MOTIVO,GANADO,PERDIDO,CUANTOS_KILOS,
               MOTIVO_PESO,EVOLUCION,CUANTOS_MESES,OTRA_CIRUGIA,CIRUGIA_ANTIGUA,CUANDO,CUALES_SUSTANCIAS,
               CANTIDAD_DIARIA_CIGARRILLO,CONSUME_LICOR,CANTIDAD_DIARIA_LICOR,CONSUME_ALUCINOGENOS,CANTIDAD_DIARIA_ALUCINOGENOS,PROGRAMACION_CIRUGIA
             )
       SELECT var_num_solicitud,CODIGO_RIESGO,PESO_ACTUAL,ESTATURA,INDICE_MASA_CORPORAL,HIPERTENSION_ARTERIAL,
              COLESTEROL_TRIGLICERIDOS,OBESIDAD,ESTA_EMBARAZADA,OTRA_ENFERMEDAD_SINTOMA,CUAL_ENFERMEDAD,
              DEBE_TRAER_HISTORIA_CLINICA,PARALISIS_O_AMPUTACIONES,CIRUGIAS,SUSTANCIAS_ADICTIVAS,SUSTANCIA_TOXICA,
              FUMA,FUMABA,HACE_CUANTO,CUANTOS_CIGARRILLOS,TOMA_ALGUN_MEDICAMENTO,POR_ENFERMEDAD_MENCIONADA,
              OTRO_MEDICAMENTO,CUAL_MEDICAMENTO,CIRUGIA_PROGRAMADA,CUAL_CIRUGIA,ESTUDIO_HTA,
              ESTUDIO_OBESIDAD,ESTUDIO_LIPIDOS,ESTUDIO_DIABETES,SE_ENVIA_A_EVALUACION,USUARIO_CREACION,
              FECHA_CREACION,USUARIO_TRANSACCION,FECHA_TRANSACCION,ANTECEDENTE_FAMILIAR,CUAL_ANTECEDENTE,
              ANTECEDENTE_POLIZA,AUMENTO_PESO,CAMBIO_MOTIVO_SALUD,MOTIVO,GANADO,PERDIDO,CUANTOS_KILOS,
              MOTIVO_PESO,EVOLUCION,CUANTOS_MESES,OTRA_CIRUGIA,CIRUGIA_ANTIGUA,CUANDO,CUALES_SUSTANCIAS,
              CANTIDAD_DIARIA_CIGARRILLO,CONSUME_LICOR,CANTIDAD_DIARIA_LICOR,CONSUME_ALUCINOGENOS,CANTIDAD_DIARIA_ALUCINOGENOS,PROGRAMACION_CIRUGIA
        FROM  EMI_BLOQUE_MEDICO ED
       WHERE  ED.CODIGO_RIESGO = var_cod_riesgo
         AND  ED.NUMERO_SOLICITUD = var_solicitud;

       INSERT INTO EMI_CLAUSULAS_EXCLUSION
              ( NRO_SECU,NUMERO_SOLICITUD,TXT_COMP,USUARIO_CREACION,FECHA_CREACION,
                USUARIO_TRANSACCION,FECHA_TRANSACCION,NUM_CLAUSULA
              )
        SELECT NRO_SECU,var_num_solicitud,TXT_COMP,USUARIO_CREACION,FECHA_CREACION,
               USUARIO_TRANSACCION,FECHA_TRANSACCION,NUM_CLAUSULA
          FROM EMI_CLAUSULAS_EXCLUSION EL
         WHERE EL.NUMERO_SOLICITUD = var_solicitud;

        INSERT INTO EMI_COMISIONES
              ( NRO_SECU,NUMERO_SOLICITUD,CLAVE_INTERMEDIARIO,LOCALIDAD_RADICACION,CONVENIO,
                FORMA_ACTUACION,PORC_PARTICIPACION,MCA_LIDER,USUARIO_CREACION,FECHA_CREACION,
                USUARIO_TRANSACCION,FECHA_TRANSACCION
              )
        SELECT NRO_SECU,var_num_solicitud,CLAVE_INTERMEDIARIO,LOCALIDAD_RADICACION,CONVENIO,
               FORMA_ACTUACION,PORC_PARTICIPACION,MCA_LIDER,USUARIO_CREACION,FECHA_CREACION,
               USUARIO_TRANSACCION,FECHA_TRANSACCION
          FROM EMI_COMISIONES EN
         WHERE EN.NUMERO_SOLICITUD = var_solicitud;

         INSERT INTO EMI_CONCEPTO_TECNICO
               ( NUMERO_SOLICITUD,CODIGO_RIESGO,TIPO_RIES,TIPO_RIES_RE,REC_OCU_VIDA,REC_SALU_VIDA,
                 PORC_DESADMTVO,REC_X_MUERTE,PORC_DESADM902,REC_X_DESMEM,PORC_DESADM903,REC_X_INDEMN,
                 PORC_DESADM904,REC_X_GASMED,PORC_DESADM905,REC_SALU_EG,PORC_DESADM906,REC_SALU_ITP,
                 PORC_DESADM908,REC_SALU_EE,PORC_DESADM910,REC_SALU_EADIC,PORC_DESADM911,REC_SALU_EEADI,
                 PORC_DESADM912,CAMBIA_A_PREFERENTE,CATEGORIA,USUARIO_CREACION,FECHA_CREACION,
                 USUARIO_TRANSACCION,FECHA_TRANSACCION,REC_X_MAATT,PORC_DESADM915,REC_ITP_ADIC,
                 PORC_DESADM916,REC_RENTA_DIARIA,PORC_DESADM918
                )
         SELECT var_num_solicitud, CODIGO_RIESGO,TIPO_RIES,TIPO_RIES_RE,REC_OCU_VIDA,REC_SALU_VIDA,
                PORC_DESADMTVO,REC_X_MUERTE,PORC_DESADM902,REC_X_DESMEM,PORC_DESADM903,REC_X_INDEMN,
                PORC_DESADM904,REC_X_GASMED,PORC_DESADM905,REC_SALU_EG,PORC_DESADM906,REC_SALU_ITP,
                PORC_DESADM908,REC_SALU_EE,PORC_DESADM910,REC_SALU_EADIC,PORC_DESADM911,REC_SALU_EEADI,
                PORC_DESADM912,CAMBIA_A_PREFERENTE,CATEGORIA,USUARIO_CREACION,FECHA_CREACION,
                USUARIO_TRANSACCION,FECHA_TRANSACCION,REC_X_MAATT,PORC_DESADM915,REC_ITP_ADIC,
                PORC_DESADM916,REC_RENTA_DIARIA,PORC_DESADM918
           FROM EMI_CONCEPTO_TECNICO ET
          WHERE ET.CODIGO_RIESGO = var_cod_riesgo
            AND ET.NUMERO_SOLICITUD = var_solicitud;

        INSERT INTO EMI_ENFERMEDAD_ASEGURADO
               ( COD_ENF,NUMERO_SOLICITUD,CODIGO_RIESGO,USUARIO_TRANSACCION,FECHA_TRANSACCION,
                 INSTITUCION_MEDICO,FECHA_DIAGNOSTICO,FECHA_ULTIMO_EPISODIO,EVOLUCION_SECUELAS
               )
        SELECT COD_ENF,var_num_solicitud,CODIGO_RIESGO,USUARIO_TRANSACCION,FECHA_TRANSACCION,
               INSTITUCION_MEDICO,FECHA_DIAGNOSTICO,FECHA_ULTIMO_EPISODIO,EVOLUCION_SECUELAS
          FROM EMI_ENFERMEDAD_ASEGURADO ER
         WHERE ER.CODIGO_RIESGO = var_cod_riesgo
           AND ER.NUMERO_SOLICITUD = var_solicitud;

        INSERT INTO EMI_FORMA_PAGO
               ( NUMERO_SOLICITUD,PRIMERA_CUOTA_EFECTIVO,FORMA_PAGO,TIPO_DOC_LIBRANZA,NIT_LIBRANZA,
                 ENTIDAD_DEBITO,COD_IDENTIF,TIPO_CUENTA,NUMERO_CUENTA,FECHA_VCTO_TARJETA,NOMBRE_CTAHABIENTE,
                 IDENTIFICACION_CTAHABIENTE,DIRECCION_CTAHABIENTE,CIUDAD_CTAHABIENTE,TELEFONO_CTAHABIENTE,
                 PERIODICIDAD,VALOR_A_AHORRAR,INC_ANUAL_AHORRO,TOTAL_PRIMA_MAS_AHORRO,INC_ADICIONAL_IPC_RENOVACION,
                 USUARIO_CREACION,FECHA_CREACION,USUARIO_TRANSACCION,FECHA_TRANSACCION,TC_NRO_CUOTAS,CONVENIO_FER_FED,TIPO_DOC_CTAHABIENTE
               )
        SELECT var_num_solicitud,PRIMERA_CUOTA_EFECTIVO,FORMA_PAGO,TIPO_DOC_LIBRANZA,NIT_LIBRANZA,
               ENTIDAD_DEBITO,COD_IDENTIF,TIPO_CUENTA,NUMERO_CUENTA,FECHA_VCTO_TARJETA,NOMBRE_CTAHABIENTE,
               IDENTIFICACION_CTAHABIENTE,DIRECCION_CTAHABIENTE,CIUDAD_CTAHABIENTE,TELEFONO_CTAHABIENTE,
               PERIODICIDAD,VALOR_A_AHORRAR,INC_ANUAL_AHORRO,TOTAL_PRIMA_MAS_AHORRO,INC_ADICIONAL_IPC_RENOVACION,
               USUARIO_CREACION,FECHA_CREACION,USUARIO_TRANSACCION,FECHA_TRANSACCION,TC_NRO_CUOTAS,CONVENIO_FER_FED,TIPO_DOC_CTAHABIENTE
          FROM EMI_FORMA_PAGO EP
         WHERE EP.NUMERO_SOLICITUD = var_solicitud;

         INSERT INTO EMI_FORMA_PAGO_AHORRO
                (NUMERO_SOLICITUD,PRIMERA_CUOTA_EFECTIVO,FORMA_PAGO,ENTIDAD_DEBITO,COD_IDENTIF,TIPO_CUENTA,
                 NUMERO_CUENTA,NOMBRE_CTAHABIENTE,TIPO_DOC_CTAHABIENTE,IDENTIFICACION_CTAHABIENTE,DIRECCION_CTAHABIENTE,
                 CIUDAD_CTAHABIENTE,TELEFONO_CTAHABIENTE,PERIODICIDAD,VALOR_A_AHORRAR,INC_ANUAL_AHORRO,
                 TOTAL_PRIMA_MAS_AHORRO,USUARIO_CREACION,FECHA_CREACION,USUARIO_TRANSACCION,FECHA_TRANSACCION
                )
         SELECT var_num_solicitud,PRIMERA_CUOTA_EFECTIVO,FORMA_PAGO,ENTIDAD_DEBITO,COD_IDENTIF,TIPO_CUENTA,
                 NUMERO_CUENTA,NOMBRE_CTAHABIENTE,TIPO_DOC_CTAHABIENTE,IDENTIFICACION_CTAHABIENTE,DIRECCION_CTAHABIENTE,
                 CIUDAD_CTAHABIENTE,TELEFONO_CTAHABIENTE,PERIODICIDAD,VALOR_A_AHORRAR,INC_ANUAL_AHORRO,
                 TOTAL_PRIMA_MAS_AHORRO,USUARIO_CREACION,FECHA_CREACION,USUARIO_TRANSACCION,FECHA_TRANSACCION
          FROM EMI_FORMA_PAGO_AHORRO EP
         WHERE EP.NUMERO_SOLICITUD = var_solicitud;

         INSERT INTO EMI_MEDICAMENTO_ASEGURADO
               ( COD_MED,NUMERO_SOLICITUD,CODIGO_RIESGO,USUARIO_TRANSACCION,FECHA_TRANSACCION)
         SELECT COD_MED,var_num_solicitud,CODIGO_RIESGO,USUARIO_TRANSACCION,FECHA_TRANSACCION
           FROM EMI_MEDICAMENTO_ASEGURADO EC
          WHERE EC.NUMERO_SOLICITUD = var_solicitud;

        INSERT INTO EMI_REFERENCIAS_FAMILIARES
               ( NUMERO_SOLICITUD,CONSECUTIVO,NOMBRE_COMPLETO,TELEFONO,USUARIO_CREACION,
                 FECHA_CREACION,USUARIO_TRANSACCION,FECHA_TRANSACCION
               )
        SELECT var_num_solicitud, CONSECUTIVO,NOMBRE_COMPLETO,TELEFONO,USUARIO_CREACION,
               FECHA_CREACION,USUARIO_TRANSACCION,FECHA_TRANSACCION
          FROM EMI_REFERENCIAS_FAMILIARES EL
         WHERE EL.NUMERO_SOLICITUD = var_solicitud;

        INSERT INTO EMI_REFERENCIAS_PERSONALES
               ( NUMERO_SOLICITUD,CONSECUTIVO,NOMBRE_COMPLETO,TELEFONO,
                 USUARIO_CREACION,FECHA_CREACION,USUARIO_TRANSACCION,FECHA_TRANSACCION
               )
        SELECT var_num_solicitud,CONSECUTIVO,NOMBRE_COMPLETO,TELEFONO,
               USUARIO_CREACION,FECHA_CREACION,USUARIO_TRANSACCION,FECHA_TRANSACCION
          FROM EMI_REFERENCIAS_PERSONALES EP
         WHERE EP.NUMERO_SOLICITUD = var_solicitud;

          DELETE FROM EMI_MUTATING WHERE TABLE_NAME = 'EMI_SOLICITUD';
  end if;
end TRG_AU_EMI_CAMBIA_PRODUCTO;
/
