CREATE OR REPLACE TRIGGER TRG_EMI_ALARMA_ENFERMEDADES
AFTER INSERT OR UPDATE ON EMI_ENFERMEDAD_ASEGURADO FOR EACH ROW
DECLARE

 VAR_ENFERMEDAD VARCHAR2(60);

BEGIN
 IF NVL(:NEW.COD_ENF,0) <> NVL(:OLD.COD_ENF,0)THEN

     SELECT EF.ENFERMEDAD
       INTO VAR_ENFERMEDAD
       FROM EMI_ENFERMEDADES EF
      WHERE EF.CODIGO = :NEW.COD_ENF;

     UPDATE EMI_SOLICITUD_POLIZA
        SET OBSERVACION_USUARIO = OBSERVACION_USUARIO || ' -> '||:NEW.USUARIO_TRANSACCION||' Fecha: '||sysdate||' '|| ' ALARMA: '||VAR_ENFERMEDAD
      WHERE NUMERO_SOLICITUD = :NEW.NUMERO_SOLICITUD;
 END IF;

EXCEPTION WHEN OTHERS THEN
  RAISE_APPLICATION_ERROR(-20005,'Error Alarmas Enf '||SQLERRM);
END;
/
