CREATE OR REPLACE TRIGGER TRG_COPIA_EMI_FORMA_PAGO
AFTER INSERT OR UPDATE OF COPIA_FORMA_PAGO ON EMI_FORMA_PAGO
FOR EACH ROW
DECLARE

BEGIN

  IF :NEW.COPIA_FORMA_PAGO = 'S' AND (NVL(:NEW.COPIA_FORMA_PAGO,'-') <> NVL(:OLD.COPIA_FORMA_PAGO,'-')) THEN

          DELETE FROM EMI_FORMA_PAGO_AHORRO
          WHERE NUMERO_SOLICITUD = :NEW.NUMERO_SOLICITUD;

          INSERT INTO EMI_FORMA_PAGO_AHORRO
          (NUMERO_SOLICITUD,
           PRIMERA_CUOTA_EFECTIVO,
           FORMA_PAGO,
           ENTIDAD_DEBITO,
           COD_IDENTIF,
           TIPO_CUENTA,
           NUMERO_CUENTA,
           TIPO_DOC_CTAHABIENTE,
           NOMBRE_CTAHABIENTE,
           IDENTIFICACION_CTAHABIENTE,
           DIRECCION_CTAHABIENTE,
           CIUDAD_CTAHABIENTE,
           TELEFONO_CTAHABIENTE,
           PERIODICIDAD,
           USUARIO_CREACION,
           FECHA_CREACION,
           USUARIO_TRANSACCION,
           FECHA_TRANSACCION)
        VALUES
          (:NEW.NUMERO_SOLICITUD,
           :NEW.PRIMERA_CUOTA_EFECTIVO,
           :NEW.FORMA_PAGO,
           :NEW.ENTIDAD_DEBITO,
           :NEW.COD_IDENTIF,
           :NEW.TIPO_CUENTA,
           :NEW.NUMERO_CUENTA,
           :NEW.TIPO_DOC_CTAHABIENTE,
           :NEW.NOMBRE_CTAHABIENTE,
           :NEW.IDENTIFICACION_CTAHABIENTE,
           :NEW.DIRECCION_CTAHABIENTE,
           :NEW.CIUDAD_CTAHABIENTE,
           :NEW.TELEFONO_CTAHABIENTE,
           :NEW.PERIODICIDAD,
           :NEW.USUARIO_CREACION,
           SYSDATE,
           :NEW.USUARIO_TRANSACCION,
           SYSDATE);
  END IF;
END;
/
