CREATE OR REPLACE TRIGGER "TRG_SEC_SIM_PERIODOS_CARENCIA"
  BEFORE INSERT ON SIM_PERIODOS_CARENCIA
  FOR EACH ROW
BEGIN

  :NEW.PERCAR_SECUENCIA := SEC_SIM_PERIODOS_CARENCIA.NEXTVAL;

END TRG_SEC_SIM_PERIODOS_CARENCIA;
/
