CREATE OR REPLACE TRIGGER TRG_AIR_CUENTAS_GESTION_BANCO
AFTER INSERT ON SIM_CUENTAS_GESTION_BANCOS FOR EACH ROW
DECLARE
  vl_ip_equipo_maquina  SIM_HIST_CUENTAS_GESTION_BANCO.IP_EQUIPO_MAQUINA%TYPE;
BEGIN
  vl_ip_equipo_maquina := 'IP: '||sys_context('USERENV','ip_address')||', Host: '||sys_context('USERENV','host');
  INSERT INTO SIM_HIST_CUENTAS_GESTION_BANCO (SECUENCIA, ROWID_CUENTAS_GESTION_BANCOS,
  FECHA_OPERACION, TIPO_OPERACION, USUARIO_OPERACION, IP_EQUIPO_MAQUINA,
  COD_CIA, CUENTA_CONTABLE, ES_BANCO_CUENTA, ES_CUENTA_TERCERO,
  CUENTA_SIMPLIFICADA, FECHA_CREACION, USUARIO_CREACION, FECHA_MODIFICACION,
  USUARIO_MODIFICACION, OBSERVACION, FECHA_ALTA, FECHA_BAJA)
  VALUES (SEQ_HIST_CUENTAS_GESTION_BANCO.NEXTVAL, :NEW.ROWID, SYSDATE, 'I',
  :NEW.USUARIO_CREACION, vl_ip_equipo_maquina, :NEW.COD_CIA, :NEW.CUENTA_CONTABLE,
  :NEW.ES_BANCO_CUENTA, :NEW.ES_CUENTA_TERCERO, :NEW.CUENTA_SIMPLIFICADA,
  :NEW.FECHA_CREACION, :NEW.USUARIO_CREACION, :NEW.FECHA_MODIFICACION,
  :NEW.USUARIO_MODIFICACION, :NEW.OBSERVACION, :NEW.FECHA_ALTA, :NEW.FECHA_BAJA);
  -- Validaciones
  SIM_PCK_PAGOS_MASIVOS_CG.Prc_Cargar(p_cod_cia => :NEW.COD_CIA,
  p_cuenta_contable => :NEW.CUENTA_CONTABLE, p_es_banco_cuenta => :NEW.ES_BANCO_CUENTA,
  p_fecha_alta => :NEW.FECHA_ALTA, p_fecha_baja => :NEW.FECHA_BAJA,
  p_rowid => :NEW.ROWID);
END TRG_AIR_CUENTAS_GESTION_BANCO;
/
