CREATE OR REPLACE TRIGGER TRG_BIU_SINIMMAG
BEFORE INSERT OR UPDATE
ON SINIMMAG 
REFERENCING NEW AS NEW OLD AS OLD
FOR EACH ROW
DECLARE
  --
  FUNCTION QUITARCRCTER (e_cadena IN VARCHAR2) RETURN VARCHAR2 IS
    -- Variables
    l_VarResult VARCHAR2(200);
  BEGIN
    l_VarResult := e_cadena;
    SELECT REPLACE(e_cadena,CHR(10),'') INTO l_VarResult FROM DUAL; 
	SELECT REPLACE(l_VarResult,CHR(13),'') INTO l_VarResult FROM DUAL;
	SELECT REPLACE(l_VarResult,CHR(92),'') INTO l_VarResult FROM DUAL;
	RETURN l_VarResult;
  EXCEPTION WHEN OTHERS THEN
    RETURN e_cadena;  
  END QUITARCRCTER;
  --
BEGIN
  IF UPDATING THEN
    IF :NEW.DESCRIPCION <> :OLD.DESCRIPCION THEN
	  :NEW.DESCRIPCION := QUITARCRCTER (:NEW.DESCRIPCION);
	END IF;
    IF :NEW.DOCUMENTO_SOPORTE1 <> :OLD.DOCUMENTO_SOPORTE1 THEN
	  :NEW.DOCUMENTO_SOPORTE1 := QUITARCRCTER (:NEW.DOCUMENTO_SOPORTE1);
	END IF;
	IF :NEW.DOCUMENTO_SOPORTE2 <> :OLD.DOCUMENTO_SOPORTE2 THEN
	  :NEW.DOCUMENTO_SOPORTE2 := QUITARCRCTER (:NEW.DOCUMENTO_SOPORTE2);
	END IF;
	IF :NEW.DOCUMENTO_SOPORTE3 <> :OLD.DOCUMENTO_SOPORTE3 THEN
	  :NEW.DOCUMENTO_SOPORTE3 := QUITARCRCTER (:NEW.DOCUMENTO_SOPORTE3);
	END IF;
  END IF;	
  IF INSERTING THEN	
    :NEW.DESCRIPCION := QUITARCRCTER (:NEW.DESCRIPCION);
	:NEW.DOCUMENTO_SOPORTE1 := QUITARCRCTER (:NEW.DOCUMENTO_SOPORTE1);
	:NEW.DOCUMENTO_SOPORTE2 := QUITARCRCTER (:NEW.DOCUMENTO_SOPORTE2);
	:NEW.DOCUMENTO_SOPORTE3 := QUITARCRCTER (:NEW.DOCUMENTO_SOPORTE3);  
  END IF;
EXCEPTION
    WHEN OTHERS THEN
      NULL;
END TRG_BIU_SINIMMAG;
/
