CREATE OR REPLACE TRIGGER "TRG_SEC_SIM_EXCLUSION_GENERAL"
  BEFORE INSERT ON SIM_EXCLUSION_GENERAL
  FOR EACH ROW
BEGIN

  :NEW.EXCGEN_SECUENCIA := SEC_SIM_EXCLUSION_GENERAL.NEXTVAL;

END TRG_SEC_SIM_EXCLUSION_GENERAL;
/
