CREATE OR REPLACE TRIGGER TRG_AIUS_CUENTAS_GESTION_BANCO
AFTER INSERT OR UPDATE ON SIM_CUENTAS_GESTION_BANCOS
BEGIN
  SIM_PCK_PAGOS_MASIVOS_CG.Prc_Validar_Solapes;
END TRG_BIUS_CUENTAS_GESTION_BANCO;
/
