CREATE OR REPLACE TRIGGER TRG_RECAUDO_AUDIT
	BEFORE UPDATE OF DOCUMENTO ON A5021113 
	FOR EACH ROW
DISABLE
DECLARE
	V_MSG_LOG	VARCHAR(1000);
BEGIN
    /* 	OBJETIVO		: AUDITAR LA TABLA PARA IDENTIFICAR LOS PROCESOS QUE PUEDAN ESTAR ANULANDO EL CAMPO DOCUMENTO
    						DADO QUE ESTA IMPIDIENDO QUE SE REALICEN LOS RECAUDOS EN SAI
		DESARROLLADO POR: SADITH NUNEZ ROCHA
		FECHA CRECION	: 15/04/2024
		TICKET			: ESTCORE-10100
    */
    IF (:OLD.MCA_ESTADO = 'T' AND :OLD.DOCUMENTO > 0 AND :NEW.DOCUMENTO IS NULL ) THEN 
		-- Se está anulando un recibo de caja antes de que se aplique en SAI.
		-- Esta acción no es correcta por tanto se impide el cambio del camo DOCUMENTO
		
		:NEW.DOCUMENTO := :OLD.DOCUMENTO;
		:NEW.MCA_ESTADO := :OLD.MCA_ESTADO;
    	V_MSG_LOG := 'Anulacion de recaudo PENDIENTE por aplicacion en SAI. LIQ: ' || :OLD.NUM_LIQUIDACION  ||' - DOCUMENTO: ' || :OLD.DOCUMENTO ||' - PROCESO ORIGEN: ' || SYS_CONTEXT('USERENV', 'MODULE');
		BEGIN
			INSERT INTO LOG_TESORERIA ( EVENTO, MENSAJE, SECUENCIA, FECHA, ID_SESSION, USUARIO) 
			VALUES ( 'TRG_RECAUDO_AUDIT', V_MSG_LOG, NULL, SYSDATE, SYS_CONTEXT('USERENV', 'SID'), SYS_CONTEXT('USERENV', 'SESSION_USER'));
		EXCEPTION
			WHEN OTHERS THEN
				RAISE_APPLICATION_ERROR(-20507, 'ERR EN INSERT LOG_TESORERIA DESDE TRG_RECAUDO_AUDIT. ' || SQLERRM);
		END;
	ELSIF (:OLD.MCA_ESTADO = 'P' AND :OLD.DOCUMENTO > 0 AND (:NEW.DOCUMENTO IS NULL OR :NEW.MCA_ESTADO='I')) THEN
		-- Hay recaudos que se pueden anular porque se realiza devolucion del pago.
		-- Por lo tanto no se impedirá dicha acción pero si se auditará
    	V_MSG_LOG := 'Anulacion de recaudo ya aplicado en SAI. LIQ: ' || :OLD.NUM_LIQUIDACION  ||' - DOCUMENTO: ' || :OLD.DOCUMENTO ||' - PROCESO ORIGEN: ' || SYS_CONTEXT('USERENV', 'MODULE');
		BEGIN
			INSERT INTO LOG_TESORERIA ( EVENTO, MENSAJE, SECUENCIA, FECHA, ID_SESSION, USUARIO) 
			VALUES ( 'TRG_RECAUDO_AUDIT', V_MSG_LOG, NULL, SYSDATE, SYS_CONTEXT('USERENV', 'SID'), SYS_CONTEXT('USERENV', 'SESSION_USER'));
		EXCEPTION
			WHEN OTHERS THEN
				RAISE_APPLICATION_ERROR(-20507, 'ERR EN INSERT LOG_TESORERIA DESDE TRG_RECAUDO_AUDIT. ' || SQLERRM);
		END;
    END IF;

END TRG_RECAUDO_AUDIT;
/
