CREATE OR REPLACE TRIGGER "TRG_SIM_DBA_PARAMETROS" 
    BEFORE INSERT OR UPDATE OF FUNCION_VALIDACION,ID_PARAMETRO,TIPO,VALOR ON SIM_DBA_PARAMETROS 
   for each row
BEGIN

  PCK_SIM_DBA_PARAMETROS.VALIDARPARAMETRO(
    ID_PARAMETRO => :OLD.ID_PARAMETRO,
    VALOR_ACT => :NEW.VALOR,
    VALOR_ANT => :OLD.VALOR,
    TIPO => :OLD.TIPO,
    FUNCION_VALIDACION => :OLD.FUNCION_VALIDACION
  );
  
END;
/
