CREATE OR REPLACE TRIGGER TRG_BIU_R_A7000110 BEFORE INSERT OR UPDATE ON A7000110 FOR EACH ROW
BEGIN
  IF :NEW.TIPO_EXPED = :NEW.TIPO_EXP_RELAC THEN
    RAISE_APPLICATION_ERROR(-20000,'NO PUEDE COLOCAR EL MISMO TIPO DE EXPEDIENTE');
  END IF;
END;
/
