CREATE OR REPLACE TRIGGER TRG_SEC_CATEGORIZN_TARIF_AUTOS
  BEFORE INSERT ON SIM_CATEGORIZACION_TARIF_AUTOS
  FOR EACH ROW
DECLARE
  V_SECUENCIA NUMBER(15) := 0;
BEGIN
  BEGIN
     SELECT SEC_SIM_CATEGORIZN_TARIF_AUTOS.NEXTVAL
     INTO   V_SECUENCIA
     FROM   DUAL;
  END;

  :NEW.SECUENCIA := V_SECUENCIA;

END TRG_SEC_CATEGORIZN_TARIF_AUTOS;
/
