CREATE OR REPLACE TRIGGER TRG_EXCLU_PROD_IMPR_CONV_LIBR
  BEFORE INSERT ON  SIM_EXCLU_PROD_IMPR_CONV_LIBR 
  FOR EACH ROW
DECLARE
  V_SECUENCIA NUMBER(17) := 0;
BEGIN
  BEGIN
    SELECT SEC_EXCLU_PROD_IMPR_CONV_LIBR.NEXTVAL INTO V_SECUENCIA FROM DUAL;
  END;
   :NEW.SECUENCIA := V_SECUENCIA;
END  TRG_EXCLU_PROD_IMPR_CONV_LIBR;
/
