CREATE OR REPLACE TRIGGER "TRG_SEC_SIM_CENTROS_SERVICIO"
  BEFORE INSERT ON SIM_CENTROS_SERVICIO
  FOR EACH ROW
BEGIN

  :NEW.CSV_SECUENCIA := SEC_SIM_CENTROS_SERVICIO.NEXTVAL;

END TRG_SEC_SIM_CENTROS_SERVICIO;
/
