CREATE OR REPLACE TRIGGER TRG_BI_C9990119
BEFORE INSERT ON C9990119 
FOR EACH ROW
DECLARE
/*
Creado por:Juan C Gonzalez
Fecha : Marzo 6 2013
Proposito: Actualizar los campos de valores y porcentajes con los decimales cargados
desde el archivo plano de TC de davivienda
*/
BEGIN
    --Campos númericos
    :NEW.PORC_ASEGURABILIDAD:=:NEW.PORC_ASEGURABILIDAD*0.01;
    :NEW.PORC_EXTRA_PRI:=:NEW.PORC_EXTRA_PRI*0.01;
    :NEW.VLR_CUPO_OTOR:=:NEW.VLR_CUPO_OTOR*0.01;
    :NEW.VLR_DISPONIBLE:=:NEW.VLR_DISPONIBLE*0.01;
    :NEW.VLR_DESEMBOLSO:=:NEW.VLR_DESEMBOLSO*0.01;
    :NEW.VLR_ASEG_VIDA:=:NEW.VLR_ASEG_VIDA*0.01;
    :NEW.VLR_ASEG_ITP:=:NEW.VLR_ASEG_ITP*0.01;
    :NEW.VLR_PRIMA_VIDA:=:NEW.VLR_PRIMA_VIDA*0.01;
    :NEW.VLR_PRIMA_ITP_BOL:=:NEW.VLR_PRIMA_ITP_BOL*0.01;
    :NEW.VLR_EXT_VIDA:=:NEW.VLR_EXT_VIDA*0.01;
    :NEW.VLR_EXT_ITP:=:NEW.VLR_EXT_ITP*0.01;
    :NEW.VLR_INT_MORA:=:NEW.VLR_INT_MORA*0.01;
END;
/
