CREATE OR REPLACE TRIGGER TRG_SIM_PARAM_TARIFACION_FCTOR 
  BEFORE INSERT ON  SIM_PARAM_TARIFACION_FACTOR 
  FOR EACH ROW
DECLARE
  V_SECUENCIA NUMBER(17) := 0;
BEGIN
  BEGIN
    SELECT SEC_SIM_PARAM_TARIFACION_FCTOR.NEXTVAL INTO V_SECUENCIA FROM DUAL;
  END;
   :NEW.SECUENCIA := V_SECUENCIA;
END TRG_SIM_PARAM_TARIFACION_FCTOR;
/
