CREATE OR REPLACE TRIGGER trg_cambia_suma_asegurada
AFTER UPDATE OF suma_asegurada ON EMI_SOLICITUD_POLIZA
FOR EACH ROW
DECLARE

BEGIN
 IF :NEW.SUMA_ASEGURADA <> :OLD.SUMA_ASEGURADA THEN
     DELETE FROM EMI_AMPAROS_ADICIONALES WHERE NUMERO_SOLICITUD = :NEW.NUMERO_SOLICITUD;
 END IF;
END;
/
