CREATE OR REPLACE TRIGGER TRG_SEQ_A502_AUDITORIA_AREA
  BEFORE INSERT ON A502_AUDITORIA_AREA_FACT FOR EACH ROW
DECLARE
  -- local variables here
  V_secuencia NUMBER(25) := 0;
BEGIN
  BEGIN
     SELECT SEC_A502_AUDITORIA_AREA_FE.NEXTVAL
     INTO   V_secuencia
     FROM   dual;
  END;

  :NEW.ID_AUDITORIA := V_secuencia;

END TRG_SEQ_A502_AUDITORIA_AREA;
/
