CREATE OR REPLACE TRIGGER TRG_HIST_EMI_FORMA_PAGO_AH
AFTER INSERT OR UPDATE ON EMI_FORMA_PAGO_AHORRO
FOR EACH ROW
DECLARE

BEGIN
   INSERT INTO EMI_HIST_FORMA_PAGO_AHORRO
         (SECUENCIA_HISTORICO,
          NUMERO_SOLICITUD,
          PRIMERA_CUOTA_EFECTIVO,
          FORMA_PAGO,
          ENTIDAD_DEBITO,
          COD_IDENTIF,
          TIPO_CUENTA,
          NUMERO_CUENTA,
          NOMBRE_CTAHABIENTE,
          TIPO_DOC_CTAHABIENTE,
          IDENTIFICACION_CTAHABIENTE,
          DIRECCION_CTAHABIENTE,
          CIUDAD_CTAHABIENTE,
          TELEFONO_CTAHABIENTE,
          USUARIO_CREACION,
          FECHA_CREACION,
          USUARIO_TRANSACCION,
          FECHA_TRANSACCION,
          PERIODICIDAD,
          VALOR_A_AHORRAR,
          INC_ANUAL_AHORRO,
          TOTAL_PRIMA_MAS_AHORRO
     		 )
   VALUES( Seq_emi_hist_forma_pago_ah.Nextval,
          :NEW.NUMERO_SOLICITUD,
          :NEW.PRIMERA_CUOTA_EFECTIVO,
          :NEW.FORMA_PAGO,
          :NEW.ENTIDAD_DEBITO,
          :NEW.COD_IDENTIF,
          :NEW.TIPO_CUENTA,
          :NEW.NUMERO_CUENTA,
          :NEW.NOMBRE_CTAHABIENTE,
          :NEW.TIPO_DOC_CTAHABIENTE,
          :NEW.IDENTIFICACION_CTAHABIENTE,
          :NEW.DIRECCION_CTAHABIENTE,
          :NEW.CIUDAD_CTAHABIENTE,
          :NEW.TELEFONO_CTAHABIENTE,
          :NEW.USUARIO_CREACION,
          :NEW.FECHA_CREACION,
          :NEW.USUARIO_TRANSACCION,
          SYSDATE,
          :NEW.PERIODICIDAD,
          :NEW.VALOR_A_AHORRAR,
          :NEW.INC_ANUAL_AHORRO,
          :NEW.TOTAL_PRIMA_MAS_AHORRO
         );
END;
/
