CREATE OR REPLACE TRIGGER TRG_VALIDA_EMI_AMPAROS
AFTER INSERT OR UPDATE ON EMI_AMPAROS_ADICIONALES FOR EACH ROW
BEGIN
    IF(:NEW.INCAPACIDAD_TOTAL_PERMANENTE = 'S' AND :NEW.EXONERACION_DE_PRIMAS = 'S') THEN
      RAISE_APPLICATION_ERROR(-20154,'No se puede tener ITP y Exoneracion de Primas. Por favor revise');
    END IF;

	IF :NEW.MUERTE_ACCIDENTAL = 'N' THEN
	   IF(:NEW.DESMEMBRACION = 'S' OR :NEW.GASTOS_MEDICOS = 'S' OR  :NEW.RENTA_MENSUAL_INCAPACIDAD = 'S') THEN
         RAISE_APPLICATION_ERROR(-20155,'El asegurado no tiene Muerte Accidental, Por favor revise amparos de Desmembracion,Gastos Medicos o Renta Mensual Incapacidad');
	   END IF;
	END IF;
END;
/
