CREATE OR REPLACE TRIGGER TRG_AU_EMI_ACTUALIZA_ASEGURADO
AFTER UPDATE OF CAMBIA_TOMADOR ON EMI_SOLICITUD_POLIZA
  FOR EACH ROW
BEGIN
     --Man 15341 Se adiciona el cambio de tomador para validar las alarmas
      DELETE FROM EMI_MUTATING WHERE NUMERO_SOLICITUD = :NEW.NUMERO_SOLICITUD AND TABLE_NAME = 'EMI_CAMBIA_TOMADOR';
END;
/
