CREATE OR REPLACE TRIGGER "TRG_HIST_DEFINICION_2" BEFORE
  UPDATE ON IND_REGLAS_DEFINICION FOR EACH ROW
DECLARE v_id NUMBER :=NULL;
  BEGIN
    BEGIN
      SELECT ID
      INTO v_id
      FROM SIM_DEFINICION_REGLAS_JN
      WHERE ID  = :NEW.ID
      AND ROWNUM=1;
    EXCEPTION
    WHEN NO_DATA_FOUND THEN
      INSERT
      INTO OPS$PUMA.SIM_DEFINICION_REGLAS_JN
        (
          ID,
          PRODUCTO,
          SCORE_RIESGO,
          CLV,
          COBERTURA ,
          CAUSA,
          CONSECUENCIA,
          MODELO_RIESGO_PRETENSION,
          RESULTADO_ENCUESTA,
          RESULTADO_EVIDENCIA,
          CLASIFICACION_CASO_CODE,
          MOTOR_DEFINICION_CASO,
          DEFINICION_CASO_CODE,
          COMPANY,
          SECCION,
          FECHA_BAJA,
          FECHA_MODIFICACION,
          USUARIO_MODIFICACION
        )
        VALUES
        (
          :OLD.ID,
          :OLD.PRODUCTO,
          :OLD.SCORE_RIESGO,
          :OLD.CLV,
          :OLD.COBERTURA ,
          :OLD.CAUSA,
          :OLD.CONSECUENCIA,
          :OLD.MODELO_RIESGO_PRETENSION,
          :OLD.RESULTADO_ENCUESTA,
          :OLD.RESULTADO_EVIDENCIA,
          :OLD.CLASIFICACION_CASO_CODE,
          :OLD.MOTOR_DEFINICION_CASO,
          :OLD.DEFINICION_CASO_CODE,
          :OLD.COMPANY,
          :OLD.SECCION,
          :OLD.FECHA_BAJA,
          :OLD.FECHA_CREACION,
          :OLD.USUARIO_CREACION
        );
    END;
  END TRG_HIST_DEFINICION_2;
/
