CREATE OR REPLACE TRIGGER TRG_AIUD_R_A7000100
  after insert or update or delete on A7000100
  for each row
declare
v_ope varchar2(3) := null;
begin
  IF     DELETING  THEN v_ope := 'DEL';
  ELSIF UPDATING  THEN v_ope := 'UPD';
  ELSIF INSERTING THEN v_ope := 'INS';
  ELSE  V_OPE :='ERR';
 END IF;

  IF UPDATING OR INSERTING THEN
   insert into A7000100_JN (
  JN_OPERATION     	,JN_ORACLE_USER      	,JN_DATETIME    ,JN_NOTES
  ,JN_APPLN        	,JN_SESSION		,COD_CIA	,COD_SECC
  ,TIPO_EXPED		,COD_CONCEP_RVA		,COD_COB	,COD_IND
  ,MCA_COB		,COD_USER  		,COD_CAUSA	,COD_CONS
  ,COD_AGRAVANTE	,COD_REBAJA  		,FECHA_CREACION	,USUARIO_CREACION
  ,FECHA_MODIFICA	,USUARIO_MODIFICA	,ESTADO)
  values      (
  v_ope			, user               	, sysdate           	,NULL
  ,NULL            	,NULL                	,:NEW.COD_CIA       	,:NEW.COD_SECC
  ,:NEW.TIPO_EXPED 	,:NEW.COD_CONCEP_RVA	,:NEW.COD_COB	    	,:NEW.COD_IND
  ,:NEW.MCA_COB		,:NEW.COD_USER		,:NEW.COD_CAUSA		,:NEW.COD_CONS
  ,:NEW.COD_AGRAVANTE	,:NEW.COD_REBAJA  	,:NEW.FECHA_CREACION	,:NEW.USUARIO_CREACION
  ,:NEW.FECHA_MODIFICA	,:NEW.USUARIO_MODIFICA	,:NEW.ESTADO);

  ELSIF DELETING THEN
  insert into A7000100_JN (
  JN_OPERATION     	,JN_ORACLE_USER      	,JN_DATETIME    ,JN_NOTES
  ,JN_APPLN        	,JN_SESSION		,COD_CIA	,COD_SECC
  ,TIPO_EXPED		,COD_CONCEP_RVA		,COD_COB	,COD_IND
  ,MCA_COB		,COD_USER  		,COD_CAUSA	,COD_CONS
  ,COD_AGRAVANTE	,COD_REBAJA  		,FECHA_CREACION	,USUARIO_CREACION
  ,FECHA_MODIFICA	,USUARIO_MODIFICA	,ESTADO)
  values      (
  v_ope			, user               	, sysdate           	,NULL
  ,NULL            	,NULL                	,:OLD.COD_CIA       	,:OLD.COD_SECC
  ,:OLD.TIPO_EXPED 	,:OLD.COD_CONCEP_RVA	,:OLD.COD_COB	    	,:OLD.COD_IND
  ,:OLD.MCA_COB		,:OLD.COD_USER		,:OLD.COD_CAUSA		,:OLD.COD_CONS
  ,:OLD.COD_AGRAVANTE	,:OLD.COD_REBAJA  	,:OLD.FECHA_CREACION	,:OLD.USUARIO_CREACION
  ,:OLD.FECHA_MODIFICA	,:OLD.USUARIO_MODIFICA	,:OLD.ESTADO);
  END IF;
end;
/
