CREATE OR REPLACE TRIGGER TRG_INC_SIM_VOLUMENES_SINIESTR
  after INSERT OR UPDATE OR DELETE
  on SIM_VOLUMENES_SINIESTROS
  for each row
begin
  if INSERTING then 
    PCK_INC_SIM_VOLUMENES_SINIESTR.procesa_trigger (:new.ROWID, 'INS');
  elsif UPDATING then
    PCK_INC_SIM_VOLUMENES_SINIESTR.procesa_trigger (:old.ROWID, 'UPD');
  elsif DELETING then
    PCK_INC_SIM_VOLUMENES_SINIESTR.procesa_trigger (:old.ROWID, 'DEL');
  end if; 
EXCEPTION
  WHEN OTHERS THEN
    null;
end TRG_INC_SIM_VOLUMENES_SINIESTR
;
/
