CREATE OR REPLACE TRIGGER TRG_A502_LOG_SERVICIO_LLAVE     
    BEFORE INSERT ON A502_LOG_SERVICIO
    FOR EACH ROW
DISABLE
BEGIN
   :NEW.LOG_TIPO_DOC := REGEXP_SUBSTR(:NEW.LOG_LLAVE_FACTURA,'[^_]+',1,1);
   :NEW.LOG_TDOC_TERCERO := REGEXP_SUBSTR(:NEW.LOG_LLAVE_FACTURA,'[^_]+',1,2);
   :NEW.LOG_COD_BENEF := REGEXP_SUBSTR(:NEW.LOG_LLAVE_FACTURA,'[^_]+',1,3);
   :NEW.LOG_NRO_FACTURA := REGEXP_SUBSTR(:NEW.LOG_LLAVE_FACTURA,'[^_]+',1,4);
END TRG_A502_LOG_SERVICIO_LLAVE;
/
