CREATE OR REPLACE TRIGGER TRG_CART_SAL
BEFORE INSERT ON C5027000
FOR EACH ROW
DECLARE
V_DIAS		NUMBER(5)	:= :NEW.DIAS_DIF;
BEGIN
	IF V_DIAS BETWEEN 0 AND 30 THEN
	   :NEW.DIAS_30 := 30;
	ELSIF V_DIAS BETWEEN 30 AND 60 THEN
	   :NEW.DIAS_60 := 60;
	ELSIF V_DIAS BETWEEN 60 AND 90 THEN
	   :NEW.DIAS_90 := 90;
	ELSIF V_DIAS BETWEEN 90 AND 360 THEN
	   :NEW.DIAS_MAS := 91;
    ELSIF V_DIAS > 360 THEN
     :NEW.DIAS_MAS := 361;
	END IF;
END;
/
