CREATE OR REPLACE TRIGGER trg_emi_inserta_seguridad
AFTER INSERT ON PERFIL
FOR EACH ROW
BEGIN
  INSERT INTO TAREA_PERFIL ( CODIGO_TAREA, CODIGO_PERFIL, PERMISO_EJECUTAR, PERMISO_IMPRIMIR,
                             PERMISO_ACTUALIZACION, PERMISO_ADICIONAR, PERMISO_BORRAR,
							 PERMISO_CONSULTAR, FECHA_TRANSACCION,USUARIO_TRANSACCION
						   )
					VALUES (
						    'SEGU0007', :NEW.codigo_perfil, 'S', 'N', 'S', 'S', 'N', 'N',  SYSDATE, USER
						    );
END;
/
