CREATE OR REPLACE TRIGGER "TRG_SEC_SIM_GRUPO_DEDUCIBLE"
  BEFORE INSERT ON SIM_GRUPO_DEDUCIBLE
  FOR EACH ROW
BEGIN

  :NEW.GRD_CODIGO := SEC_SIM_GRUPO_DEDUCIBLE.NEXTVAL;

END TRG_SEC_SIM_GRUPO_DEDUCIBLE;
/
