CREATE OR REPLACE TRIGGER trg_reversa_emision_solicitud
BEFORE UPDATE OF estado_solicitud ON EMI_SOLICITUD_POLIZA FOR EACH ROW
DECLARE

BEGIN
 IF :NEW.ESTADO_SOLICITUD <> :OLD.ESTADO_SOLICITUD THEN
      IF (:OLD.ESTADO_SOLICITUD = 'EMI' OR :OLD.ESTADO_SOLICITUD = 'EMT' AND :NEW.ESTADO_SOLICITUD = 'PEN') THEN
          :NEW.NUMERO_POLIZA:= NULL;
          :NEW.FECHA_EMISION := NULL;
      END IF;
 END IF;
EXCEPTION WHEN OTHERS THEN
  RAISE_APPLICATION_ERROR(-20189,'Error en reversion poliza '||SQLERRM);
END;
/
