CREATE OR REPLACE TRIGGER TRG_A7000025_TALLER
  FOR INSERT ON A7000025 
COMPOUND TRIGGER

  V_TALLER A7000025.VALOR_CAMPO%TYPE;
  V_TALLER_NUEVO A7000025.VALOR_CAMPO%TYPE := '0';
  V_NUM_SECU_SINI A7000025.NUM_SECU_SINI%TYPE := 0;
  V_NRO_ORDEN_SINI A7000025.NRO_ORDEN_SINI%TYPE := 0; 

  AFTER EACH ROW IS
  BEGIN
    IF (:NEW.COD_RAMO = 250 AND :NEW.COD_CAMPO = 'CEDULA_TALLER'
    AND :NEW.COD_NIVEL = 1 AND :NEW.NRO_ORDEN_SINI > 0) THEN
      V_NUM_SECU_SINI := :NEW.NUM_SECU_SINI;
      V_NRO_ORDEN_SINI := :NEW.NRO_ORDEN_SINI - 1;
      V_TALLER_NUEVO := :NEW.VALOR_CAMPO;
    END IF;
  END AFTER EACH ROW;
  AFTER STATEMENT IS
  BEGIN
    BEGIN
      SELECT VALOR_CAMPO
      INTO   V_TALLER
      FROM   A7000025
      WHERE  NUM_SECU_SINI = V_NUM_SECU_SINI
      AND    NRO_ORDEN_SINI = V_NRO_ORDEN_SINI
	  AND    COD_NIVEL = 1
	  AND    COD_GRUPO = 1
      AND    COD_CAMPO = 'CEDULA_TALLER';
    EXCEPTION 
      WHEN NO_DATA_FOUND OR TOO_MANY_ROWS THEN
        V_TALLER := '0';
    END;
    IF NVL(V_TALLER,'0') <> V_TALLER_NUEVO AND V_TALLER_NUEVO <> '0' THEN 
        -- Insertar en la tabla de envio de correos bienvenidas oportunas un cambio de taller CSI-27
      sim_pck_bienvenida_oportuna.prc_insert_sim_envios_correos(V_NUM_SECU_SINI,
                                                              V_NRO_ORDEN_SINI);
    END IF;
  END AFTER STATEMENT;
END TRG_A7000025_TALLER;
/
