CREATE OR REPLACE TRIGGER TRG_SIM_HOMOLOGA_ORG_TRANSITO
  BEFORE INSERT ON  SIM_HOMOLOGA_ORG_TRANSITO 
  FOR EACH ROW
DECLARE
  V_SECUENCIA NUMBER(17) := 0;
BEGIN
  BEGIN
    SELECT SEC_SIM_HOMOLOGA_ORG_TRANSITO.NEXTVAL INTO V_SECUENCIA FROM DUAL;
  END;
   :NEW.SECUENCIA := V_SECUENCIA;
END  TRG_SIM_HOMOLOGA_ORG_TRANSITO;
/
