CREATE OR REPLACE TRIGGER trg_alarmas_asegurado
AFTER INSERT OR UPDATE OF MANEJA_MOTOCICLETA,DEPORTES_ALTO_RIESGO ON EMI_DATOS_ASEGURADO FOR EACH ROW
DECLARE

 --Man 15341 Se adiciona el cambio de tomador para validar las alarmas
 VAR_NUM NUMBER;

BEGIN

 SELECT COUNT(*)
   INTO VAR_NUM
   FROM EMI_MUTATING
  WHERE NUMERO_SOLICITUD = :NEW.NUMERO_SOLICITUD
    AND TABLE_NAME = 'EMI_CAMBIA_TOMADOR';

 IF VAR_NUM = 0 THEN
   IF (NVL(:NEW.MANEJA_MOTOCICLETA,'-') <> NVL(:OLD.MANEJA_MOTOCICLETA,'-') AND :NEW.MANEJA_MOTOCICLETA = 'S')THEN
       UPDATE EMI_SOLICITUD_POLIZA
          SET OBSERVACION_USUARIO = OBSERVACION_USUARIO || ' -> '||:NEW.USUARIO_TRANSACCION||' Fecha: '||sysdate||' '|| ' ALARMA: MANEJA MOTOCICLETA'
        WHERE NUMERO_SOLICITUD = :NEW.NUMERO_SOLICITUD;
   END IF;

   IF (NVL(:NEW.DEPORTES_ALTO_RIESGO,'-') <> NVL(:OLD.DEPORTES_ALTO_RIESGO,'-') AND :NEW.DEPORTES_ALTO_RIESGO = 'S')THEN
       UPDATE EMI_SOLICITUD_POLIZA
          SET OBSERVACION_USUARIO = OBSERVACION_USUARIO || ' -> '||:NEW.USUARIO_TRANSACCION||' Fecha: '||sysdate||' '|| ' ALARMA: PRACTICA DEPORTES ALTO RIESGO'
        WHERE NUMERO_SOLICITUD = :NEW.NUMERO_SOLICITUD;
   END IF;
 ELSE
    DELETE FROM EMI_MUTATING WHERE NUMERO_SOLICITUD = :NEW.NUMERO_SOLICITUD AND TABLE_NAME = 'EMI_CAMBIA_TOMADOR';
 END IF;
EXCEPTION WHEN OTHERS THEN
  RAISE_APPLICATION_ERROR(-20005,'Error actualizando Alarmas '||SQLERRM);
END;
/
