CREATE OR REPLACE TRIGGER TRG_BIU_R_A502113_TES
  BEFORE DELETE OR UPDATE OF MCA_ESTADO,DOCUMENTO
     ON A5021113
  FOR EACH ROW
BEGIN
  IF DELETING THEN
     BEGIN
        INSERT INTO AUD5021113 (NUM_LIQUIDACION,COD_CIA,
         SUB_TIPO_ORD,MCA_ESTADO_ANT,MCA_ESTADO_NVO,DOCUMENTO_ANT,DOCUMENTO_NVO,
         TPO_NVDAD,USRIO,FCHA_NVDAD)  VALUES
         (:OLD.NUM_LIQUIDACION,:OLD.COD_CIA,
         :OLD.SUB_TIPO_ORD,:OLD.MCA_ESTADO,:OLD.MCA_ESTADO,
         :OLD.DOCUMENTO,:OLD.DOCUMENTO,'B',USER,SYSDATE);
       EXCEPTION WHEN OTHERS THEN
         RAISE_APPLICATION_ERROR(-20600,'Error insertando la auditoria de borrado AUD5021113.');
     END;

  ELSIF UPDATING THEN
     IF NVL(:OLD.DOCUMENTO,0) <> 0 AND (:OLD.DOCUMENTO <> :NEW.DOCUMENTO) THEN
        BEGIN
           INSERT INTO AUD5021113 (NUM_LIQUIDACION,COD_CIA,
            SUB_TIPO_ORD,MCA_ESTADO_ANT,MCA_ESTADO_NVO,DOCUMENTO_ANT,DOCUMENTO_NVO,
            TPO_NVDAD,USRIO,FCHA_NVDAD)  VALUES
            (:OLD.NUM_LIQUIDACION,:OLD.COD_CIA,
            :OLD.SUB_TIPO_ORD,:OLD.MCA_ESTADO,:OLD.MCA_ESTADO,
            :OLD.DOCUMENTO,:NEW.DOCUMENTO,'D',USER,SYSDATE);
          EXCEPTION WHEN OTHERS THEN
            RAISE_APPLICATION_ERROR(-20601,'Error insertando la auditoria de actualizacion AUD5021113.');
        END;
     END IF;
     IF (:OLD.MCA_ESTADO = 'T') AND (:OLD.MCA_ESTADO <> :NEW.MCA_ESTADO) THEN
        BEGIN
           INSERT INTO AUD5021113 (NUM_LIQUIDACION,COD_CIA,
            SUB_TIPO_ORD,MCA_ESTADO_ANT,MCA_ESTADO_NVO,DOCUMENTO_ANT,DOCUMENTO_NVO,
            TPO_NVDAD,USRIO,FCHA_NVDAD)  VALUES
            (:OLD.NUM_LIQUIDACION,:OLD.COD_CIA,
            :OLD.SUB_TIPO_ORD,:OLD.MCA_ESTADO,:NEW.MCA_ESTADO,
            :OLD.DOCUMENTO,:OLD.DOCUMENTO,'E',USER,SYSDATE);
          EXCEPTION WHEN OTHERS THEN
            RAISE_APPLICATION_ERROR(-20602,'Error insertando la auditoria de actualizacion AUD5021113.');
        END;
     END IF;
  END IF;
 EXCEPTION
  WHEN OTHERS THEN
     RAISE_APPLICATION_ERROR(-20603,'Error en trigger de auditoria tabla ');

end TRG_BIU_R_A5021113_TES;
/
