CREATE OR REPLACE TRIGGER "TRG_SEC_SIM_VALOR_DEDUCIBLES"
  BEFORE INSERT ON SIM_VALOR_DEDUCIBLES
  FOR EACH ROW
BEGIN

  :NEW.DDU_CODIGO := SEC_SIM_VALOR_DEDUCIBLES.NEXTVAL;

END TRG_SEC_SIM_VALOR_DEDUCIBLES;
/
