CREATE OR REPLACE TRIGGER "TRG_AIUD_R_SIM_NIT"
  after insert or update or delete on SIM_NIT_PAGO
  for each row
declare
v_ope varchar2(3) := null;
begin
 IF     DELETING  THEN v_ope := 'DEL';
  ELSIF UPDATING  THEN v_ope := 'UPD';
  ELSIF INSERTING THEN v_ope := 'INS';
  ELSE  V_OPE :='ERR';
 END IF;

  IF UPDATING OR INSERTING THEN
   insert into SIM_NIT_PAGO_JN (
  JN_OPERATION		,JN_ORACLE_USER		,JN_DATETIME	,JN_NOTES
  ,JN_APPLN		,JN_SESSION		,ID_NITPAGO	,TIPO_PAGO
  ,TDOC_PAGO		,NIT_PAGO		,ESTADO		,USUARIO_CREACION
  ,TDOC_CAUSACION	,NIT_CAUSACION		,VR_DEMANDA	,VR_ACUM_PAGADO
  ,FECHA_CREACION	,USUARIO_MODIFICA	,FECHA_MODIFICA	,COD_CIA
  ,ORDEN		,JUZGADO		,OBSERVACIONES	,FECHA_RECIBO
  ,NOMBRE_NIT_CAUSAC	,NOMBRE_NIT_PAGO ,PORCENTAJE_PAGO ,REFERENCIA)
  values      (
  v_ope            	,user                	,sysdate           	,NULL
  ,NULL            	,NULL                	,:NEW.ID_NITPAGO	,:NEW.TIPO_PAGO
  ,:NEW.TDOC_PAGO	,:NEW.NIT_PAGO	   	,:NEW.ESTADO		,:NEW.USUARIO_CREACION
  ,:NEW.TDOC_CAUSACION	,:NEW.NIT_CAUSACION	,:NEW.VR_DEMANDA	,:NEW.VR_ACUM_PAGADO
  ,:NEW.FECHA_CREACION	,:NEW.USUARIO_MODIFICA	,:NEW.FECHA_MODIFICA	,:NEW.COD_CIA
  ,:NEW.ORDEN		,:NEW.JUZGADO		,:NEW.OBSERVACIONES	,:NEW.FECHA_RECIBO
  ,:NEW.NOMBRE_NIT_CAUSAC	,:NEW.NOMBRE_NIT_PAGO ,:NEW.PORCENTAJE_PAGO ,:NEW.REFERENCIA  )        ;

  ELSIF DELETING THEN
  insert into SIM_NIT_PAGO_JN (
  JN_OPERATION		,JN_ORACLE_USER		,JN_DATETIME	,JN_NOTES
  ,JN_APPLN		,JN_SESSION		,ID_NITPAGO	,TIPO_PAGO
  ,TDOC_PAGO		,NIT_PAGO		,ESTADO		,USUARIO_CREACION
  ,TDOC_CAUSACION	,NIT_CAUSACION		,VR_DEMANDA	,VR_ACUM_PAGADO
  ,FECHA_CREACION	,USUARIO_MODIFICA	,FECHA_MODIFICA	,COD_CIA
  ,ORDEN		,JUZGADO		,OBSERVACIONES	,FECHA_RECIBO
  ,NOMBRE_NIT_CAUSAC	,NOMBRE_NIT_PAGO ,PORCENTAJE_PAGO ,REFERENCIA)
  values      (
  v_ope            	,user                	,sysdate           	,NULL
  ,NULL            	,NULL                	,:OLD.ID_NITPAGO	,:OLD.TIPO_PAGO
  ,:OLD.TDOC_PAGO	,:OLD.NIT_PAGO	   	,:OLD.ESTADO		,:OLD.USUARIO_CREACION
  ,:OLD.TDOC_CAUSACION	,:OLD.NIT_CAUSACION	,:OLD.VR_DEMANDA	,:OLD.VR_ACUM_PAGADO
  ,:OLD.FECHA_CREACION	,:OLD.USUARIO_MODIFICA	,:OLD.FECHA_MODIFICA	,:OLD.COD_CIA
  ,:OLD.ORDEN		,:OLD.JUZGADO		,:OLD.OBSERVACIONES	,:OLD.FECHA_RECIBO
  ,:OLD.NOMBRE_NIT_CAUSAC	,:OLD.NOMBRE_NIT_PAGO ,:OLD.PORCENTAJE_PAGO ,:OLD.REFERENCIA  )        ;
  END IF;
end;
/
