CREATE OR REPLACE TRIGGER TRG_BU_EMI_ACTUALIZA_ASEGURADO
  BEFORE UPDATE OF CAMBIA_TOMADOR ON EMI_SOLICITUD_POLIZA
  FOR EACH ROW
DECLARE

  var_num_aseg NUMBER;
  var_tipo_doc_aseg VARCHAR2(5);
  var_num_doc_aseg NUMBER;

BEGIN

  --Operaciones para cambio de tomador por asegurado
  IF :NEW.TIPO_NEGOCIO = 'C' THEN
    IF :OLD.CAMBIA_TOMADOR <> :NEW.CAMBIA_TOMADOR AND
       :NEW.CAMBIA_TOMADOR = 'S' AND :NEW.ESTADO_SOLICITUD = 'PEN' THEN

      SELECT COUNT(*)
        INTO var_num_aseg
        FROM EMI_CLIENTE EC
       WHERE EC.NUMERO_SOLICITUD = :NEW.NUMERO_SOLICITUD;

      IF var_num_aseg > 1 THEN
       BEGIN
        --Man 15341 Se adiciona el cambio de tomador para validar las alarmas
        DELETE FROM EMI_MUTATING WHERE NUMERO_SOLICITUD = :NEW.NUMERO_SOLICITUD AND TABLE_NAME = 'EMI_CAMBIA_TOMADOR';

        INSERT INTO EMI_MUTATING
        (num_rowid, table_name, mensaje, numero_solicitud, codigo_riesgo)
        VALUES
        (:NEW.ROWID, 'EMI_CAMBIA_TOMADOR', NULL, :NEW.numero_solicitud, NULL);

        SELECT EC.TIPDOC_CODIGO, EC.NUMERO_DOCUMENTO
          INTO var_tipo_doc_aseg, var_num_doc_aseg
          FROM EMI_CLIENTE EC
         WHERE EC.NUMERO_SOLICITUD = :NEW.NUMERO_SOLICITUD
           AND EC.CODIGO_RIESGO = 1;

        --Se cambia el tomador por asegurado temporal

        INSERT INTO EMI_CLIENTE
           (NUMERO_SOLICITUD,CODIGO_RIESGO,MARCA_APLICACION,ROL,DESC_ROL,FECHA_DILIGENCIAMIENTO,TIPDOC_CODIGO,
            DESC_TIPDOC,NUMERO_DOCUMENTO,FECHA_EXPEDICION,DIVPOL_CODIGO_EXPEDIDO_EN,LUGAR_EXPEDICION,
            DESC_LUGAR_EXP,PRIMER_NOMBRE,SEGUNDO_NOMBRE,PRIMER_APELLIDO,SEGUNDO_APELLIDO,FECHA_NACIMIENTO,
            EDAD_TARIFA,EDAD_EXTEN,DIVPOL_CODIGO_NACIDO_EN,LUGAR_NACIMIENTO,DESC_LUGAR_NAC,NACIONALIDAD,
            SEXO,ESTADO_CIVIL,DESC_ESTADO_CIVIL,AFI_SECUENCIA,AFI_DESCRIPCION,
            DIRECCION_RESIDENCIA,DIVPOL_CODIGO_RESIDENCIA,CIUDAD_RESIDENCIA,DESC_LUGAR_RES,
            TELEFONO_RESIDENCIA,NO_DE_CELULAR,FAX,EMAIL,CONTACTAR_EN,
            TIPO_ACTIVIDAD,
            COD_PROFESION,PROFESION,OCUPACION_ACTUAL,DESC_OCUPACION,ACTIVIDAD_ECONOMICA,DESC_ACTIVIDAD_ECONOMICA,
            EMPRESA_TRABAJA,CARGO,DIRECCION_TRABAJO,DIVPOL_CODIGO_TRABAJO,CIUDAD_TRABAJO,DESC_LUGAR_TRAB,
            TELEFONO,FAX_OFICINA,SERVIDOR_PUBLICO,MANEJA_RECURSOS_PUBLICOS,PUBLICAMENTE_EXPUESTA,VINCULO_PERSONA_RECONOCIDA,
            FECHA_ESTADOS_FINANCIEROS,MANEJA_MONEDA_EXTRANJERA,
            MONEDA_EXTRANJERA,OPERACIONES_INTERNACIONALES,TIPO_OPERACION_INTERNACIONAL,
            NRO_CUENTA_MONEDA_EXTRANJERA,BANCO_O_ENTIDAD,DIVPOL_PAIS_CUENTA,PAIS_DE_LA_CUENTA,DESC_PAIS_EXT,
            DIVPOL_CIUDAD_CUENTA,CIUDAD_DE_LA_CUENTA,DESC_CIUDAD_EXT,USUARIO_CREACION,FECHA_CREACION,
            USUARIO_TRANSACCION,FECHA_TRANSACCION,CLA_OCUPACION_ACTUAL,PRIMER_NOMBRE_REL_PEP,SEGUNDO_NOMBRE_REL_PEP,
            PRIMER_APELLIDO_REL_PEP,SEGUNDO_APELLIDO_REL_PEP,
            num_id_familiar_o_socio_pep,parentesco_familiar_socio_pep,cargo_familiar_socio_pep,
            total_patrimonio,posee_prod_financieros_ext,tipo_producto,monto,
            moneda,vlr_total_activos, vlr_total_pasivos,vlr_total_ingresos,vlr_total_egresos
           )
       SELECT NUMERO_SOLICITUD,CODIGO_RIESGO,MARCA_APLICACION,ROL,DESC_ROL,FECHA_DILIGENCIAMIENTO,TIPDOC_CODIGO,
            DESC_TIPDOC,NUMERO_DOCUMENTO,FECHA_EXPEDICION,DIVPOL_CODIGO_EXPEDIDO_EN,LUGAR_EXPEDICION,
            DESC_LUGAR_EXP,PRIMER_NOMBRE,SEGUNDO_NOMBRE,PRIMER_APELLIDO,SEGUNDO_APELLIDO,FECHA_NACIMIENTO,
            EDAD_TARIFA,EDAD_EXTEN,DIVPOL_CODIGO_NACIDO_EN,LUGAR_NACIMIENTO,DESC_LUGAR_NAC,NACIONALIDAD,
            SEXO,ESTADO_CIVIL,DESC_ESTADO_CIVIL,AFI_SECUENCIA,AFI_DESCRIPCION,
            DIRECCION_RESIDENCIA,DIVPOL_CODIGO_RESIDENCIA,CIUDAD_RESIDENCIA,DESC_LUGAR_RES,
            TELEFONO_RESIDENCIA,NO_DE_CELULAR,FAX,EMAIL,CONTACTAR_EN,
            TIPO_ACTIVIDAD,
            COD_PROFESION,PROFESION,OCUPACION_ACTUAL,DESC_OCUPACION,ACTIVIDAD_ECONOMICA,DESC_ACTIVIDAD_ECONOMICA,
            EMPRESA_TRABAJA,CARGO,DIRECCION_TRABAJO,DIVPOL_CODIGO_TRABAJO,CIUDAD_TRABAJO,DESC_LUGAR_TRAB,
            TELEFONO,FAX_OFICINA,SERVIDOR_PUBLICO,MANEJA_RECURSOS_PUBLICOS,PUBLICAMENTE_EXPUESTA,VINCULO_PERSONA_RECONOCIDA,
            FECHA_ESTADOS_FINANCIEROS,MANEJA_MONEDA_EXTRANJERA,
            MONEDA_EXTRANJERA,OPERACIONES_INTERNACIONALES,TIPO_OPERACION_INTERNACIONAL,
            NRO_CUENTA_MONEDA_EXTRANJERA,BANCO_O_ENTIDAD,DIVPOL_PAIS_CUENTA,PAIS_DE_LA_CUENTA,DESC_PAIS_EXT,
            DIVPOL_CIUDAD_CUENTA,CIUDAD_DE_LA_CUENTA,DESC_CIUDAD_EXT,USUARIO_CREACION,FECHA_CREACION,
            USUARIO_TRANSACCION,FECHA_TRANSACCION,CLA_OCUPACION_ACTUAL,PRIMER_NOMBRE_REL_PEP,SEGUNDO_NOMBRE_REL_PEP,
            PRIMER_APELLIDO_REL_PEP,SEGUNDO_APELLIDO_REL_PEP,
			      num_id_familiar_o_socio_pep,PARENTESCO_FAMILIAR_SOCIO_PEP,cargo_familiar_socio_pep,
		        total_patrimonio,posee_prod_financieros_ext,tipo_producto,monto,
			      moneda,vlr_total_activos, vlr_total_pasivos,vlr_total_ingresos,vlr_total_egresos
          FROM EMI_CLIENTE EC
         WHERE EC.CODIGO_RIESGO = 3
           AND EC.NUMERO_SOLICITUD = :NEW.NUMERO_SOLICITUD;

        INSERT INTO EMI_DATOS_ASEGURADO
              (NUMERO_SOLICITUD,CODIGO_RIESGO,ENTIDAD_SEGURIDAD_SOCIAL,ES_ZURDO,
               NIVEL_DE_EDUCACION,VIDA_PROTEGIDA,LICENCIA_PILOTO,MANEJA_MOTOCICLETA,
               DEPORTES_ALTO_RIESGO,OTRO_DEPORTE_ALTO_RIESGO,PRACTICA_OTROS_DEPORTES,
               CUALES_DEPORTES,ACTIVIDADES_LICITAS,CONDENADO_PENALMENTE,SECUESTRADO,
               RESIDE_EXTERIOR,USUARIO_CREACION,FECHA_CREACION,USUARIO_TRANSACCION,
               FECHA_TRANSACCION,INDEMNIZACION_PREVIA,LABORES_FISCALIZACION,CUALES_LABORES,
               VIDA_ASEGURADA,CIA_PROTEGIDA,MONTO_PROTEGIDO,CIA_ASEGURADA,MONTO_ASEGURADO,
               CUAL_ANEXO,MONTO_ANEXO)
        SELECT  NUMERO_SOLICITUD,4,ENTIDAD_SEGURIDAD_SOCIAL,ES_ZURDO,NIVEL_DE_EDUCACION,
                VIDA_PROTEGIDA,LICENCIA_PILOTO,MANEJA_MOTOCICLETA,DEPORTES_ALTO_RIESGO,
                OTRO_DEPORTE_ALTO_RIESGO,PRACTICA_OTROS_DEPORTES,CUALES_DEPORTES,
                ACTIVIDADES_LICITAS,CONDENADO_PENALMENTE,SECUESTRADO,RESIDE_EXTERIOR,
                USUARIO_CREACION,FECHA_CREACION,USUARIO_TRANSACCION,FECHA_TRANSACCION,
                INDEMNIZACION_PREVIA,LABORES_FISCALIZACION,CUALES_LABORES,VIDA_ASEGURADA,
                CIA_PROTEGIDA,MONTO_PROTEGIDO,CIA_ASEGURADA,MONTO_ASEGURADO,CUAL_ANEXO,MONTO_ANEXO
          FROM EMI_DATOS_ASEGURADO EA
         WHERE EA.CODIGO_RIESGO = 3
           AND EA.NUMERO_SOLICITUD = :NEW.NUMERO_SOLICITUD;

        UPDATE EMI_AMPAROS_ADICIONALES EA
           SET EA.CODIGO_RIESGO       = 4,
               EA.USUARIO_TRANSACCION = :NEW.USUARIO_TRANSACCION,
               EA.FECHA_TRANSACCION   = SYSDATE
         WHERE EA.CODIGO_RIESGO = 3
           AND EA.NUMERO_SOLICITUD = :NEW.NUMERO_SOLICITUD;

        UPDATE EMI_BLOQUE_MEDICO EB
           SET EB.CODIGO_RIESGO       = 4,
               EB.USUARIO_TRANSACCION = :NEW.USUARIO_TRANSACCION,
               EB.FECHA_TRANSACCION   = SYSDATE
         WHERE EB.CODIGO_RIESGO = 3
           AND EB.NUMERO_SOLICITUD = :NEW.NUMERO_SOLICITUD;

        UPDATE EMI_BENEFICIARIOS EN
           SET EN.CODIGO_RIESGO       = 4,
               EN.USUARIO_TRANSACCION = :NEW.USUARIO_TRANSACCION,
               EN.FECHA_TRANSACCION   = SYSDATE
         WHERE EN.CODIGO_RIESGO = 3
           AND EN.NUMERO_SOLICITUD = :NEW.NUMERO_SOLICITUD;

        UPDATE EMI_CONCEPTO_TECNICO ET
           SET ET.CODIGO_RIESGO       = 4,
               ET.USUARIO_TRANSACCION = :NEW.USUARIO_TRANSACCION,
               ET.FECHA_TRANSACCION   = SYSDATE
         WHERE ET.CODIGO_RIESGO = 3
           AND ET.NUMERO_SOLICITUD = :NEW.NUMERO_SOLICITUD;

        UPDATE EMI_ENFERMEDAD_ASEGURADO ES
           SET ES.CODIGO_RIESGO       = 4,
               ES.USUARIO_TRANSACCION = :NEW.USUARIO_TRANSACCION,
               ES.FECHA_TRANSACCION   = SYSDATE
         WHERE ES.CODIGO_RIESGO = 3
           AND ES.NUMERO_SOLICITUD = :NEW.NUMERO_SOLICITUD;

     EXCEPTION WHEN OTHERS THEN
       RAISE_APPLICATION_ERROR(-20852,'Error cambio tomador '||sqlerrm);
     END;

     BEGIN

        --Elimina el registro original del tomador para actualizar el segundo asegurado a tomador
        DELETE FROM EMI_DATOS_ASEGURADO ED
         WHERE ED.CODIGO_RIESGO = 3
           AND ED.NUMERO_SOLICITUD = :NEW.NUMERO_SOLICITUD;

        --Elimina el registro original del tomador para actualizar el segundo asegurado a tomador
        DELETE FROM EMI_CLIENTE EC
         WHERE EC.CODIGO_RIESGO = 3
           AND EC.NUMERO_SOLICITUD = :NEW.NUMERO_SOLICITUD;

         INSERT INTO EMI_CLIENTE
           (NUMERO_SOLICITUD,CODIGO_RIESGO,MARCA_APLICACION,ROL,DESC_ROL,FECHA_DILIGENCIAMIENTO,TIPDOC_CODIGO,
            DESC_TIPDOC,NUMERO_DOCUMENTO,FECHA_EXPEDICION,DIVPOL_CODIGO_EXPEDIDO_EN,LUGAR_EXPEDICION,
            DESC_LUGAR_EXP,PRIMER_NOMBRE,SEGUNDO_NOMBRE,PRIMER_APELLIDO,SEGUNDO_APELLIDO,FECHA_NACIMIENTO,
            EDAD_TARIFA,EDAD_EXTEN,DIVPOL_CODIGO_NACIDO_EN,LUGAR_NACIMIENTO,DESC_LUGAR_NAC,NACIONALIDAD,
            SEXO,ESTADO_CIVIL,DESC_ESTADO_CIVIL,AFI_SECUENCIA,AFI_DESCRIPCION,
            DIRECCION_RESIDENCIA,DIVPOL_CODIGO_RESIDENCIA,CIUDAD_RESIDENCIA,DESC_LUGAR_RES,
            TELEFONO_RESIDENCIA,NO_DE_CELULAR,FAX,EMAIL,CONTACTAR_EN,
            TIPO_ACTIVIDAD,
            COD_PROFESION,PROFESION,OCUPACION_ACTUAL,DESC_OCUPACION,ACTIVIDAD_ECONOMICA,DESC_ACTIVIDAD_ECONOMICA,
            EMPRESA_TRABAJA,CARGO,DIRECCION_TRABAJO,DIVPOL_CODIGO_TRABAJO,CIUDAD_TRABAJO,DESC_LUGAR_TRAB,
            TELEFONO,FAX_OFICINA,SERVIDOR_PUBLICO,MANEJA_RECURSOS_PUBLICOS,PUBLICAMENTE_EXPUESTA,VINCULO_PERSONA_RECONOCIDA,
            FECHA_ESTADOS_FINANCIEROS,MANEJA_MONEDA_EXTRANJERA,
            MONEDA_EXTRANJERA,OPERACIONES_INTERNACIONALES,TIPO_OPERACION_INTERNACIONAL,
            NRO_CUENTA_MONEDA_EXTRANJERA,BANCO_O_ENTIDAD,DIVPOL_PAIS_CUENTA,PAIS_DE_LA_CUENTA,DESC_PAIS_EXT,
            DIVPOL_CIUDAD_CUENTA,CIUDAD_DE_LA_CUENTA,DESC_CIUDAD_EXT,USUARIO_CREACION,FECHA_CREACION,
            USUARIO_TRANSACCION,FECHA_TRANSACCION,CLA_OCUPACION_ACTUAL,PRIMER_NOMBRE_REL_PEP,SEGUNDO_NOMBRE_REL_PEP,
            PRIMER_APELLIDO_REL_PEP,SEGUNDO_APELLIDO_REL_PEP,
            num_id_familiar_o_socio_pep,parentesco_familiar_socio_pep,cargo_familiar_socio_pep,
            total_patrimonio,posee_prod_financieros_ext,tipo_producto,monto,
            moneda,vlr_total_activos, vlr_total_pasivos,vlr_total_ingresos,vlr_total_egresos
           )
       SELECT NUMERO_SOLICITUD,3,MARCA_APLICACION,ROL,DESC_ROL,FECHA_DILIGENCIAMIENTO,TIPDOC_CODIGO,
            DESC_TIPDOC,NUMERO_DOCUMENTO,FECHA_EXPEDICION,DIVPOL_CODIGO_EXPEDIDO_EN,LUGAR_EXPEDICION,
            DESC_LUGAR_EXP,PRIMER_NOMBRE,SEGUNDO_NOMBRE,PRIMER_APELLIDO,SEGUNDO_APELLIDO,FECHA_NACIMIENTO,
            EDAD_TARIFA,EDAD_EXTEN,DIVPOL_CODIGO_NACIDO_EN,LUGAR_NACIMIENTO,DESC_LUGAR_NAC,NACIONALIDAD,
            SEXO,ESTADO_CIVIL,DESC_ESTADO_CIVIL,AFI_SECUENCIA,AFI_DESCRIPCION,
            DIRECCION_RESIDENCIA,DIVPOL_CODIGO_RESIDENCIA,CIUDAD_RESIDENCIA,DESC_LUGAR_RES,
            TELEFONO_RESIDENCIA,NO_DE_CELULAR,FAX,EMAIL,CONTACTAR_EN,
            TIPO_ACTIVIDAD,
            COD_PROFESION,PROFESION,OCUPACION_ACTUAL,DESC_OCUPACION,ACTIVIDAD_ECONOMICA,DESC_ACTIVIDAD_ECONOMICA,
            EMPRESA_TRABAJA,CARGO,DIRECCION_TRABAJO,DIVPOL_CODIGO_TRABAJO,CIUDAD_TRABAJO,DESC_LUGAR_TRAB,
            TELEFONO,FAX_OFICINA,SERVIDOR_PUBLICO,MANEJA_RECURSOS_PUBLICOS,PUBLICAMENTE_EXPUESTA,VINCULO_PERSONA_RECONOCIDA,
            FECHA_ESTADOS_FINANCIEROS,MANEJA_MONEDA_EXTRANJERA,
            MONEDA_EXTRANJERA,OPERACIONES_INTERNACIONALES,TIPO_OPERACION_INTERNACIONAL,
            NRO_CUENTA_MONEDA_EXTRANJERA,BANCO_O_ENTIDAD,DIVPOL_PAIS_CUENTA,PAIS_DE_LA_CUENTA,DESC_PAIS_EXT,
            DIVPOL_CIUDAD_CUENTA,CIUDAD_DE_LA_CUENTA,DESC_CIUDAD_EXT,USUARIO_CREACION,FECHA_CREACION,
            USUARIO_TRANSACCION,FECHA_TRANSACCION,CLA_OCUPACION_ACTUAL,PRIMER_NOMBRE_REL_PEP,SEGUNDO_NOMBRE_REL_PEP,
            PRIMER_APELLIDO_REL_PEP,SEGUNDO_APELLIDO_REL_PEP,
            num_id_familiar_o_socio_pep,parentesco_familiar_socio_pep,cargo_familiar_socio_pep,
            total_patrimonio,posee_prod_financieros_ext,tipo_producto,monto,
            moneda,vlr_total_activos, vlr_total_pasivos,vlr_total_ingresos,vlr_total_egresos
          FROM EMI_CLIENTE EC
         WHERE EC.CODIGO_RIESGO = 1
           AND EC.NUMERO_SOLICITUD = :NEW.NUMERO_SOLICITUD;

        INSERT INTO EMI_DATOS_ASEGURADO
              (NUMERO_SOLICITUD,CODIGO_RIESGO,ENTIDAD_SEGURIDAD_SOCIAL,ES_ZURDO,
               NIVEL_DE_EDUCACION,VIDA_PROTEGIDA,LICENCIA_PILOTO,MANEJA_MOTOCICLETA,
               DEPORTES_ALTO_RIESGO,OTRO_DEPORTE_ALTO_RIESGO,PRACTICA_OTROS_DEPORTES,
               CUALES_DEPORTES,ACTIVIDADES_LICITAS,CONDENADO_PENALMENTE,SECUESTRADO,
               RESIDE_EXTERIOR,USUARIO_CREACION,FECHA_CREACION,USUARIO_TRANSACCION,
               FECHA_TRANSACCION,INDEMNIZACION_PREVIA,LABORES_FISCALIZACION,CUALES_LABORES,
               VIDA_ASEGURADA,CIA_PROTEGIDA,MONTO_PROTEGIDO,CIA_ASEGURADA,MONTO_ASEGURADO,
               CUAL_ANEXO,MONTO_ANEXO)
        SELECT  NUMERO_SOLICITUD,3,ENTIDAD_SEGURIDAD_SOCIAL,ES_ZURDO,NIVEL_DE_EDUCACION,
                VIDA_PROTEGIDA,LICENCIA_PILOTO,MANEJA_MOTOCICLETA,DEPORTES_ALTO_RIESGO,
                OTRO_DEPORTE_ALTO_RIESGO,PRACTICA_OTROS_DEPORTES,CUALES_DEPORTES,
                ACTIVIDADES_LICITAS,CONDENADO_PENALMENTE,SECUESTRADO,RESIDE_EXTERIOR,
                USUARIO_CREACION,FECHA_CREACION,USUARIO_TRANSACCION,FECHA_TRANSACCION,
                INDEMNIZACION_PREVIA,LABORES_FISCALIZACION,CUALES_LABORES,VIDA_ASEGURADA,
                CIA_PROTEGIDA,MONTO_PROTEGIDO,CIA_ASEGURADA,MONTO_ASEGURADO,CUAL_ANEXO,MONTO_ANEXO
          FROM EMI_DATOS_ASEGURADO EA
         WHERE EA.CODIGO_RIESGO = 1
           AND EA.NUMERO_SOLICITUD = :NEW.NUMERO_SOLICITUD;



        -- Se cambia segundo asegurado por Tomador
        UPDATE EMI_AMPAROS_ADICIONALES EA
           SET EA.CODIGO_RIESGO       = 3,
               EA.USUARIO_TRANSACCION = :NEW.USUARIO_TRANSACCION,
               EA.FECHA_TRANSACCION   = SYSDATE
         WHERE EA.CODIGO_RIESGO = 1
           AND EA.NUMERO_SOLICITUD = :NEW.NUMERO_SOLICITUD;

        UPDATE EMI_BLOQUE_MEDICO EB
           SET EB.CODIGO_RIESGO       = 3,
               EB.USUARIO_TRANSACCION = :NEW.USUARIO_TRANSACCION,
               EB.FECHA_TRANSACCION   = SYSDATE
         WHERE EB.CODIGO_RIESGO = 1
           AND EB.NUMERO_SOLICITUD = :NEW.NUMERO_SOLICITUD;

        UPDATE EMI_BENEFICIARIOS EN
           SET EN.CODIGO_RIESGO       = 3,
               EN.USUARIO_TRANSACCION = :NEW.USUARIO_TRANSACCION,
               EN.FECHA_TRANSACCION   = SYSDATE
         WHERE EN.CODIGO_RIESGO = 1
           AND EN.NUMERO_SOLICITUD = :NEW.NUMERO_SOLICITUD;

        UPDATE EMI_CONCEPTO_TECNICO ET
           SET ET.CODIGO_RIESGO       = 3,
               ET.USUARIO_TRANSACCION = :NEW.USUARIO_TRANSACCION,
               ET.FECHA_TRANSACCION   = SYSDATE
         WHERE ET.CODIGO_RIESGO = 1
           AND ET.NUMERO_SOLICITUD = :NEW.NUMERO_SOLICITUD;

        UPDATE EMI_ENFERMEDAD_ASEGURADO ES
           SET ES.CODIGO_RIESGO       = 3,
               ES.USUARIO_TRANSACCION = :NEW.USUARIO_TRANSACCION,
               ES.FECHA_TRANSACCION   = SYSDATE
         WHERE ES.CODIGO_RIESGO = 1
           AND ES.NUMERO_SOLICITUD = :NEW.NUMERO_SOLICITUD;

     EXCEPTION WHEN OTHERS THEN
       RAISE_APPLICATION_ERROR(-20853,'Error cambio segundo aseg '||sqlerrm);
     END;

     BEGIN

       DELETE FROM EMI_AMPAROS_ADICIONALES EA WHERE EA.CODIGO_RIESGO = 1 AND EA.NUMERO_SOLICITUD = :NEW.NUMERO_SOLICITUD;
       DELETE FROM EMI_BLOQUE_MEDICO EB WHERE EB.CODIGO_RIESGO = 1 AND EB.NUMERO_SOLICITUD = :NEW.NUMERO_SOLICITUD;
       DELETE FROM EMI_BENEFICIARIOS EN WHERE EN.CODIGO_RIESGO = 1 AND EN.NUMERO_SOLICITUD = :NEW.NUMERO_SOLICITUD;
       DELETE FROM EMI_CONCEPTO_TECNICO ET WHERE ET.CODIGO_RIESGO = 1 AND ET.NUMERO_SOLICITUD = :NEW.NUMERO_SOLICITUD;
       DELETE FROM EMI_ENFERMEDAD_ASEGURADO ES WHERE ES.CODIGO_RIESGO = 1 AND ES.NUMERO_SOLICITUD = :NEW.NUMERO_SOLICITUD;
       DELETE FROM EMI_DATOS_ASEGURADO ED WHERE ED.CODIGO_RIESGO = 1 AND ED.NUMERO_SOLICITUD = :NEW.NUMERO_SOLICITUD;
       DELETE FROM EMI_CLIENTE EC WHERE EC.CODIGO_RIESGO = 1 AND EC.NUMERO_SOLICITUD = :NEW.NUMERO_SOLICITUD;

       INSERT INTO EMI_CLIENTE
           (NUMERO_SOLICITUD,CODIGO_RIESGO,MARCA_APLICACION,ROL,DESC_ROL,FECHA_DILIGENCIAMIENTO,TIPDOC_CODIGO,
            DESC_TIPDOC,NUMERO_DOCUMENTO,FECHA_EXPEDICION,DIVPOL_CODIGO_EXPEDIDO_EN,LUGAR_EXPEDICION,
            DESC_LUGAR_EXP,PRIMER_NOMBRE,SEGUNDO_NOMBRE,PRIMER_APELLIDO,SEGUNDO_APELLIDO,FECHA_NACIMIENTO,
            EDAD_TARIFA,EDAD_EXTEN,DIVPOL_CODIGO_NACIDO_EN,LUGAR_NACIMIENTO,DESC_LUGAR_NAC,NACIONALIDAD,
            SEXO,ESTADO_CIVIL,DESC_ESTADO_CIVIL,AFI_SECUENCIA,AFI_DESCRIPCION,
            DIRECCION_RESIDENCIA,DIVPOL_CODIGO_RESIDENCIA,CIUDAD_RESIDENCIA,DESC_LUGAR_RES,
            TELEFONO_RESIDENCIA,NO_DE_CELULAR,FAX,EMAIL,CONTACTAR_EN,
            TIPO_ACTIVIDAD,
            COD_PROFESION,PROFESION,OCUPACION_ACTUAL,DESC_OCUPACION,ACTIVIDAD_ECONOMICA,DESC_ACTIVIDAD_ECONOMICA,
            EMPRESA_TRABAJA,CARGO,DIRECCION_TRABAJO,DIVPOL_CODIGO_TRABAJO,CIUDAD_TRABAJO,DESC_LUGAR_TRAB,
            TELEFONO,FAX_OFICINA,SERVIDOR_PUBLICO,MANEJA_RECURSOS_PUBLICOS,PUBLICAMENTE_EXPUESTA,VINCULO_PERSONA_RECONOCIDA,
            FECHA_ESTADOS_FINANCIEROS,MANEJA_MONEDA_EXTRANJERA,
            MONEDA_EXTRANJERA,OPERACIONES_INTERNACIONALES,TIPO_OPERACION_INTERNACIONAL,
            NRO_CUENTA_MONEDA_EXTRANJERA,BANCO_O_ENTIDAD,DIVPOL_PAIS_CUENTA,PAIS_DE_LA_CUENTA,DESC_PAIS_EXT,
            DIVPOL_CIUDAD_CUENTA,CIUDAD_DE_LA_CUENTA,DESC_CIUDAD_EXT,USUARIO_CREACION,FECHA_CREACION,
            USUARIO_TRANSACCION,FECHA_TRANSACCION,CLA_OCUPACION_ACTUAL,PRIMER_NOMBRE_REL_PEP,SEGUNDO_NOMBRE_REL_PEP,
            PRIMER_APELLIDO_REL_PEP,SEGUNDO_APELLIDO_REL_PEP,
            num_id_familiar_o_socio_pep,parentesco_familiar_socio_pep,cargo_familiar_socio_pep,
            total_patrimonio,posee_prod_financieros_ext,tipo_producto,monto,
            moneda,vlr_total_activos, vlr_total_pasivos,vlr_total_ingresos,vlr_total_egresos
           )
       SELECT NUMERO_SOLICITUD,1,MARCA_APLICACION,ROL,DESC_ROL,FECHA_DILIGENCIAMIENTO,TIPDOC_CODIGO,
            DESC_TIPDOC,NUMERO_DOCUMENTO,FECHA_EXPEDICION,DIVPOL_CODIGO_EXPEDIDO_EN,LUGAR_EXPEDICION,
            DESC_LUGAR_EXP,PRIMER_NOMBRE,SEGUNDO_NOMBRE,PRIMER_APELLIDO,SEGUNDO_APELLIDO,FECHA_NACIMIENTO,
            EDAD_TARIFA,EDAD_EXTEN,DIVPOL_CODIGO_NACIDO_EN,LUGAR_NACIMIENTO,DESC_LUGAR_NAC,NACIONALIDAD,
            SEXO,ESTADO_CIVIL,DESC_ESTADO_CIVIL,AFI_SECUENCIA,AFI_DESCRIPCION,
            DIRECCION_RESIDENCIA,DIVPOL_CODIGO_RESIDENCIA,CIUDAD_RESIDENCIA,DESC_LUGAR_RES,
            TELEFONO_RESIDENCIA,NO_DE_CELULAR,FAX,EMAIL,CONTACTAR_EN,
            TIPO_ACTIVIDAD,
            COD_PROFESION,PROFESION,OCUPACION_ACTUAL,DESC_OCUPACION,ACTIVIDAD_ECONOMICA,DESC_ACTIVIDAD_ECONOMICA,
            EMPRESA_TRABAJA,CARGO,DIRECCION_TRABAJO,DIVPOL_CODIGO_TRABAJO,CIUDAD_TRABAJO,DESC_LUGAR_TRAB,
            TELEFONO,FAX_OFICINA,SERVIDOR_PUBLICO,MANEJA_RECURSOS_PUBLICOS,PUBLICAMENTE_EXPUESTA,VINCULO_PERSONA_RECONOCIDA,
            FECHA_ESTADOS_FINANCIEROS,MANEJA_MONEDA_EXTRANJERA,
            MONEDA_EXTRANJERA,OPERACIONES_INTERNACIONALES,TIPO_OPERACION_INTERNACIONAL,
            NRO_CUENTA_MONEDA_EXTRANJERA,BANCO_O_ENTIDAD,DIVPOL_PAIS_CUENTA,PAIS_DE_LA_CUENTA,DESC_PAIS_EXT,
            DIVPOL_CIUDAD_CUENTA,CIUDAD_DE_LA_CUENTA,DESC_CIUDAD_EXT,USUARIO_CREACION,FECHA_CREACION,
            USUARIO_TRANSACCION,FECHA_TRANSACCION,CLA_OCUPACION_ACTUAL,PRIMER_NOMBRE_REL_PEP,SEGUNDO_NOMBRE_REL_PEP,
            PRIMER_APELLIDO_REL_PEP,SEGUNDO_APELLIDO_REL_PEP,
            num_id_familiar_o_socio_pep,parentesco_familiar_socio_pep,cargo_familiar_socio_pep,
            total_patrimonio,posee_prod_financieros_ext,tipo_producto,monto,
            moneda,vlr_total_activos, vlr_total_pasivos,vlr_total_ingresos,vlr_total_egresos
          FROM EMI_CLIENTE EC
         WHERE EC.CODIGO_RIESGO = 4
           AND EC.NUMERO_SOLICITUD = :NEW.NUMERO_SOLICITUD;

        INSERT INTO EMI_DATOS_ASEGURADO
              (NUMERO_SOLICITUD,CODIGO_RIESGO,ENTIDAD_SEGURIDAD_SOCIAL,ES_ZURDO,
               NIVEL_DE_EDUCACION,VIDA_PROTEGIDA,LICENCIA_PILOTO,MANEJA_MOTOCICLETA,
               DEPORTES_ALTO_RIESGO,OTRO_DEPORTE_ALTO_RIESGO,PRACTICA_OTROS_DEPORTES,
               CUALES_DEPORTES,ACTIVIDADES_LICITAS,CONDENADO_PENALMENTE,SECUESTRADO,
               RESIDE_EXTERIOR,USUARIO_CREACION,FECHA_CREACION,USUARIO_TRANSACCION,
               FECHA_TRANSACCION,INDEMNIZACION_PREVIA,LABORES_FISCALIZACION,CUALES_LABORES,
               VIDA_ASEGURADA,CIA_PROTEGIDA,MONTO_PROTEGIDO,CIA_ASEGURADA,MONTO_ASEGURADO,
               CUAL_ANEXO,MONTO_ANEXO)
        SELECT  NUMERO_SOLICITUD,1,ENTIDAD_SEGURIDAD_SOCIAL,ES_ZURDO,NIVEL_DE_EDUCACION,
                VIDA_PROTEGIDA,LICENCIA_PILOTO,MANEJA_MOTOCICLETA,DEPORTES_ALTO_RIESGO,
                OTRO_DEPORTE_ALTO_RIESGO,PRACTICA_OTROS_DEPORTES,CUALES_DEPORTES,
                ACTIVIDADES_LICITAS,CONDENADO_PENALMENTE,SECUESTRADO,RESIDE_EXTERIOR,
                USUARIO_CREACION,FECHA_CREACION,USUARIO_TRANSACCION,FECHA_TRANSACCION,
                INDEMNIZACION_PREVIA,LABORES_FISCALIZACION,CUALES_LABORES,VIDA_ASEGURADA,
                CIA_PROTEGIDA,MONTO_PROTEGIDO,CIA_ASEGURADA,MONTO_ASEGURADO,CUAL_ANEXO,MONTO_ANEXO
          FROM EMI_DATOS_ASEGURADO EA
         WHERE EA.CODIGO_RIESGO = 4
           AND EA.NUMERO_SOLICITUD = :NEW.NUMERO_SOLICITUD;

        -- Se cambia asegurado temporal por segundo asegurado
        UPDATE EMI_AMPAROS_ADICIONALES EA
           SET EA.CODIGO_RIESGO       = 1,
               EA.USUARIO_TRANSACCION = :NEW.USUARIO_TRANSACCION,
               EA.FECHA_TRANSACCION   = SYSDATE
         WHERE EA.CODIGO_RIESGO = 4
           AND EA.NUMERO_SOLICITUD = :NEW.NUMERO_SOLICITUD;

        UPDATE EMI_BLOQUE_MEDICO EB
           SET EB.CODIGO_RIESGO       = 1,
               EB.USUARIO_TRANSACCION = :NEW.USUARIO_TRANSACCION,
               EB.FECHA_TRANSACCION   = SYSDATE
         WHERE EB.CODIGO_RIESGO = 4
           AND EB.NUMERO_SOLICITUD = :NEW.NUMERO_SOLICITUD;

        UPDATE EMI_BENEFICIARIOS EN
           SET EN.CODIGO_RIESGO       = 1,
               EN.USUARIO_TRANSACCION = :NEW.USUARIO_TRANSACCION,
               EN.FECHA_TRANSACCION   = SYSDATE
         WHERE EN.CODIGO_RIESGO = 4
           AND EN.NUMERO_SOLICITUD = :NEW.NUMERO_SOLICITUD;

        UPDATE EMI_CONCEPTO_TECNICO ET
           SET ET.CODIGO_RIESGO       = 1,
               ET.USUARIO_TRANSACCION = :NEW.USUARIO_TRANSACCION,
               ET.FECHA_TRANSACCION   = SYSDATE
         WHERE ET.CODIGO_RIESGO = 4
           AND ET.NUMERO_SOLICITUD = :NEW.NUMERO_SOLICITUD;

        UPDATE EMI_ENFERMEDAD_ASEGURADO ES
           SET ES.CODIGO_RIESGO       = 1,
               ES.USUARIO_TRANSACCION = :NEW.USUARIO_TRANSACCION,
               ES.FECHA_TRANSACCION   = SYSDATE
         WHERE ES.CODIGO_RIESGO = 4
           AND ES.NUMERO_SOLICITUD = :NEW.NUMERO_SOLICITUD;

        DELETE FROM EMI_DATOS_ASEGURADO ED
         WHERE ED.CODIGO_RIESGO = 4
           AND ED.NUMERO_SOLICITUD = :NEW.NUMERO_SOLICITUD;

        DELETE FROM EMI_CLIENTE EC
         WHERE EC.CODIGO_RIESGO = 4
           AND EC.NUMERO_SOLICITUD = :NEW.NUMERO_SOLICITUD;

      --Se actualiza la solicitud de tomador
       IF var_tipo_doc_aseg is not null AND var_num_doc_aseg is not null THEN
          :NEW.TIPO_DOCUMENTO := var_tipo_doc_aseg;
          :NEW.NUMERO_DOCUMENTO := var_num_doc_aseg;
       END IF;
     EXCEPTION WHEN OTHERS THEN
       RAISE_APPLICATION_ERROR(-20854,'Error primer aseg '||sqlerrm);
     END;
      END IF;
    END IF;
  END IF;
END;
/
