CREATE OR REPLACE TRIGGER "TRG_HIST_CLASSIFICACION" AFTER
  INSERT OR
  UPDATE ON IND_REGLAS_CLASIFICACION FOR EACH ROW
BEGIN
  INSERT
  INTO OPS$PUMA.SIM_CLASSIFICACION_REGLAS_JN
    (
      ID,
      CONSECUENCIA,
      PRODUCTO,
      SCORE_RIESGO,
      COBERTURA ,
      CAUSA,
      MODELO_RIESGO_PRETENSION,
      RESULTADO_ENCUESTA,
      MOTOR_CLASIFICACION_CASO,
      CLASIFICACION_CASO_CODE,
      CLV,
      COMPANY,
      SECCION,
      FECHA_MODIFICACION,
      USUARIO_MODIFICACION,
      FECHA_BAJA
    )
    VALUES
    (
      :NEW.ID,
      :NEW.CONSECUENCIA,
      :NEW.PRODUCTO,
      :NEW.SCORE_RIESGO,
      :NEW.COBERTURA ,
      :NEW.CAUSA,
      :NEW.MODELO_RIESGO_PRETENSION,
      :NEW.RESULTADO_ENCUESTA,
      :NEW.MOTOR_CLASIFICACION_CASO,
      :NEW.CLASIFICACION_CASO_CODE,
      :NEW.CLV,
      :NEW.COMPANY,
      :NEW.SECCION,
      :NEW.FECHA_CREACION,
      :NEW.USUARIO_CREACION,
      :NEW.FECHA_BAJA
    );
END TRG_HIST_CLASSIFICACION;
/
