CREATE OR REPLACE TRIGGER TRG_SIM_COSTOS_MARGINALES 
  BEFORE INSERT ON  SIM_COSTOS_MARGINALES 
  FOR EACH ROW
DECLARE
  V_SECUENCIA NUMBER(17) := 0;
BEGIN
  BEGIN
    SELECT SEC_SIM_COSTOS_MARGINALES.NEXTVAL INTO V_SECUENCIA FROM DUAL;
  END;
   :NEW.SECUENCIA := V_SECUENCIA;
END  TRG_SIM_COSTOS_MARGINALES;
/
