CREATE OR REPLACE TRIGGER TRG_BUDR_CUENTAS_GESTION_BANCO
BEFORE INSERT OR UPDATE OR DELETE ON SIM_CUENTAS_GESTION_BANCOS
FOR EACH ROW
DECLARE
  vl_ip_equipo_maquina  SIM_HIST_CUENTAS_GESTION_BANCO.IP_EQUIPO_MAQUINA%TYPE;
BEGIN
  vl_ip_equipo_maquina := 'IP: '||sys_context('USERENV','ip_address')||', Host: '||sys_context('USERENV','host');
  If (INSERTING OR UPDATING) AND :NEW.ES_BANCO_CUENTA IN ('A','C') THEN -- Aprovechamiento o Cuenta
    :NEW.CUENTA_SIMPLIFICADA := NULL;
  End If;
  IF DELETING THEN
    INSERT INTO SIM_HIST_CUENTAS_GESTION_BANCO (SECUENCIA, ROWID_CUENTAS_GESTION_BANCOS,
    FECHA_OPERACION, TIPO_OPERACION, USUARIO_OPERACION, IP_EQUIPO_MAQUINA,
    COD_CIA, CUENTA_CONTABLE, ES_BANCO_CUENTA, ES_CUENTA_TERCERO,
    CUENTA_SIMPLIFICADA, FECHA_CREACION, USUARIO_CREACION, FECHA_MODIFICACION,
    USUARIO_MODIFICACION, OBSERVACION, FECHA_ALTA, FECHA_BAJA)
    VALUES (SEQ_HIST_CUENTAS_GESTION_BANCO.NEXTVAL, :OLD.ROWID, SYSDATE, 'B',
    :OLD.USUARIO_CREACION, vl_ip_equipo_maquina, :OLD.COD_CIA, :OLD.CUENTA_CONTABLE,
    :OLD.ES_BANCO_CUENTA, :OLD.ES_CUENTA_TERCERO, :OLD.CUENTA_SIMPLIFICADA,
    :OLD.FECHA_CREACION, :OLD.USUARIO_CREACION, :OLD.FECHA_MODIFICACION,
    :OLD.USUARIO_MODIFICACION, :OLD.OBSERVACION, :OLD.FECHA_ALTA, :OLD.FECHA_BAJA);
  ELSIF UPDATING THEN
    INSERT INTO SIM_HIST_CUENTAS_GESTION_BANCO (SECUENCIA, ROWID_CUENTAS_GESTION_BANCOS,
    FECHA_OPERACION, TIPO_OPERACION, USUARIO_OPERACION, IP_EQUIPO_MAQUINA,
    COD_CIA, CUENTA_CONTABLE, ES_BANCO_CUENTA, ES_CUENTA_TERCERO,
    CUENTA_SIMPLIFICADA, FECHA_CREACION, USUARIO_CREACION, FECHA_MODIFICACION,
    USUARIO_MODIFICACION, OBSERVACION, FECHA_ALTA, FECHA_BAJA)
    VALUES (SEQ_HIST_CUENTAS_GESTION_BANCO.NEXTVAL, :OLD.ROWID, SYSDATE, 'A',
    :OLD.USUARIO_CREACION, vl_ip_equipo_maquina, :OLD.COD_CIA, :OLD.CUENTA_CONTABLE,
    :OLD.ES_BANCO_CUENTA, :OLD.ES_CUENTA_TERCERO, :OLD.CUENTA_SIMPLIFICADA,
    :OLD.FECHA_CREACION, :OLD.USUARIO_CREACION, :OLD.FECHA_MODIFICACION,
    :OLD.USUARIO_MODIFICACION, :OLD.OBSERVACION, :OLD.FECHA_ALTA, :OLD.FECHA_BAJA);
    -- Validaciones
    SIM_PCK_PAGOS_MASIVOS_CG.Prc_Cargar(p_cod_cia => :NEW.COD_CIA,
    p_cuenta_contable => :NEW.CUENTA_CONTABLE, p_es_banco_cuenta => :NEW.ES_BANCO_CUENTA,
    p_fecha_alta => :NEW.FECHA_ALTA, p_fecha_baja => :NEW.FECHA_BAJA,
    p_rowid => :NEW.ROWID);
  END IF;
END TRG_BUDR_CUENTAS_GESTION_BANCO;
/
