CREATE OR REPLACE TRIGGER trg_biu_c2700001_fecnace
  BEFORE INSERT OR UPDATE OF FEC_NACE
  ON C2700001 
  FOR EACH ROW
BEGIN
  IF TRIM (:NEW.FEC_NACE) IS NOT NULL
 AND --        (:NEW.FEC_NACE <= TO_DATE('01-JAN-1920','DD-MON-YYYY') OR
     (:NEW.FEC_NACE <= TO_DATE ('01/01/1920', 'DD/MM/YYYY')
   OR :NEW.FEC_NACE > TRUNC (SYSDATE) - 3650)
  THEN
    RAISE_APPLICATION_ERROR (-20502, 'FECHA DE NACIMIENTO NO ESTA ENTRE LOS RANGOS');
  END IF;
END;
/
