CREATE OR REPLACE TRIGGER "TRG_SEC_SIM_COBERTURA_FILTRO"
  BEFORE INSERT ON SIM_COBERTURA_FILTRO
  FOR EACH ROW
BEGIN

  :NEW.CBR_CODIGO := SEC_SIM_COBERTURA_FILTRO.NEXTVAL;

END TRG_SEC_SIM_COBERTURA_FILTRO;
/
