# Perfil de Producción (AWS ECS Fargate)
# Activación: --spring.profiles.active=pdn

spring:
  main:
    lazy-initialization: true
  sql:
    init:
      mode: never

cloud:
  aws:
    region:
      static: us-east-1

bsg:
  security:
    deployment: pdn
    redis:
      enabled: true
    auth:
      reset-password-base-url: ${BSG_SECURITY_AUTH_RESET_PASSWORD_BASE_URL:https://app.example.invalid/reset-password}
    aws:
      dynamodb:
        endpoint: "" # Forzamos a que use el endpoint real de AWS, no localstack

management:
  endpoint:
    health:
      show-details: never
  health:
    redis:
      enabled: false

logging:
  level:
    root: WARN
    com.bsg.security: INFO
    org.springframework.r2dbc.core: WARN
    org.springframework.data.r2dbc: WARN
    io.r2dbc: WARN
