# Clave local (no subir a git). Copia desde .pinecone.local.properties.example si hace falta.
docviz.vector.pinecone-api-key=pcsk_4d9Rv9_QY9EPdmo1itSUDJ3NV2eBqvmUZD5FzGARfGRXNUnNemiNM4aAEC5G95rypxtba4
